<h1>Reactivate inactive Record</h1>

<p><b>Title:</b> <?= $this->etd->title() ?><br/>
<b>Author:</b> <?= $this->etd->author() ?><br/>
<b>Status before being marked inactive:</b> <?= $this->previous_status ?>
</p>

<form name="reactivate" method="post"
   action="<?= $this->url(array("action" => "do-reactivate"))?>">
<?= $this->formHidden("pid", $this->etd->pid()) ?>

Reactivate record with status:
  <?= $this->formSelect("status", $this->previous_status, null, $this->status_opts) ?>

<p><?= $this->formLabel("reason", "Reason for reactivation: "); ?>   
<?= $this->formText("reason", "", array("size" => 50)); ?></p>

  <?= $this->formSubmit("reactivate", "Reactivate"); ?>
</form>