<? if (isset($this->current_user) && $this->current_user->hasUnpublishedEtd() && sizeOf($this->current_user->getUsersEtds()) > 0): ?>
  <? $user_etds = $this->current_user->getUsersEtds(); ?>
<div class="notice">
    Your submission, <a class="etd-title" href="<?= $this->url(array("controller" => "view",
    "action" => "record", "pid" => $user_etds[0]->pid)) ?>"><?= $user_etds[0]->title(); ?></a>,
    is currently in <b><?= $user_etds[0]->status() ?></b> status.
</div>
<? endif ?>
