<div id="calendar">
<h2>Calendar</h2>
<!-- FIXME: how should this be dynamically stored/updated? -->

<p><b>September 14, 2007:</b> Degree Applications Due for December Graduation</p>

<p><b>November 9, 2007:</b> Dissertations Due at Graduate School for December Graduation</p>

<p><b>February 8, 2008:</b> Degree Applications Due for May Graduation</p>

<p><b>March 21, 2008:</b> Dissertations Due at Graduate School for May Graduation</p>

<p><b>May 12, 2008:</b> Commencement</p>

</div>

