<div id="news">
  <h2>News and Announcements</h2>
   
<p><b>Intellectual Property Rights Workshops for Fall graduates</b><br/>

The Graduate School and the University Libraries Intellectual Property Rights Office will be holding workshops for graduate students on copyright law and author rights and responsibilities.  All graduate students should plan on attending one of these workshops while at Emory.  They will help you prepare your thesis or dissertation, and will provide vital information for all your future academic publishing endeavors.<br/>
The workshop will last one hour, and for your convenience, we have scheduled several dates in October.  Also, several sessions will have a particular focus to address concerns specific to a discipline.<br/>
Thursday, October 23, noon to 1 pm, Woodruff Library Room 312 – focus on Humanities & Social Sciences.<br/>
Tuesday, October 28, 4 pm to 5 pm, Woodruff Library Room 312 – general session.<br/>
Wednesday, October 29, noon to 1 pm, Rollins School of Public Health, Rita Rollins Room, 8th floor – focus on Sciences.<br/>
Thursday, October 30, noon to 1 pm, Woodruff Library Room 312 – focus on permissions for images in Art History.<br/>
If you cannot attend a session with a focus related to your discipline, feel free to attend the general session.  Each workshop will allow time for specific questions.<br/>
If you attended one of the workshops last semester, no need to attend again, but feel free to contact Lisa Macklin (lisa.macklin@emory.edu or 404-727-1535) or Heather Williams (hrwilli@emory.edu or 404- 727–0127) in the library if you have questions.<br/>
We look forward to seeing you there.  Please RSVP to Heather Williams at hrwilli@emory.edu or 7-0127 so we know how many students to expect.  If you have any questions, please contact Heather.</p>

<p><b>ETD Submission Workshops for Fall graduates</b><br/>

We will be holding workshops for students submitting their theses and dissertations on Thurs., Oct 30 from 4:00-5:00 in Woodruff Library Room 312 and on Mon., Nov. 4 from 12:00 to 1:00 in Woodruff Library Room 314.<br/>
Feel free to drop by any time during these hours and we will assist you with your submission.</p>

<p><b>Electronic Submission of Theses and Dissertations Now Required </b><br/>
All students completing their degree programs in the Emory Graduate School must now
submit their theses and dissertations electronically. <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Detailed instructions on submitting your ETD</a> are available on the site. Please contact 
the ETD staff at <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
if you need assistance.  Any questions on graduation 
requirements should be referred to the Graduate School.</p>
 
<p><b>Submission Form for All ETD Program Participants </b><br>
 All students depositing their thesis or dissertation must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>


</div>
