<div id="news">
  <h2>News and Announcements</h2>
   
<p><b>Submission Form for All ETD Program Participants </b><br>
 All students depositing their thesis or dissertation must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>

<p><b>The ETD System Software Has Been Updated.  New Instructions. </b><br/>
We have been working for a number of months on revamping the submission system for the
ETD Repository.  We would like to thank the pilot participants for their comments and suggestions.
<a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Instructions on how to use the new system are now available.</a>   Please contact the ETD staff at 
etd-admin@listserv.cc.emory.edu with any questions or comments about the new system.</p>

</div>