<style>
    p {margin-bottom: 0}
    ol {padding-top: 0; margin-top: 0; margin-left: -1.5em}
    ol li {padding-top: 0; margin-top: 0}
</style>
<p>The Electronic Theses and Dissertations (ETD) repository provides online 
    access to the University’s master’s theses, doctoral dissertations, and 
    undergraduate honors theses, increasing the visibility of our scholars 
    and fulfilling the University’s mission to contribute to academic 
    scholarship.</p>

<p>The ETD submission process involves three steps:
<ol>
    <li>Complete the pre-screening questionnaire</li>
    <li>Create and edit your ETD record</li>
    <li>Submit your thesis or dissertation</li>
</ol></p>

<p>The pre-screening questionnaire covers three broad questions pertaining to 
    copyright, patents, and access restrictions to your work. Please review 
    the ETD materials on the Copyright Education Initiative Blackboard 
    Organization before you proceed. For a more detailed overview of access 
    restrictions, please see the <a href="https://etd.library.emory.edu/docs/faq" target="_blank">ETD FAQ</a>. 
    If you are unsure whether you should choose an access restriction, speak 
    with your major advisor before proceeding.You must complete the entire 
    pre-screening questionnaire before you can begin creating your record.</p>

<p style ="text-align: center"><a href="<?= $this->url(array("controller" => "submission", "action" => "start"))?>" class="button">Next</a> </p>
