<? /* common view layout for contact information view and full record review */ ?>
<? $authorInfo = $this->authorInfo->mads; ?>
<div class="contact_info">
 <? if (isset($authorInfo->current)): ?>
 <h2>current</h2>
    <div class="indent">
      <? $this->affiliation = $authorInfo->current; ?>
      <?= $this->render("authorinfo/address.phtml"); ?>
      <? if ($authorInfo->current->phone): ?>
        <p><b>phone:</b> <?= $authorInfo->current->phone ?></p>
      <? endif ?>   
      <p><b>email:</b> <?= $authorInfo->current->email ?>
    </div>
<? endif ?>

<? if (isset($authorInfo->permanent)): ?>
  <h2>permanent</h2>
  <div class="indent">
    <? $this->affiliation = $authorInfo->permanent; ?>
    <?= $this->render("authorinfo/address.phtml"); ?>
    <? if ($authorInfo->permanent->phone): ?>
       <p><b>phone:</b> <?= $authorInfo->permanent->phone ?></p>
    <? endif ?>
   <p><b>email:</b> <?= $authorInfo->permanent->email ?></p> <? /* required field, so not checking if set */ ?>
  </div>
<? endif ?>
<p><b>netid:</b> <?= $authorInfo->netid ?></p>
</div>