	<script type="text/javascript"
		djConfig="isDebug: false, parseOnLoad: true"
		src="http://o.aolcdn.com/dojo/1.2.3/dojo/dojo.xd.js"></script>
	<script type="text/javascript">
	dojo.require("dojo.html");
	dojo.require("dijit._editor.RichText");
		//Put "onload" logic in here.
		dojo.addOnLoad(function(){
			var theme = 'tundra';
			if(!dojo.hasClass(dojo.body(),theme))
			{
			        dojo.addClass(dojo.body(),theme);
			}


<?php			//dojo.html.selectElement(dijit.byId('lastYearETDReport')); ?>
		});
	</script>
	<head>
	<style type="text/css">
        @import "http://o.aolcdn.com/dojo/1.2.3/dijit/themes/tundra/tundra.css";
        @import "http://o.aolcdn.com/dojo/1.2.3/dojo/resources/dojo.css";
	</style>
	</head>

<h1>Commencement Report </h1>

	<?php //Change this paragraph if the query changes ?>
    <p>
        Selected all records with degree <span style="font-weight:bold">PhD</span>
        published between <span style="font-weight:bold"><?=$this->startDate ?></span> and
        <span style="font-weight:bold"><?=$this->endDate ?></span> or not yet published and with status not
        <span style="font-weight:bold">inactive</span>.
    </p>


<?php //Based on browse/list.phtml ?>

<? if ($this->list_title): ?>
     <h1><?= $this->list_title ?></h1>
<? endif ?>
<? if ($this->list_description): ?><h2><?= $this->list_description ?></h2><? endif ?>
	
    <p>Displaying <?=  count($this->etdSet->etds); ?> result(s)</p>

 <textarea dojoType="dijit._editor.RichText" id="commencementETDReport">
<? foreach ($this->etdSet->etds as $etd): ?>
  <? $this->etd = $etd; ?>
  <?=  $this->render('report/shortrecord.phtml'); ?>
<? endforeach ?>
</textarea>
