<h1>Commencement Report Review</h1>

<p>
Please select records to <span style="font-weight:bold">exclude</span> from the report
</p>

<form name="commencement-review" action="commencement" method="post">
    <table cellpadding="0" cellspacing="0" align="center">
        <? foreach ($this->etdSet->etds as $etd): ?>
            <tr>
                <td class="separator"> <?=$this->formCheckbox('exclude[]', $etd->pid); ?> </td>
                <td class="separator">
                <div class="shrink">
                    <?=$etd->mods->author->full?>
                    <br />
                    <? foreach ($etd->mods->chair as $advisor): ?>
                    <div> <?=$etd->program()?>, <?=$advisor->full?>, Advisor </div>
                    <? endforeach ?>
                    <?=$etd->mods->genre?>:
                    <br />
                    <?=$etd->title()?>
                    <br />
                    <?//SUBMIT DATE GOES HERE ? ?>
                    Publication Date: <?=$etd->mods->originInfo->issued?>
                    </div>
                </td>
            </tr>
        <? endforeach ?>
        <tr>
        <td> <?= $this->formSubmit("submit", "Create Report >", Array("class" => "submitlink")); ?> </td>
        <td> </td>
        </tr>
</table>
</form>