<? /* recursive partial template to generate program selection list; expects these variables:
      collection - skosCollection for this level of the program tree
      level 	 - what level in the tree we are at
      [parent_id - parent id of current collection, needed for subfield; only set when recursing]
*/ ?>

<?
$id = $this->collection->id;
$label = $this->collection->label;
$hasMembers = (count($this->collection->members) != 0);
?>

<li id="<?= $id ?>">
<? if ($this->level ==  4 && isset($this->parent_id)): ?>
 <a onClick="setSubfield('<?= $id ?>', '<?= $this->parent_id ?>')"
    id="<?= $id ?>_label"><?= $label ?></a>   
<? elseif (! $hasMembers || $this->level ==  3): ?>
 <a onClick="setProgram('<?= $id ?>')" id="<?= $id ?>_label"><?= $label ?></a>
<? else: ?>
  <? if (isset($this->parent_id)): /* no toggle at top-level */ ?>
    <a class="toggle" onClick="Element.toggle('<?= $id ?>_list')">&gt;</a>
  <? endif ?>
  <span id="<?= $id ?>_label"><?= $label ?></span>
<? endif ?>       
<? if ($hasMembers): ?>
     <ul id="<?= $id ?>_list">
     <? foreach ($this->collection->members as $subcollection): ?>
	<?=  $this->partial('edit/_subprogram.phtml', array("collection" => $subcollection,
							    "level" => $this->level + 1,
							    "parent_id" => $id)); ?>
     <? endforeach ?>
     </ul>
<? endif ?>	  
</li>
