<? include "js/FCKeditor/fckeditor.php"; ?>

<h1>Edit <?= $this->template ?> Email Template</h1>


<form name="edit" method="post"
    action="<?= $this->url(array("action" => "edit", "template" => $this->template))?>">
<? /* configuration options for FCK editor */ 
$editor_opts = array("config" => (string)$this->linkTo("js/FCKconfig.js"),
		     "height" => "400", "toolbar" => "Default",
		     "TemplatesXmlPath" => (string)$this->linkTo("js/templates.xml"));
$editor_opts["css"] = $this->linkTo("css/etd.css");
if ($this->current_user->role == "superuser") $editor_opts["toolbar"] = "etd-admin";
?>

<?= $this->FckEditor("edit_content", (string)$this->edit_content, $editor_opts) ?>

<?= $this->formSubmit("Save", "Save", array("class" => "button")); ?>
<?= $this->formSubmit("preview", "Preview", array("class" => "button")); ?>
</form>

<? if ($this->preview): ?>
  <hr/>
  <p><b>Preview</b></p>
  <? if (isset($this->etd)): ?>
   <div class="email_template">
    <? /* TODO: need a render-text helper... ?  submit the form and use the output */ ?>
    <? $this->environment = "production"; ?> 
    <?= $this->renderString($this->preview_content) ?>
  </div>
 <? else: ?>
    <p>Please select a sample ETD to use for preview.</p>
 <? endif ?>
<? endif ?>