<h1><?= $this->title ?></h1>

<ul>
 <li><a href="<?= $this->url(array('action' => 'view', 'template' => 'submission')) ?>">submission</a> - 
  <a href="<?= $this->url(array('action' => 'edit', 'template' => 'submission')) ?>">edit</a>
</li>
 <li><a href="<?= $this->url(array('action' => 'view', 'template' => 'request_changes')) ?>">request changes</a></li>
 <li><a href="<?= $this->url(array('action' => 'view', 'template' => 'approval')) ?>">approval</a></li>
 <li><a href="<?= $this->url(array('action' => 'view', 'template' => 'publication')) ?>">publication</a></li>
 <li><a href="<?= $this->url(array('action' => 'view', 'template' => 'embargo_expiration')) ?>">embargo warning</a></li>
 <li><a href="<?= $this->url(array('action' => 'view', 'template' => 'embargo_end')) ?>">embargo end</a></li>
</ul>