<? if (isset($this->facets) && count($this->facets)): ?>
  <style type="text/css">div.content {padding-right:215px; }</style>
 <? /* FIXME.. better way to do this? (set margin for main div to leave room for faces) */ ?>

<? /* assumes view->facets is set with output from Solr */ ?>
<div class="facets">
     <? /* display filters currently in effect and allow them to be removed */ ?>
     <? if (isset($this->filters) && count($this->filters)): ?>
        <p><b>Remove filters:</b></p>
	<ul>
	  <? foreach ($this->filters as $facet => $term): ?>
	   <? /* build up url for this page _without_ this facet */ ?>
	   <? $url_opts = array('controller' => $this->controller, 'action' => $this->action);
		foreach ($this->filters as $f => $t) if ($f != $facet) $url_opts[$f] = $t; ?>
	    <li><a href="<?= $this->url($url_opts, '', true) ?>"><?= $term ?></a></li>
          <? endforeach ?>
	</ul>
        <hr/> 
    <? endif ?>
   
   <b>Filter your results:</b>
   
	    <? foreach (array("status", "chair", "year", "subject", "committee", "program", "author", "keyword") as $facet): ?>
     <? if ($this->browse_mode == "committee" && $facet == "chair") continue; ?>
     <? if (isset($this->facets->$facet) && count($this->facets->$facet)
	    && !isset($this->filters[$facet]) && $this->browse_mode != $facet): ?>
   <p class="label"><?= ucfirst($facet) ?></p>
	  <ul>
  	    <? foreach ($this->facets->$facet as $label => $count): ?>
  	      <li>
  	        <a href="<?= $this->url(array($facet => $label)) ?>"><?= $label ?></a>
	       (<?= $count ?>)</li>
 	    <? endforeach ?>
	  </ul>
       <? endif ?>
    <? endforeach ?>
  
</div>
<? endif ?>