<p class="browse_heading">
   <?=  $this->render('browse/_collection_breadcrumb.phtml'); ?>
</p>

  
    <? if ($this->coll != '') $linkmode = "subcoll"; else $linkmode = "coll"; ?>
<? foreach ($this->collection->members as $member): ?>
   <? $link_id = str_replace("#", '', $member->id);?>

  <p><a href="<?= $this->url(array('coll' => $link_id)) ?>"><?= $member->label ?></a>
   <?/* category totals: display if non-zero */?>
  <? if (isset($this->program_totals[$member->label]) && $this->program_totals[$member->label]): ?>
     (<?= $this->program_totals[$member->label]?>)
  <? endif ?>
   </p>
<? endforeach ?>

<? /* don't show etd records at top level */ ?>
<? if ($this->collection->label != "Programs"): ?>
  <?=  $this->render('browse/_facets.phtml'); ?>
  <?=  $this->render('browse/list.phtml'); ?>
<? endif ?>  