<form name="search" method="post" action="<?= $this->url(array("action" => "results"))?>">
<table>
  <tr><th>anywhere</th> <td><?= $this->formText("query", ""); ?></td></tr>
  <tr><th>Title</th> <td><?= $this->formText("title", ""); ?></td></tr>
  <tr><th>Author</th> <td><?= $this->formText("author", ""); ?></td></tr>
  <tr><th>Committee Member</th> <td><?= $this->formText("committee", ""); ?></td></tr>
  <tr><th>Abstract</th> <td><?= $this->formText("abstract", ""); ?></td></tr>
  <tr><th>Table of Contents</th> <td><?= $this->formText("toc", ""); ?></td></tr>
  <tr><th>Keywords</th> <td><?= $this->formText("keyword", ""); ?></td></tr>
  <tr><th>Research Field</th> <td><?= $this->formText("subject", ""); ?></td></tr>
  <tr><th>Program</th> <td><?= $this->formText("program", ""); ?> </td></tr>
</table>
   <?= $this->formSubmit("Search", "Search"); ?>
</form>