<? if ($this->list_title): ?>
     <h1><?= $this->list_title ?></h1>
<? endif ?>
<? if ($this->list_description): ?><h2><?= $this->list_description ?></h2><? endif ?>
	
<?=  $this->render('browse/_facets.phtml'); ?>
<?=  $this->render('browse/_paging.phtml'); ?>	       
	
<? foreach ($this->etdSet->etds as $etd): ?>
  <? $this->etd = $etd; ?>
  <?=  $this->render('view/shortrecord.phtml'); ?>
<? endforeach ?>
