<?/* FIXME: lots of duplication with submission/review */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user);  ?>
<style type="text/css">
   p.note, #submission_status, #history {display:none; }
</style>
<?=  $this->render('view/fullrecord.phtml'); ?>
<?=  $this->render('submission/_reviewinfo.phtml'); ?>
</hr>


<p style="text-align:center">
    <a class="button" href="<?= $this->url(array('action' => 'accept')) ?>">Accept &gt;</a>
    <a class="button" href="<?= $this->url(array('action' => 'requestchanges',
		'type' => 'record')) ?>">Request Changes &gt;</a>
</p>
