<div id="calendar">
<h2>Calendar</h2>

<p><b>February 6, 2009:</b> Degree Applications Due for May Graduation</p>

<p><b>February 24, 26, March 3 and 17 2009:</b> Copyright Workshops</p>

<p><b>February 26, March 4 and 16 2009:</b> Introduction to ETD program</p>

<p><b>April 3, 2009:</b> Theses/Dissertations Due at Graduate School for May Graduation</p>

<p><b>May 11, 2009:</b> Commencement</p>

<p><b>July 2, 2009:</b> Degree Applications Due for August Graduation</p>

<p><b>July 31, 2009:</b> Theses/Dissertations Due for August Graduation</p>
</div>
