<div id="calendar">
<h2>Calendar</h2>

<p>
    <b>Introduction to ETD:</b><br/>
    <ul>
        <li>October 21st in Woodruff Library 310</li>
        <li>October 27th in Woodruff Library 310</li>
    </ul>

</p>

<p>
    <b>ETD Submission Workshop:</b>
    <ul>
        <li>November 9th in Woodruff Library 310 3:00 PM - 4:00 PM</li>
        <li>November 11th in GCRP45 (Rollins) noon - 1 PM</li>
        <li>November 15th in Woodruff Library 310 3:00 PM - 4:00 PM</li>
        <li>November 17th in Woodruff Library 310 3:00 PM - 4:00 PM</li>
    </ul>
</p>

<p><b>November 19th</b> Laney Submission Deadline</p>
<p><b>December 2nd</b> College Honors Submission Deadline</p>
<p><b>December 3rd</b> Rollins Submission Deadline</p>
<p><b>December 6th</b> Candler Submission Deadline</p>
</div> 

