<h1>Edit Program/Department</h1>
<p><b><?= $this->etd->title() ?></b></p>
<p>Your Emory record indicates that you are currently enrolled in the
following
<? if ($this->honors): ?> Undergraduate Honors Program<? else: ?>  Graduate Program<? endif ?>.</p>

<p>If this information is incorrect, re-enter your program below.  Begin typing
the name of your program and select from the supplied list.
If your program has an applicable subfield, please select that as well.</p> 

<form action="<?= $this->url(array("action" => "save-program")) ?>" method="post">
			    
<div>
<b>Department/Graduate Program *</b><br/>
  <input id="program" name="program" autocomplete="off" size="60" type="text"
			    value="<?= $this->etd->mods->department ?>"/>
  <span id="prog_success" class="success" style="display:none">Success: valid program id</span>
  <input id="program_id" name="program_id" type="hidden"
			    value="<?= $this->etd->rels_ext->program ?>"/>
  <div class="autocomplete" id="program_list" style="display:none"> </div>
</div>
<div id="subfield_form"
<? if (!isset($this->etd->rels_ext->subfield) || $this->etd->rels_ext->subfield == ''): ?>
   style="display:none" <? endif ?> >
 <b>Subfield</b><br/>
  <select id="subfield_id" name="subfield_id">
  </select>
</div>

<p><input class="button" type="submit" value="save"/></p>
</form>

<? // build an array of program id and name and an array of subfield
   // id and name by program id  (for use in javascript)
$program_names = array();
$subfields = array();
foreach ($this->prog_section->members as $division) {
  if (count($division->members)) {
    foreach ($division->members as $program) {
      $program_names[$program->getId()] = $program->label;
      if (count($program->members)) {	// this program has subfields
	$prog_id = $program->getId();
	$subfields[$prog_id] = array();
	foreach ($program->members as $subfield) {
	  $subfields[$prog_id][$subfield->getId()] = $subfield->label;
	}  // subfield loop
      }  // program with subfield
    }  // program loop
  }
}  ?>

<?= $this->javascript("projax/js/scriptaculous.js"); ?>
<?= $this->javascript("projax/js/effects.js"); ?>
<?= $this->javascript("projax/js/prototypeUtils.js"); ?>
<script language="JavaScript">
  var program_names = <?= json_encode(array_values($program_names)) ?>;
  var programs_by_id = <?= json_encode($program_names) ?>;
  var subfields = <?= json_encode($subfields) ?>;
<? if (isset($this->etd->rels_ext->subfield)): ?>
   var init_subfield = '<?= $this->etd->rels_ext->subfield ?>';
<? endif ?>     
new Autocompleter.Local('program', 'program_list', program_names, {
    partialSearch: true,
    afterUpdateElement: afterSelect
			    });

function afterSelect() {
  // find and set id in hidden field
  var prog_name = $F('program');

  // find program id
  var prog_id = '';
  for (var i in programs_by_id) {
    if (programs_by_id[i] == prog_name) {
      prog_id = i;
    }
  }
  // store program id in hidden input (if no match is found, blanks it out)
  Form.Element.setValue("program_id", prog_id);
  if (prog_id != "") {
    $('prog_success').show();
    Effect.Fade('prog_success', { duration: 3.0 });
  }

  // check if this program has subfields
  var has_subfield = false;
  for (var prog in subfields) {
    if (prog == prog_id) {
      has_subfield = true;
      // populate subfield select box with program's subfields
      $('subfield_id').options.length=0;
      var count = 0;
      $('subfield_id').options[count] = new Option("", "");	// add blank (optional)
      for (var id in subfields[prog]) {
	count++;
	var selected = (init_subfield && (init_subfield == id));
	$('subfield_id').options[count] = new Option(subfields[prog][id], id, false, selected);
      }
    }
  }
  // show or  hide the subfield section of the form as appropriate
  if (has_subfield) {
    $("subfield_form").show();
  } else {
    $('subfield_id').options.length=0;		// unset any value
    $("subfield_form").hide();
  }

  // blank out initial subfield
  init_subfield = null;
}

<?  /* if program already set, populate any subfield select and pre-set it correctly */
if ($this->etd->rels_ext->program != "" || $this->etd->mods->department != ""): ?>
     afterSelect();
<? endif ?>
</script>
