<? $current_field = $this->field; ?>
<?/*
<li><a id="<?= $current_field->id ?>" onclick="new Insertion.Bottom('user_fields', '<li><?= $current_field->label ?></li>');
Element.addClassName('<?= $current_field->id ?>','selected');
return false;"><?= $current_field->label ?></a>
*/?>

<li><a id="<?= $current_field->id ?>" onclick="javascript:toggle_selection('<?= $current_field->id ?>', '<?= $current_field->label ?>');return false;"><?= $current_field->label ?></a>
  <? if (count($current_field->members)): ?>
     <ul>
     <? foreach ($this->field->members as $member): ?>
	<? $this->field = $member; ?>
        <?=  $this->render('edit/_researchfield.phtml'); /* recurse again */  ?>
     <? endforeach ?>
    </ul>
   <? endif ?>
</li>

