<xf:instance id="tmp" xmlns="">
   <tmp>
     <copyright><?= $this->etd->mods->copyright ?></copyright>
     <embargo><?= $this->etd->mods->embargo_request ?></embargo>
    <agreement><?= $this->etd->mods->hasSubmissionAgreement() ? "yes" : "" ?></agreement>
     <rights id="yes"><?= $this->rights_stmt ?></rights>
     <rights id="no"/>
     <ask_pq_submit/>
     <ask_copyright/>
   </tmp>
</xf:instance>

<?/* use yes/no temporary settings for copyright, embargo, and submission agreement;
    once they are set, calculate or set the real fields based on  them
   */ ?>
<? if ($this->etd->isRequired("embargo request")): ?>
  <xf:bind nodeset="instance('tmp')/embargo" required="true()" />
<? endif ?> 
<? if ($this->etd->isRequired("submission agreement")): ?>
   <xf:bind nodeset="instance('tmp')/agreement" required="true()"/>
<? endif ?>
<? if ($this->etd->isRequired("copyright")): ?>
   <xf:bind nodeset="instance('tmp')/copyright" required="true()"/>
<? endif ?>

   
<xf:bind nodeset="mods:note[@ID='embargo']" type="xsd:string" calculate="concat('embargo requested? ', instance('tmp')/embargo)"/>
<xf:bind nodeset="mods:note[@ID='copyright']" type="xsd:string" calculate="concat('registering copyright? ', instance('tmp')/copyright)"/> 

<? /* submit to PQ optional for masters */ ?>
<xf:bind id="pq_submit" nodeset="instance('tmp')/ask_pq_submit" relevant="instance('main')/mods:extension/etd:degree/etd:name = 'MA' or instance('main')/mods:extension/etd:degree/etd:name = 'MS'"/>
      
<? /* if degree is PhD, will submit to PQ - no need to prompt */ ?>
<? if ($this->etd->isRequired("send to ProQuest")): ?>
  <xf:bind nodeset="mods:note[@ID='pq_submit']" type="xsd:string" required="true()"/>
<? endif ?>

<? /* only ask about copyright if record will be sent to proquest  */ ?>
<xf:bind id="ask_copyright" nodeset="instance('tmp')/ask_copyright"
	 relevant="instance('main')/mods:note[@ID='pq_submit'] = 'yes'"/>  
<xf:submission id="submission" 
	       action="<?= $this->url(array('action' => 'savemods',
		       'id' => $this->pid, "component" => "copyright, embargo, and access rights"))?>"
	       method="post" />

<xf:message level="modal"
   ev:event="xforms-submit-error">Error: check that all required fields are filled in correctly</xf:message>
