<? include "js/FCKeditor/fckeditor.php"; ?>

<h1>Edit <?= $this->mode_label ?></h1>
<p><b><?= $this->etd->title() ?></b></p>


<form name="edit" method="post"
    action="<?= $this->url(array("action" => "save" . ucfirst($this->mode), "mode" => $this->mode))?>">

<?php
$oFCKeditor = new FCKeditor("edit_content");
$oFCKeditor->BasePath = (string)$this->linkTo("js/FCKeditor/");
$oFCKeditor->Value = (string)$this->edit_content;

$oFCKeditor->Config["CustomConfigurationsPath"] = (string)$this->linkTo("js/FCKconfig.js");
$oFCKeditor->ToolbarSet = 'Basic';
if ($this->mode == "title") {
  $oFCKeditor->Height = '200';
  $oFCKeditor->ToolbarSet = "etd-title";
} else {
  $oFCKeditor->Height = '400';
  $oFCKeditor->ToolbarSet = "etd";
}
$oFCKeditor->Create();
?>

  <?= $this->formSubmit("Save", "Save"); ?>
</form>
