<?= $this->javascript("util.js"); ?>
<? include "js/FCKeditor/fckeditor.php"; ?>

<h1>Edit <?= $this->mode_label ?></h1>
<p><b><?= $this->etd->title() ?></b></p>

<p>The system may have trouble with special and foreign language characters 
    and with characters imported using cut-and-paste.  We recommend using the 
    following tools:</p>

<ul>
    <li>Use the paste from Word tool <?= $this->img("images/fck_pasteword.gif") ?>
        to copy from Microsoft Word.</li>
    <li>Use the paste as plain text tool <?= $this->img("images/fck_pastetext.gif") ?> 
        to copy special characters.</li>
    <li>Use the special character <?= $this->img("images/fck_specialchar.gif") ?> 
        or universal keyboard <?= $this->img("images/fck_keyboard.gif") ?> 
        tool for special
        and foreign language characters.</li>
</ul>

<form name="edit" method="post" onsubmit="disableButton('Save')"
    action="<?= $this->url(array("action" => "save" . ucfirst($this->mode), "mode" => $this->mode))?>">
<? /* configuration options for FCK editor */ 
$editor_opts = array("config" => (string)$this->linkTo("js/FCKconfig.js"),
			    "height" => "400", "toolbar" => "etd" );
if ( $this->mode == "title") {
  $editor_opts["toolbar"] = "etd-title";
  $editor_opts["height"] = "etd-title";
} elseif ($this->mode == "abstract") {
  $editor_opts["BodyId"] = "abstract";
}

$editor_opts["css"] = $this->linkTo("css/etd.css");
if ($this->current_user->role == "superuser" || $this->current_user->role == "techsupport") $editor_opts["toolbar"] = "etd-admin";
?>

<?= $this->FckEditor("edit_content", (string)$this->edit_content, $editor_opts) ?>

<?= $this->formSubmit("Save", "Save", array("class" => "button")); ?>
</form>
