<h1>edit thesis information</h1>

<? /* fixme: figure out some way to hide this until form is loaded */ ?>
<?= $this->xformOutput("Title", "mods:titleInfo/mods:title"); ?><br/>

<? /* FIXME: should author name be editable ? */ ?> 
 <xf:group ref="mods:name[mods:role/mods:roleTerm='author']">
    <xf:label>author</xf:label>
    <?=  $this->render('edit/_mods_name.phtml'); ?>
    <?/* note: department now edited on separate page */ ?>
 </xf:group>
 <br/>
 <? /* note: advisor & committee members are edited on a separate form */ ?>
 <? /* note: title, abstract, & table of contents are edited on a separate form */ ?>

  <xf:select1 ref="mods:language/mods:languageTerm[@type='text']">
   <xf:label>language</xf:label>
   <xf:itemset nodeset="instance('languages')/language">
     <xf:label ref="@display"/><xf:value ref="@text"/>
   </xf:itemset>
  </xf:select1>
 <br/>

 <?/*  umi/proquest research fields edited separately */ ?>

  <p><u>keywords</u></p>
  <xf:repeat id="repeat-keywords" nodeset="mods:subject[@authority='keyword']">
   <?= $this->xformText("", "mods:topic"); ?>
   <br/>
  </xf:repeat>

  <xf:trigger>
      <xf:label>Add another keyword</xf:label>
      <xf:action ev:event="DOMActivate">
        <xf:insert nodeset="mods:subject[@authority='keyword']" at="last()" position="after"/>
        <xf:setvalue ref="mods:subject[@authority='keyword']/mods:topic[last()]" value="''"/>
       </xf:action>
     </xf:trigger>
      
    <xf:trigger>
      <xf:label>Remove last keyword</xf:label>
      <xf:delete ev:event="DOMActivate" nodeset="mods:subject[@authority='keyword']" at="last()"/>
    </xf:trigger>
<br/>

  <xf:select1 ref="mods:extension/etd:degree/etd:name">
   <xf:label>degree</xf:label>
   <xf:itemset nodeset="instance('degrees')/level/degree">
     <xf:label ref="@name"/><xf:value ref="@name"/>
   </xf:itemset>
  </xf:select1>

  <?= $this->xformText("degree level", "mods:extension/etd:degree/etd:level"); ?>
  <?= $this->xformText("thesis type", "mods:genre"); ?>
  <br/>

  <xf:submit submission="submission">
<xf:label>Save</xf:label>
</xf:submit>

<? if ($this->site_mode == 'development'): ?>
  <p id="status"></p>
<? endif ?>   

