<?= $this->javascript("projax/js/prototype.js"); ?>
<?= $this->javascript("projax/js/scriptaculous.js"); ?>
<? //php ajax/scriptaculous
include("projax/projax.php");
$projax = new Projax(); ?>

<? $blank = ($this->etd->mods->researchfields[0]->id == ""); ?>     
<script type="text/javascript">
var field_count = <?= $blank ? 0 : count($this->etd->mods->researchfields); ?>;
var field_max = 3;
     function toggle_selection(id, text) {
      if (Element.hasClassName(id, 'selected')) {
	// unselect & remove from list
	field_count--;
	Element.removeClassName(id, 'selected');
	Element.remove(id + '_list');
	updatePrimary(id);
      } else if (field_count < field_max) {
	field_count++;
	// select & add to list
	if (field_count == 1) { var label = " <i id='primary_field'>(primary field)</i>"; }
	else { var label = ""; }
	new Insertion.Bottom('user_fields', '<li id="' + id + '_list">' + text + label +
			     '<input id="' + id + '_input" type="hidden" name="fields[]" value="'
			     + id + ' ' + text + '"/>' + '</li>');
	Element.addClassName(id, 'selected');
      } else {
	// alert user, don't select
	alert("You may choose a maximum of " + field_max + " fields. Save your choices or reselect.");
      }
      Sortable.create("user_fields", {onChange:updatePrimary});
}
function updatePrimary(listitem) {
  var label =   document.getElementById('primary_field');
  if (label != null)  Element.remove('primary_field');
  var list = document.getElementById("user_fields");
  if (list.firstChild)
    new Insertion.Bottom(list.firstChild, '<i id="primary_field"> (primary field)</i>');  
}
</script>     

<p><b>Edit Research Fields</b></p>

<form method="post" id="fields_form"  action="<?= $this->url(array("action" => "saveResearchfield"))?>">
  <ul id="user_fields">
  <? if ($this->etd->mods->researchfields[0]->id != ""): ?>
   <? foreach ($this->etd->mods->researchfields as $field): ?>
     <li id="#<?= $field->id ?>_list"><?= $field->topic ?>
       <input type="hidden" name="fields[]"
       value="#<?= $field->id ?> <?= $field->topic ?>"/>
	<? if ($field->id == $this->etd->mods->researchfields[0]->id): ?>
	  <i id="primary_field">(primary field)</i>
	<? endif ?>
     </li>
    <? endforeach ?>
  <? endif ?>	
  </ul>
	<?= $projax->sortable_element("user_fields",
     		      array("url" => null, "onChange" => "updatePrimary")); ?>     

   <input id="save_button" type="submit" value="save"/>
</form>
<br/>


<p><b>UMI ProQuest Research Fields</b></p>
<div id="select_researchfields">
<? foreach ($this->fields->members as $this->field): ?>
  <?=  $this->render('edit/_researchfield.phtml'); /* recursive */ ?>
<? endforeach ?>
</div>
