<div class="fullrecord">
  <div id="access">
   <h2>Access Restrictions</h2>
      <? if ($this->acl->isAllowed($this->role, $this->etd, "edit metadata")): ?>
	<a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "rights")) ?>">edit access restrictions</a>
      <? endif ?>

	   Access restrictions requested?
	   <? if ($this->etd->mods->isEmbargoRequested()): ?>
	      <b>yes:
<? $restricted = array();	// nicer view of what exactly will be restricted
if ($this->etd->mods->isEmbargoRequested(etd_mods::EMBARGO_FILES)) $restricted[] = "files";
if ($this->etd->mods->isEmbargoRequested(etd_mods::EMBARGO_TOC)) $restricted[] = "table of contents";
if ($this->etd->mods->isEmbargoRequested(etd_mods::EMBARGO_ABSTRACT)) $restricted[] = "abstract"; ?>
		<?= implode(", ", $restricted); ?>
		 </b>
	   <? else: ?>
	      <b>no: </b>
	   <? endif ?>
  </div>

 <? if ($this->etd->isRequired("send to ProQuest")): ?>	   
  <div id="proquest">
   <h2>ProQuest Submission Information</h2>
    <? if ($this->acl->isAllowed($this->role, $this->etd, "edit metadata")): ?>
      <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "rights")) ?>">edit copyright</a>
    <? endif ?>

   <p>Sending to ProQuest? <b><?= $this->etd->mods->submitToProquest() ? "yes" : "no"; ?></b></p>
   <p>Applying for copyright? <b><?= $this->etd->mods->copyright ?></b></p>
  </div>
<? endif ?>
     
  <div id="contact">
    <h2>Contact information</h2>
   <? if ($this->acl->isAllowed($this->role, "authorInfo", "edit")): ?>
      <a class="action" href="<?= $this->url(array("controller" => "authorInfo", "action" => "edit",
		"pid" => $this->etd->authorInfo->pid), '', true) ?>">edit contact information</a>
    <? endif ?>
    <? $this->user = $this->etd->authorInfo; ?>
    <?=  $this->render('author-info/_view.phtml'); ?>

  </div>
</div>
