<?= $this->javascript("projax/js/prototype.js"); ?>
<?
 $etd = $this->etd;
// get required & optional fields, and which are missing
 $required_fields = $etd->requiredFields();
 $required_missing = $etd->checkRequired();
 $optional_fields = $etd->optionalFields();
 $optional_missing = $etd->checkOptional();
// display variables
 $ok = "<span class='ok'>&#x2714;</span>"; // green check mark 
 $incomplete = "<span class='incomplete'>&#x2717;</span>"; // red x
?>
<h2>submission status</h2>
<? if (isset($etd->authorInfo)): ?>
   <? $authorInfo_url = $this->url(array("controller" => "authorinfo", "action" => "view",
					 "pid" => $etd->authorInfo->pid), '', true, false); ?>
   <? if ($etd->readyToSubmit("authorInfo")): ?>
      <?= $ok ?> <a href="<?= $authorInfo_url ?>">contact information</a><br/>
   <? else: ?>
      <?= $incomplete ?> <a href="<?= $authorInfo_url ?>">contact information</a><br/>
        <ul id="user_missing" class="missing">
	    <? /* list any missing fields (required or optional) provided by author info */ ?>
	    <? foreach (array_intersect(array_merge($required_fields, $optional_fields),
					$etd->authorInfo->available_fields) as $missing): ?>
             <li><?= $missing ?></li>
          <? endforeach ?>
        </ul>
   <? endif ?>
 <? else: /* no author info - link to create new record */ ?>
    <?= $incomplete ?> <a href="<?= $this->url(array('controller' => 'authorinfo', 'action' => 'new',
			'etd' => $etd->pid), '', true, false) ?> ">contact information</a><br/>
 <? endif ?>

<? // thesis metadata is displayed in two sections
 $rights_fields = array("send to ProQuest", "copyright", "embargo request", "submission agreement");
 // 'thesis' fields - any non-rights fields in mods
 $thesis_fields = array_diff($etd->mods->available_fields, $rights_fields);
 $missing_thesis_fields = array_intersect($required_missing, $thesis_fields);
 $optional_thesis_fields = array_intersect($optional_missing, $thesis_fields);
?>
<? if ($readyToSubmit = $etd->readyToSubmit("mods") ||
       count($missing_thesis_fields) == 0): ?>
     <? /* mods ready to submit OR no required thesis fields are missing */ ?>
    <?= $ok ?> thesis information<br/>
    <? /* special case - should NOT happen unless something is wrong */ ?>
    <? if (!$readyToSubmit):  /* not ready to submit but no missing fields = xml is invalid */ ?>
      <ul id="mods_missing" class="missing">
	<li>XML invalid; please contact ETD Administrator</li>
      </ul>
    <? endif ?>
  <? else: ?> 
   <?= $incomplete; ?> thesis information
     <? /* display which required fields are missing, if any */   ?>
     <ul id="mods_missing" class="missing">
         <? foreach ($missing_thesis_fields as $missing): ?>
           <li><a href="<?= $this->editFieldLink($missing) ?>">
	       <?= $etd->mods->fieldLabel($missing) ?></a>
           </li>
         <? endforeach ?>
     </ul>
  <? endif /* end mods ready to submit */ ?>
  <? if (count($optional_thesis_fields)): ?>
     <ul id="mods_optional" class="missing">
	<? foreach ($optional_thesis_fields as $field): ?>
	<li><a href="<?= $this->editFieldLink($field) ?>">
	  <?= $etd->mods->fieldLabel($field) ?></a></li>
	<? endforeach ?>
     </ul>
  <? endif ?>

  <?= $etd->hasPDF() ? $ok : $incomplete ?> PDF file<br/>
  <?if ($etd->hasOriginal()) : ?>
   <?= $ok ?> original file
  <? else : ?>
    <?= $incomplete ?> <a href="<?= $this->url(array('controller' => 'file', 'action' => 'add',
			'etd' => $etd->pid), '', true, false)?>">original file</a>
  <? endif ?> <br/>

  <?/*** rights details - display choices selected ***/ ?>
  <? if ($etd->isRequired("send to ProQuest") && 
	 ($etd->mods->degree->name != "PhD" && $etd->mods->degree->name != "")): ?>
      <? /* (PQ submission is not optional for PhDs-- field is required but auto-set to true) */ ?>
      <? $pq_submit = $etd->mods->hasSubmitToProquest() ?>
      <?= $pq_submit ? $ok : $incomplete; ?> <a href="<?= $this->editFieldLink('send to ProQuest') ?>">send to ProQuest</a>
      <?= $pq_submit ? ": <b>" . $etd->mods->pq_submit . "</b>" : "";	/* display choice if set */ ?>
      <br/>
  <? endif ?>

  <? /* if not submitting to PQ and copyright is set, suppress (redundant) */ ?>
  <? $copyright = $etd->mods->hasCopyright(); ?>
  <? if ($etd->mods->submitToProquest() && $copyright): ?>
    <?= $copyright ? $ok : $incomplete; ?> <a href="<?= $this->editFieldLink('copyright') ?>">copyright</a>
    <?= $copyright ? ": <b>" . $etd->mods->copyright . "</b>" : "";	/* display choice if set */ ?>
    <br/>
  <?endif ?>
  
  <? $embargo = $etd->mods->hasEmbargoRequest(); ?>
  <?= $embargo ? $ok : $incomplete; ?> <a href="<?= $this->editFieldLink('embargo request') ?>">embargo request</a>
  <?= $embargo ? ": <b>" . $etd->mods->embargo_request . "</b>" : "" ?>
   <br/>
  <?= $etd->mods->hasSubmissionAgreement() ? $ok : $incomplete; ?>
     <a href="<?= $this->editFieldLink('submission agreement') ?>">submission agreement</a><br/>
	
   <? if ($this->acl->isAllowed($this->role, $this->etd, "submit")
	  && $etd->readyToSubmit()): ?>
	   <p><a class="button" href="<?= $this->url(array('controller' => 'submission',
				'action' => 'review')) ?>">review &amp; submit &gt;</a></p>
  <? endif ?>								     

</p>
