<?/* FIXME: lots of duplication with submission/review */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user);  ?>
<style type="text/css">
   p.note, #submission_status, #history {display:none; }
</style>
<?=  $this->render('view/fullrecord.phtml'); ?>

<div class="fullrecord">
  <div id="access">
   <h2>Access Restrictions</h2>
   Access restrictions requested? <b><?= $this->etd->mods->embargo_request ?></b>
  </div>

  <div id="proquest">
   <h2>ProQuest Submission Information</h2>
   Applying for copyright? <b><?= $this->etd->mods->copyright ?></b>
  </div>

  <div id="contact">
    <h2>Contact information</h2>
 <? /* fixme: need a shorter version of this; split out user view into partials? */ ?>
   <?//=  $this->render('user/view.phtml'); ?>

   <? $user =  $this->user->mads; ?>
   
   <? if (isset($user->current)): ?>
 <p><u>current contact information:</u></p>
    <p><b>current address</b> (valid as of <?= $user->current->date ?>)</p>
    <? $this->address = $user->current->address; ?>
    <?= $this->render("user/address.phtml"); ?>

    <p><b>current phone:</b> <?= $user->current->phone ?></p>
<p><b>current email:</b> <?= $user->current->email ?>
<? endif ?>

<? if (isset($user->permanent)): ?>
  <p><b>permanent:</b></p>
  <p><b>address</b> (valid as of <?= $user->permanent->date ?>)</p>
  <? $this->address = $user->permanent->address; ?>
  <?= $this->render("user/address.phtml"); ?>
<p><b>phone:</b> <?= $user->permanent->phone ?></p>
<p><b>email:</b> <?= $user->permanent->email ?></p>
<? endif ?>

  </div>
</div>

</hr>


<p><b><a href="<?= $this->url(array('action' => 'accept')) ?>">Accept</a></b></p>

<p><b><a href="<?= $this->url(array('action' => 'requestchanges')) ?>">Request Changes</a></b></p>
