<? /* generate link navigation for paging through sets of results */ ?>

<? if (isset($this->etdSet)): ?>

  <? if ($this->etdSet->hasMoreResults()): ?>
  <ul style="float:right" class="horizontal">
      <li class="first">More results:</li>
       <? foreach ($this->etdSet->resultSets() as $start => $end): ?>
       <li <? if ($start == 1): ?>class="first" <? endif ?> >
       <? $range =  $start . ( $start != $end ? " - " . $end : "") ?>
        <? if ($start - 1 != $this->etdSet->start): ?>
          <a href="<?= $this->url(array('start' => $start - 1, 'max' => $this->etdSet->rows)) ?>">
	     <?= $range ?></a>
        <? else: ?> <?= $range ?>
	<? endif ?>
       </li>
       <? endforeach ?>
     </ul>
   <? endif ?>	     

<div class="pagination">	     
 <p><?= $this->etdSet->numFound ?> match<? if ($this->etdSet->numFound != 1): ?>es<? endif ?>
   found<? if ($this->etdSet->numFound > 1): ?>; displaying <?= $this->etdSet->currentRange() ?><? endif ?>
 </p>

 <? if (isset($this->sort) && $this->etdSet->numFound > 1): ?>
  <p>Sort by:
  <? foreach ($this->sort_fields as $sortfield): ?>
     <? if ($sortfield == $this->sort): ?>
       <b><?= $this->sort_display[$sortfield] ?></b>
     <? else: ?>
       <a href="<?= $this->url(array_merge($this->url_params, array('sort' => $sortfield))) ?>"><?= $this->sort_display[$sortfield] ?></a>
     <? endif ?>
     <? if ($sortfield != $this->sort_fields[count($this->sort_fields) - 1]): ?>|<? endif ?>
  <? endforeach ?>
  </p>
 <? endif ?>       			   
</div>
	  
<? endif ?>
