<? /* summary ETD information - displayed in both full and short record views */ ?>

<?= $this->etd->mods->author->full ?> 
   (<?= $this->etd->mods->genre ?>)<br/>

  <b>Advisor:</b> <?= $this->etd->mods->advisor->full ?><br/>
  <b>Committee members:</b> 
    <? foreach ($this->etd->mods->committee as $cm): ?>
	 <?= $cm->full ?>;
    <? endforeach ?>
    <? foreach ($this->etd->mods->nonemory_committee as $cm): ?>
         <?= $cm->full ?> (<?= $cm->affiliation ?>);
    <? endforeach ?>
    <br/>
  <b>Research Fields:</b> 
    <? for ($i = 0; $i < count($this->etd->mods->researchfields); $i++): ?>
	 <?= $this->etd->mods->researchfields[$i] ?>;
    <? endfor ?><br/>
  <b>Keywords:</b> 
    <? for ($i = 0; $i < count($this->etd->mods->keywords); $i++): ?>
       <?= $this->etd->mods->keywords[$i] ?>;
   <? endfor ?><br/>
  <b>Program:</b> <?= $this->etd->mods->department ?><br/>
