<? if ($this->show_status || $this->show_lastaction) : ?>
  <div class="record_status">
   <? if ($this->show_status): ?> 
     Current status: <b><?= $this->etd->status() ?></b><br/>
   <? endif ?>
   <? if ($this->show_lastaction): ?>
     <? /* catch exception when  Fedora permissions don't match site permissions */ ?>
     <? try { ?>
       <? $last_event = $this->etd->premis->event[count($this->etd->premis->event) - 1]; ?>
       Last action: <?= $last_event->detail ?>
       (<?= date(DATE_RFC850, strtotime($last_event->date, 0))?>)<br/>
     <? } catch (FedoraAccessDenied $e) { ?>
       <p><b>Warning: </b> Access denied to view record history</b></p>
     <? } ?>
   <? endif ?>
  </div>
<? endif ?>      
