<? $address = $this->affiliation->address;
if ($address->street[0] != "" || $address->city != "" || $address->postcode != "")  $hasAddress = true;
 else $hasAddress = false;	?>
<? if ($hasAddress): ?>
     <p><b>address</b>
     <? if ($this->affiliation->date): ?> (valid as of <?= $this->affiliation->date ?>)<? endif ?>
   <br/>

  <? foreach ($address->street as $st): ?>
    <?= $st ?><br/>
  <? endforeach ?>
  <? if ($address->city != "") : ?><?= $address->city ?>, <? endif ?>
  <? if ($address->state) : ?><?= $address->state ?>, <? endif ?>
  <? if ($address->postcode) : ?><?= $address->postcode ?>; <? endif ?>
  <?= $address->country ?> 
  </p>
<? endif ?>  

