<?/* short record view  for an ETD (list/browse)
     expects $view->etd to be set with record to display.  */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user); ?>

<div class="listrecord">
    <div class="record_label"></div>
     <div class="record_author"> <?= $this->etd->author() ?><?= $this->etd->semester ?></div>
	<? foreach ($this->etd->chair() as $advisor): ?>
		<div class="record_label"></div><div class="record_advisor"><?= $this->etd->program() ?>, <?= $advisor ?>, Adviser</div>
	<? endforeach ?>
    <div class="record_label">Dissertation: </div><div class="record_title"><?= $this->etd->title() ?></div>
    <hr><br/>
</div>
