<h1>About the web service:</h1>

<p>Indexdata is a php web service that provides solr index configuration and data to 
<a target=_blank href="https://github.com/emory-libraries/eulindexer">eulindexer</a> 
that will deposit data into a SOLR index.</p>
<p></p>
<p>Required parameters are:</p>
<ul>
  <li><i>/services/indexdata</i> - full index of all ETD objects that have a content model: "emory-control:ETD-1.0".<br/>
  <p>Response example:<pre>{"SOLR_URL":"http://dev11.library.emory.edu:9083/solr/etd","CONTENT_MODELS":[["info:fedora/emory-control:ETD-1.0"]]}</pre></p></li>
  
  <li><i>/services/indexdata/<b>{PID}</b>/</i> - single solr index for individual pid.
  <p>Response returns json with field names and values that correspond to the etd solr configuration.</p></li>
</ul>

<hr/>
<p><small>2011-08-24</small></p>
