<? if ($this->acl->isAllowed($this->role, $this->etd, "review")
       && !($this->controller == 'manage' && $this->action == 'review')): ?>
  <a class="action" href="<?= $this->url(array('controller' => 'manage',
		'action' => 'review', 'pid' => $this->etd->pid), '', true, false) ?>">
     <img src="<?= $this->linkTo('images/action_icons/inspect.png') ?>"> 
     review</a>
<? endif ?>
<? if ($this->acl->isAllowed($this->role, $this->etd, "approve")
       && !($this->controller == "manage" &&  $this->action == "approve")): ?>
  <a class="action" href="<?= $this->url(array('controller' => 'manage',
		'action' => 'approve', 'pid' => $this->etd->pid), '', true, false) ?>">
      <img src="<?= $this->linkTo('images/action_icons/check.gif') ?>"> 
      approve</a>
<? endif ?>
       <? if ($this->acl->isAllowed($this->role, $this->etd, "request document changes")): ?>
<a class="action" href="<?= $this->url(array('controller' => 'manage',
	'action' => 'requestchanges', 'pid' => $this->etd->pid,
	'type' => 'document'), '', true, false) ?>">
        <img src="<?= $this->linkTo('images/action_icons/x.gif') ?>">
	request changes</a> <? endif ?>

    <? if ($this->acl->isAllowed($this->role, $this->etd, "unpublish")): ?>
<a class="action" href="<?= $this->url(array('controller' => 'manage',
		'action' => 'unpublish', 'pid' => $this->etd->pid), '', true, false) ?>">unpublish</a> <? endif ?>
