<?=  $this->render('email/_debug.phtml'); ?>
<p>Dear <?= $this->etd->authorInfo->mads->name ?>,</p>

<p>When you submitted your dissertation or thesis to the
Emory University ETD repository, you requested that the full text of
your document remain inaccessible for <?= $this->etd->mods->embargo ?>.</p>

<p>Unless the library is informed otherwise, the full text of your thesis 
will be available via our website on <?= $this->etd->mods->embargo_end ?>.  
It is your responsibility to request an extension of your access restriction.
To request an extension in the Emory ETD system, please contact
<a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
or reply to this email with your request.</p>


<p>
<b>FOR AUTHORS WHO ALSO SUBMITTED TO PROQUEST:</b> <br>
You will need to contact ProQuest's Author Relations department to request an extended access restriction/embargo in their database. You can reach them at 1-800-521-0600 ext. 77020 or via email at
<a href="mailto:disspub@proquest.com>">disspub@proquest.com</a>.
</p>
