<h1>Available Reports</h1>
<ul id="reports_ul">
  <li><a href="<?= $this->url(array("controller" => "report",
      "action" => 'summary-stat'), '', true); ?>">Summary Statistics</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
      "action" => 'commencement-review'), '', true); ?>">Laney Graduate School Commencement Report</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
    "action" => 'grad-data'), '', true); ?>">Laney Graduate School Academic Year Report</a>
  <?= $this->FiletypeIcon("text/csv") ?></li>
  <li><a href="<?= $this->url(array("controller" => "report",
      "action" => 'export-emails')) ?>">Export Student Emails</a>      
    <?= $this->FiletypeIcon("text/csv") ?></li>    
  <li><a href="<?= $this->url(array("controller" => "report",
    "action" => 'embargo-csv'), '', true); ?>">Upcoming Embargos</a>
  <?= $this->FiletypeIcon("text/csv") ?></li>
  <li><a href="<?= $this->url(array('action' => 'embargo')) ?>">Requested Embargo Duration</a>
  <?= $this->FiletypeIcon("application/x-shockwave-flash") ?></li>
  <li><a href="<?= $this->url(array('action' => 'page-length')) ?>">Document Length</a>
  <?= $this->FiletypeIcon("application/x-shockwave-flash") ?></li>
  <li><a href="<?= $this->url(array('action' => 'standard')) ?>">Create A Report</a>
  <?= $this->FiletypeIcon("text/csv") ?></li>
</ul>

