<div id="calendar">
<h2>Calendar</h2>

<? foreach ($this->calendar as $title => $details): ?>
  <p>
    <u><b><?= $title ?></b></u>
    <? if (isset($details["description"])): ?>
        <br /><?= $details["description"] ?>
    <? endif ?>

    <?// Get the start, end and location for each entry,  can have mutiple per title?>
    <? foreach ($details["whenWhere"] as $ww): ?>
        <? if (isset($ww["start"]) && $ww["start"]!=''): ?>
            <li><?= $ww["start"] ?>
        <? endif ?>
        <? if (isset($ww["end"]) && $ww["end"]!=''): ?>
            - <?= $ww["end"] ?>
        <? endif ?>
        <? if (isset($ww["where"]) && $ww["where"] != ''): ?>
            <?= $ww["where"] ?>
        <? endif ?>
        </li>
    <? endforeach ?>
  </p>
<? endforeach ?>

</div> 

