<div id="calendar">
<h2>Calendar</h2>
<? /* FIXME: how should this be dynamically stored/updated? */ ?>

<p><b>October 23, 28, 29 and 30, 2008:</b>ETD Copyright Workshops in Woodruff Library (Note: The session on the 29th will be held in the Rollins School of Public Health).</p>

<p><b>October 30 and November 4, 2008:</b> Submission Workshops in Woodruff Library</p>

<p><b>November 7, 2008:</b> Theses/Dissertations Due at Graduate School for December Graduation</p>

<p><b>February 6, 2009:</b> Degree Applications Due for May Graduation</p>

<p><b>April 3, 2009:</b> Theses/Dissertations Due at Graduate School for May Graduation</p>

<p><b>May 11, 2009:</b> Commencement</p>

<p><b>July 2, 2009:</b> Degree Applications Due for August Graduation</p>

<p><b>July 31, 2009:</b> Theses/Dissertations Due for August Graduation</p>
</div>


