<div id="calendar">
<h2>Calendar</h2>

<? foreach ($this->calendar as $title => $details): ?>
  <p>
    <u><b><?= $title ?>:</b></u>
    <? if (isset($details["description"])): ?>
        <br /><?= $details["description"] ?>
    <? endif ?>
    <? if (isset($details["start"]) && $details["start"]!=''): ?>
        <?= $details["start"] ?>
    <? endif ?>
    <? if (isset($details["end"]) && $details["end"]!=''): ?>
        - <?= $details["end"] ?> 
    <? endif ?>
    <? if (isset($details["where"]) && $details["where"] != ''): ?>
        <?= $details["where"] ?>
    <? endif ?>
  </p>
<? endforeach ?>

</div> 

