<div id="news">
  <h2>News and Announcements</h2>
   
<p><b>ETD Submission Workshops for Fall graduates</b><br/>

We will be holding workshops for students submitting their theses and dissertations on Thurs., Oct 30 from 4:00-5:00 in Woodruff Library Room 312 and on Mon., Nov. 4 from 12:00 to 1:00 in Woodruff Library Room 314.<br/>
Feel free to drop by any time during these hours and we will assist you with your submission.</p>

<p><b>Electronic Submission of Theses and Dissertations Now Required </b><br/>
All students completing their degree programs in the Emory Graduate School must now
submit their theses and dissertations electronically. <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Detailed instructions on submitting your ETD</a> are available on the site. Please contact 
the ETD staff at <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
if you need assistance.  Any questions on graduation 
requirements should be referred to the Graduate School.</p>
 
<p><b>Submission Form for All ETD Program Participants </b><br>
 All students depositing their thesis or dissertation must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>


</div>
