<div id="news">
  <h2>News and Announcements</h2>

 <p><b>Submitting your Dissertation in November? - Mon, 08 Oct 2007, 10:00:36 EST</b><br/>
We will be holding two workshops in the library for people submitting their dissertations this fall.   The workshops will be held in Woodruff Library room 312 from 3:30pm - 5:30pm on Thurs. Nov. 1 and Thurs. Nov. 8.  Feel free to drop by at any time during those two hours and we will assist you with using the electronic submission software, as well as creating your PDF files, if necessary.</p>

<p><b>Submission Form for All Pilot Participants - Thu, 28 Jun 2007, 14:52:02 EST</b><br>
 Everyone participating in the pilot must complete the <a href="https://etd.library.emory.edu/docs/ETD_Submission_Form.doc">ETD Submission form</a>.  This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>

(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>
    
</div>