<div id="news">
  <h2>News and Announcements</h2>
  
   <p><b>The ETD System Software Has Been Updated.  New Instructions. </b><br/>
We have been working for a number of months on revamping the submission system for the
ETD Repository.  We would like to thank the pilot participants for their comments and suggestions.
<a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Instructions on how to use the new system are now available.</a>   Please contact the ETD staff at 
etd-admin@listserv.cc.emory.edu with any questions or comments about the new system.</p>

 <p><b>In Pilot Program and Submitting your Dissertation in March? </b><br/>
We will be holding a workshop in the library for students in Art History, Anthropology, 
Chemistry and Epidemiology submitting their dissertations this spring.
The workshop will be held in Woodruff Library room 312 from 3:30pm - 5:00pm on Wednesday, March 19th.
Feel free to drop by at any time during those two hours and we will assist you with using the new electronic
submission software, as well as creating your PDF files, if necessary. Contact Paul O'Grady (pogrady@emory.edu) with any questions.</p>

<p><b>Copyright Workshops for Graduate Students</b><br/>
The Graduate School and the Intellectual Property Rights Office of University Libraries
will be holding workshops for graduate students on copyright law and author rights
and responsibilities.  The workshops will be held March 25th at 11:30am and April 2nd at 4pm in Woodruff Library Room 314
Please contact Paul O'Grady (pogrady@emory.edu) to reserve a spot or if you have any questions. </p>

<p><b>Submission Form for All Pilot Participants </b><br>
 Everyone participating in the pilot must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>
    
</div>