    <? if ($this->acl->isAllowed($this->role, $this->etd, "review")): ?>
<a class="action" href="<?= $this->url(array('controller' => 'manage',
		'action' => 'review', 'pid' => $this->etd->pid), '', true) ?>">review</a> <? endif ?>
    <? if ($this->acl->isAllowed($this->role, $this->etd, "approve")): ?>
<a class="action" href="<?= $this->url(array('controller' => 'manage',
		'action' => 'approve', 'pid' => $this->etd->pid), '', true) ?>">approve</a> <? endif ?>
       <? if ($this->acl->isAllowed($this->role, $this->etd, "request changes")): ?>
<a class="action" href="<?= $this->url(array('controller' => 'manage',
	'action' => 'requestchanges', 'pid' => $this->etd->pid), '', true) ?>">request changes</a> <? endif ?>

    <? if ($this->acl->isAllowed($this->role, $this->etd, "unpublish")): ?>
<a class="action" href="<?= $this->url(array('controller' => 'manage',
		'action' => 'unpublish', 'pid' => $this->etd->pid), '', true) ?>">unpublish</a> <? endif ?>
