<?/* FIXME: lots of duplication with submission/review */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user);  ?>
<style type="text/css">
   p.note, #submission_status, #history {display:none; }
</style>
<?=  $this->render('view/fullrecord.phtml'); ?>
<?=  $this->render('submission/_reviewinfo.phtml'); ?>
</hr>


<p><b><a href="<?= $this->url(array('action' => 'accept')) ?>">Accept</a></b></p>

<p><b><a href="<?= $this->url(array('action' => 'requestchanges')) ?>">Request Changes</a></b></p>
