<h1>Unpublish Record</h1>

<p><b>Title:</b> <?= $this->etd->title() ?><br/>
<b>Author:</b> <?= $this->etd->author() ?></p>

<form name="unpublish" method="post"
   action="<?= $this->url(array("action" => "doUnpublish"))?>">
<?= $this->formHidden("pid", $this->etd->pid()) ?>

<p><?= $this->formLabel("reason", "Reason for unpublishing: "); ?>   
<?= $this->formText("reason", "", array("size" => 50)); ?></p>

  <?= $this->formSubmit("unpublish", "unpublish"); ?>
</form>