<h1>Obtaining Bound Copies of Your Theses and Dissertations</h1>

<p>In order to introduce more flexibility into the process of creating
bound copies of theses and dissertations, Emory University Libraries
and the Graduate School have decided to offer authors more choices for
having paper copies of their work produced.  In the past, all students
have been asked to pay to have four copies of their work bound.
Students submitting electronically will no longer face this
requirement.</p>

<p><b>Due to space constraints, the library will no longer retain a
bound copy of theses and dissertations for which an electronic copy is
available, and therefore authors will not be asked to produce bound
copies for the Emory Libraries.</b></p>

<p>Authors interested in having bound copies of their thesis or
dissertation produced for themselves, their committee members, or
their department/program libraries can consult the vendors below.
Although we have examined the work of the vendors listed on this page,
we cannot endorse any particular entity. This is not intended to be a
comprehensive list.  We encourage authors to explore a variety of
vendors in order to obtain copies of their theses and dissertations at
a price and quality that meets their satisfaction.</p>

<p>Vendors:</p>

<ul>
 <li>The HF Group Inc.:
    <a href="http://www.thesisondemand.com/">http://www.thesisondemand.com/</a></li>
 <li>PhD Book Binding: 
    <a href="http://www.phdbookbinding.com/">http://www.phdbookbinding.com/</a></li>
 <li>The National Library Bindery Co.<br/>
     100 Hembree Park Drive<br/>
     P.O. Box 428<br/>                   
     Roswell, GA  30076<br/>
     770-442-5490<br/></li>
</ul>