<? if ($this->env == "production"):   	/* Google Analytics */ ?>
<? $role = isset($this->current_user) ? $this->current_user->role : 'guest'; ?>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3821577-1']);
  _gaq.push(['_trackPageview']);
  <? /* custom variable to track user role. slot 1, visitor-level scope */ ?>
  _gaq.push(['_setCustomVar', 1, 'User Role', '<?= $role ?>',  1]); 

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<? endif ?>
