<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
   <title>Emory ETDs : <?= $this->escape($this->title) ?></title>
  <?= $this->css('etd.css'); ?>
  <link rel="Bookmark" href="<?= $this->linkTo('favicon.ico') ?>"/>
  <link rel="SHORTCUT ICON" href="<?= $this->linkTo('favicon.ico') ?>" />
</head>
<body>
  <div class="print_content">
     <?= $this->content ?>
   </div>
</body>
</html>  