<?/* left side navigation */?>
<div id="sidenav">

 <? if (isset($this->current_user) && $this->acl->isAllowed($this->current_user, "etd", "create")): ?>
 <p><b><a
 	class ="start-submission" href="<?= $this->url(array("controller" => "submission", "action" => "start"), "", true); ?>">Submit your Thesis &gt;</a></b></p>
<? endif ?>	


<div class="section">
  <p><a href="<?= $this->url(array("controller" => "docs", "action" => "about"), '', true); ?>">About Us</a></p>
  <p><a href="<?= $this->url(array("controller" => "docs", "action" => "faq"), '', true); ?>">Frequently Asked Questions</a></p>
  <p><a href="<?= $this->url(array("controller" => "docs"), '', true); ?>/help" class="help">ETD Help</a></p>
  <p><a href="<?= $this->url(array("controller" => "docs", "action" => "policies"), '', true); ?>">Policies and Procedures</a></p>
  <p><a href="<?= $this->url(array("controller" => "docs", "action" => "ip"), '', true); ?>">Intellectual Property</a></p>
</div>

<? if (! $this->suppress_sidenav_browse): ?>
  <? if (!($this->controller == "index" && $this->action == "index")): ?>
  <? /* don't show search & browse navigation when we are on the home page (redundant) */ ?>
    <div class="section">
     Search ETDs:
      <form name="search" method="get" action="<?= $this->url(array("controller" => "search", "action" => "results"), '', true)?>">
        <?= $this->formText("query"); ?>
        <?= $this->formSubmit("Search", "Go >", array("class" => "submitlink")); ?>
      </form>
     <a href="<?= $this->url(array("controller" => "search"), '', true)?>">Advanced Search</a>
   </div>
   <div class="section">
    Browse by:
    <? $this->browse_class = 'browse'; ?>
    <?=  $this->render('browse/_categories.phtml'); ?>
    <?=  $this->render('_proquest.phtml'); ?>
   </div>
  <? endif ?>  <? /* end home page */ ?>

  <div class="section">
    <p><a href="http://www.emory.edu/GSOAS/">Laney Graduate School</a></p>
    <p><a href="http://www.college.emory.edu/">Emory College</a></p>
    <p><a href="http://www.emory.edu/libraries.cfm">Emory Libraries</a></p>
  </div>
<? endif ?> <? /* end suppress sidenav search & browse */ ?>
</div>

