<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
 <? if ($this->xforms): ?>
  xmlns:xf="http://www.w3.org/2002/xforms"
  xmlns:ev="http://www.w3.org/2001/xml-events"
   <? if (isset($this->namespaces)): ?>
    <? foreach ($this->namespaces as $prefix => $uri): ?>
	 xmlns:<?= $prefix ?>="<?= $uri ?>"
    <? endforeach ?>
    <? endif ?>
 <? endif ?>    	 
  xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
   <title>ETD08 : <?= $this->escape($this->title) ?></title>
  <?= $this->css('etd.css'); ?>
  <?= $this->render('dc_header.phtml'); ?>

  <? if ($this->xforms): ?>
       <?= $this->render('xforms_head.phtml'); ?>
  <? endif ?>

</head>
<body>

<div id="header">
  <div id="emory">
	<a href="http://www.emory.edu"><img
	    src="http://wilson.library.emory.edu/~rsutton/etds/images/emory.gif" alt="EMORY" title="EMORY"/></a>
      </div>
<div id="title"><a href="<?= $this->url(array(), '', true) ?>">Electronic Theses and Dissertations</a> (ETD08)</div>

  <div id="photo">
	<img src="http://wilson.library.emory.edu/~rsutton/etds/images/woodruff-path.jpg"/> 
<p>Welcome to Emory University's Electronic Thesis and Dissertation
	  repository.</p>
      </div>
</div>


<div id="login">

 <? if (isset($this->current_user)): ?>
   <b>Welcome, <?= $this->current_user ?></b>
   <? if ($this->site_mode == "development"): ?>
      (<span id="current_role"><?= $this->current_user->role ?></span>)
   <? endif ?>

   <ul class="horizontal">
      <li class="first">
         <a title="logout"
		href="<?= $this->url(array("controller" => "auth", "action" => "logout"), "", true)?>"><b>Logout &gt;</b></a>

	    </li>

          <? if ($this->acl->isAllowed($this->current_user, "etd", "manage")): ?>
            <li><a href="<?= $this->url(array("controller" => "manage"), "", true)?>">Manage</a></li>
   	  <? endif ?>

            <li><a href="<?= $this->url(array("controller" => "browse", "action" => "my"), "", true)  ?>">My ETDs</a></li>

<!--      	    <li><a title="user information" href="<?= $this->url(array("controller" => "user", "action" => "view"), null, true) ?>">Profile</a></li> -->

            <li><a href="docs/id/faq#help">Help</a></li>

	    <? if ($this->site_mode == "development"): ?>
	       <?= $this->render("_setrole.phtml"); ?>
	    <? endif ?>
         </ul>

 <? else: ?>
  Emory Login: 
  <form name="login" method="post"
    action="<?= $this->url(array("controller" => "auth", "action" => "login"), "", true)?>">
  <?= $this->formText("login[username]", ""); ?>
  <?= $this->formPassword("login[password]", "", array("size" => 32)); ?>
  <?= $this->formSubmit("Submit", "Login >", array("class" => "button submitlink")); ?>
</form>	

 <ul class="horizontal">
   <li><a href="" class="help">Why Login?</a></li>
 </ul>

 <? endif ?>
</div>

<div id="navbar">
  <div id="etdhome"><a href="<?= $this->url(array(), "", true) ?>">ETD HOME</a></div>
  <?=  $this->render('navbar-curve.phtml'); ?>
</div>

<?=  $this->render('sidenav.phtml'); ?>

<div class="content">

<? if (isset($this->messages)):?>
  <div id="messages" style="color:green;">
   <? foreach ($this->messages as $message): ?>
     <p<? if (strpos($message, "Error") !== false): ?> style="color:red" <? endif ?> ><?= $message ?></p>
   <? endforeach ?>
  </div>
<? endif ?>


  <?= $this->content ?>


</div> <!-- end content div -->

<div id="footer">
 <a
    href="http://www.emory.edu/copyright.cfm">&copy; 2007 Emory
    University.</a> 
   Version Zend-0.1 updated 8/07. 
 <a href="<?= $this->url(array("controller" => "docs", "action" => "ip")); ?>">Rights and Privileges</a>
</div>

</body>
</html>