<style>
  #beta_warning {
    background-color: #ff7373;
    border: 1px solid red;
    top: 0;
    width: 100%;
    height: 50px;
    z-index: 9000000000;
    margin-bottom: 2px;
  }
  #beta_message {
    margin-top: 15px;
    text-align:center;
    font-weight: bold;
    font-size: 16px;
  }
</style>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.1/jquery.min.js"></script>
<script type="text/javascript">
  var $j = jQuery.noConflict();  
  $j(document).ready(function() {
    var div = $j('#beta_warning');
    var start = $j(div).offset().top;
    $j(window).scroll(function() {
      var p = $j(window).scrollTop();
      $j(div).css('position', ((p)>start) ? 'fixed' : 'static');
      $j(div).css('top', ((p)>start) ? '0px' : '');
    }); 
  });
</script>
<div id="beta_warning">
  <div id="beta_message">
    This is the ETD test site. Content may be changed or deleted without warning.
  </div>
</div>
