<? /* common view layout for contact information view and full record review */ ?>
<? $user = $this->user->mads; ?>
<div class="contact_info">
 <? if (isset($user->current)): ?>
 <h2>current</h2>
    <div class="indent">
      <? $this->affiliation = $user->current; ?>
      <?= $this->render("user/address.phtml"); ?>
      <? if ($user->current->phone): ?>
        <p><b>phone:</b> <?= $user->current->phone ?></p>
      <? endif ?>   
      <p><b>email:</b> <?= $user->current->email ?>
    </div>
<? endif ?>

<? if (isset($user->permanent)): ?>
  <h2>permanent</h2>
  <div class="indent">
    <? $this->affiliation = $user->permanent; ?>
    <?= $this->render("user/address.phtml"); ?>
    <? if ($user->permanent->phone): ?>
       <p><b>phone:</b> <?= $user->permanent->phone ?></p>
    <? endif ?>
   <p><b>email:</b> <?= $user->permanent->email ?></p> <? /* required field, so not checking if set */ ?>
  </div>
<? endif ?>
<p><b>netid:</b> <?= $user->netid ?></p>
</div>