<?= $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>  
  <meta name="robots" content="noindex,nofollow"/>
   <title>Emory ETDs : <?= $this->escape($this->title) ?></title>
  <?= $this->css('etd.css'); ?>
  <?= $this->css('print.css'); ?>
  <link rel="Bookmark" href="<?= $this->linkTo('favicon.ico') ?>"/>
  <link rel="SHORTCUT ICON" href="<?= $this->linkTo('favicon.ico') ?>" />
</head>
<body>

  <p>Emory University's Electronic Thesis and Dissertation Repository |
	<a href="http://etd.library.emory.edu/">http://etd.library.emory.edu/</a></p>
  <hr/>

  <?= $this->layout()->content ?>

<?=  $this->render('google_analytics.phtml'); ?>

</body>
</html>  