Emory Login: 
  <form name="login" method="post"
    action="<?= $this->url(array("controller" => "auth", "action" => "login"), "", true)?>">
  <?= $this->formText("login[username]", ""); ?>
  <?= $this->formHidden("login[url]", $_SERVER['REQUEST_URI']); ?>
  <?= $this->formPassword("login[password]", "", array("size" => 32)); ?>
  <?= $this->formSubmit("Submit", "Login >", array("class" => "button submitlink")); ?>
    <span class="tip">(Login to submit or manage theses and dissertations)</span>
</form>
