<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body>
<p align="center"><strong>Instructions for Electronic Submission of your Thesis/Dissertation</strong></p>
<p><br>
  1. Be sure to turn in to the Graduate School all paper forms (including a paper
  copy of the PDF file you will upload to the ETD system) immediately after your
  electronic submission.</p>
<p><br>
  2. Before you proceed, make sure that you have all necessary files: (1) your
  thesis or dissertation in <strong>PDF</strong> form; (2) Your thesis or dissertation in <strong>Original</strong>  Form -- usually Microsoft Word; and (3) any <strong>supplemental
  files</strong> such as
  datasets, audio, video, etc. (optional).</p>
<p><br>
  3. To begin the process, go to etd.library.emory.edu and login using your Emory
  network ID and password at the top of the page. A "Submit Your Thesis" Link
  should appear on the left side of the page. Click on that link to begin your
  submission.</p>
<p><br>
  4. The process begins by uploading your PDF. Click on "Browse"; to
  locate your file, and then click on "Begin." There will be a momentary
  delay as the system reads your file: you should see a note in green on
  the screen that says "Processing." <strong>Since the system is extracting
  information from your PDF file, it is essential that your document follow the
  order dictated by the Graduate School:</strong> (<em>i.e.</em>, Circulation
  Agreement, Approval Sheet, Dissertation/Thesis Abstract Cover Sheet, Abstract,
  etc.). </p>
<p>Access Restriction By Chapter: <em>if you are not submitting your document
    as a single PDF because you are restricting access to only certain parts
    of your document</em>,
  see the note under &quot;Edit Files&quot; below.</p>
<p><br>
  5. The submission summary page shows your submission in its preliminary form.
  You will see various edit links and the Submission Status Box:<br>
  <img src="<?= $this->linkTo("images/submit_preview.jpg") ?>"/><br>
</p>
<p>You should review all the pre-populated information for accuracy, and then
  proceed with your submission by supplying the information requested under each "edit" link.
  (You may also proceed through your submission by clicking on the items in the
  Submission Status Box.) Each completed section will be marked with a green check
  mark, and each incomplete section will be marked with a red "x." </p>
<p><br>
  Note: throughout the submission process, required fields are marked with
      an asterisk (*) and invalid entries in fields will be flagged in red. </p>
<p><strong>Edit Contact Information:</strong><br>
  We collect this information primarily for Proquest. When your submission is
    sent to Proquest, they may need to contact you for various reasons. The default
    address in this section will be pulled from your Emory record. You may edit
    your current and permanent address as needed. Be sure to include the date
    valid for your permanent address.<br>
  The non-Emory email address is especially important. If you are requesting
  an access restriction, you will receive an e-mail from the library at that
  address 60 days prior to the expiration of the access restriction to inform
  you that your document will be released via the internet. You are responsible
for letting us know if your contact e-mail address changes.</p>
<p><br>
  <strong>Edit Title/Edit Abstract/Edit Table of Contents:</strong> <br>
  In these sections, you may make changes to your title, abstract or table of
  contents if necessary. Be sure to limit your abstract to 350 words (as required
by Proquest/UMI). </p>
<p><br>
  <strong>Edit Thesis Information:</strong><br>
  a)	You may choose to change your name as it appears in your ETD record.<br>
  b)	Please enter the language in which your thesis or dissertation is written<br>
  c) Enter keywords (or phrases) to help researchers locate your work in the
  repository. Enter ONLY one word or phrase in the input box. Click on "add
  another keyword" for addition phrases. DO NOT enter multiple words in
  the box separated by commas. Proquest collects up to six keywords, but you
  may enter more in the system if you choose. We will send the first six to Proquest.<br>
d)	Enter the degree you will be receiving this submission period.</p>
<p><br>
  <strong>Edit Advisor and Committee Members:</strong><br>
  The system will attempt to extract the names of your advisor and committee
  member from your PDF. If it cannot make a match, you will need to enter these
  manually. For each faculty member, enter their last name and then wait while
  the system locates them. If you cannot locate a faculty member on the drop
down suggestor, you should enter them in the "Non-Emory Faculty Member" section.</p>
<p><br>
  <strong>Edit Rights and Restrictions:</strong><br>
  On the Author Rights and Access Restrictions page:<br>
  a) Indicate whether you have requested an access restriction on your submission
    form. The Graduate School will enter the term of the restriction upon approval.<br>
  b) Indicate whether you would like Proquest to register your copyright for
    you. This requires the payment of a fee. See Proquest submission materials
    for form. (Note that this is optional, but recommended.)<br>
  c) Check off the box for submission agreement. This section is intended to
  remind you of what you have agreed to in the Emory submission form.</p>
<p><strong>Edit Research Fields:</strong><br>
  Proquest requires that you submit at least one and up to three research fields.
    Choose the fields by clicking on each enumerated field; your choices will
    appear at the top of the page. The first field you choose will be designated
    your "primary" field. You may drag and drop fields in your list
    to rearrange their order.<br>
</p>
<p><strong>Edit Program:</strong><br>
  The system will attempt to extract the name of your graduate program from your
  Emory record. If the entry in this section is missing or incorrect, you should
  enter it manually by search for your program by division/discipline/program
(e.g., Graduate =>Humanities =>English).</p>
<p><br>
  <strong>Edit Files:</strong><br>
  You must upload a copy of your thesis or dissertation in original format. You
  may do this by clicking on either the "original file" link in the
  submission box or the "add another file" link in the files section
  at the bottom of the submission summary page. Upload your file using the browse
button on the "Add File to Record" page. </p>
<p><br>
  You may also <strong>add supplemental files</strong> on this page. Choose "supplemental
  file" from the "type of file to add" dropdown list and proceed
  to upload.<br>
  After upload, you may edit the author and document description fields if you
  choose. <br>
</p>
<p>Note: most users will upload their thesis or dissertation as a single PDF.
  <em>In the unusual event that sections of the document (rather than the entirety)
  need to be embargoed</em>, you should initially (upon entering the system for the
  first time) upload the first section of your thesis or dissertation so that
  the system can extract the necessary data from your document. You should use
  the edit files section here to upload the additional PDF files.<br>
</p>
<p>6.	Once your record is complete, a "Review & Submit" Link
  will appear on the page below the Submission Status Box. </p>
<p></p>
<img src="<?= $this->linkTo("images/Review.jpg") ?>"/>
<p></p>
<p>The review and submit link will bring you to the review page where you will
  have a final opportunity to edit any of your data or upload files. If you need
  to change anything, click on the edit link, and you will be brought back to
  the edit page for that section. When you are done editing, click on "review & submit" again. <br>
  </p>
<p>7.	If you are satisfied with your submission, you should click on the "submit" button
  at the bottom of the page. It is important to note that once your document
  is submitted you may no longer edit it without the Graduate School's
  approval.<br>
  </p>
<p>8. You will receive an email to confirm that your document has been submitted.
  <strong>In the event that the Graduate School requests changes</strong>, your document will
  be returned to draft status. Do not attempt to submit a new record. You should
  go to edit files, remove your PDF, and upload a corrected version, and proceed
  with your submission. <br>
  </p>
<p>9. You will receive e-mails upon approval. You may check on the status of
  your submission by viewing your record under the "My ETDs" section
  of the site.<br>
  </p>
<p>10. After your graduation has been confirmed, your record will appear in the
    repository. If you chose the Open Access option, the full text of your document
    will be immediately available in PDF form. If you requested an access restriction,
    a link to your PDF will not appear in your record until the access restriction
    period expires. NOTE: the access restriction expires automatically, and it
    is the student&#8217;s responsibility to request extensions, if necessary.</p>
<p><br>
</p>

</body>
</html>
