<style>
    ol ul {margin-left: -1.5em}
    ol ul li {list-style-type:disc; padding-top: 0; margin-top: 0}
    ol ul li ul li {list-style-type:circle;}
    p {margin-bottom: 0}
    
</style>
<?= $this->javascript("jquery.local.js"); ?>
<noscript style="color:red">The submission process requires that you enable Javascript.</noscript>

<p>Please answer the following questions before you begin creating your record.</p>

<? if ($this->form_errors): ?>
<div id="messages">
  <? /* display appropriate detailed error message for any missing required fields */ ?>
  <? foreach ($this->form_errors as $err): ?>
    <p class="error">
      <? switch ($err): 
        case 'copyright': ?>You must answer about copyrighted materials.<? break ?>
        <? case 'patent': ?>You must answer whether or not your work may warrant patenting.<? break ?>
        <? case 'embargo': ?>You must answer whether or not you are requesting an access restriction.<? break ?>
        <? case 'embargo_abs_toc': ?>Because you have indicated you are requesting an access restriction, you must answer about your abstract or table of contents.<? break ?>
        <? case 'title': ?>A title is required to create your initial record.<? break ?>
      <? endswitch ?>
    </p>
  <? endforeach ?>
</div>
<? endif ?>

<form name="submission" id="submission" method="post" 
   action="<?= $this->url(array("action" => "start"))?>"> 

<ol id="screening-questions">
 <li> <!-- Question 1 -->
     <p>If your thesis or dissertation includes any text, audiovisual, or 
         other material not created by you or for which you no longer own 
         copyright, and which is not a fair use, you may need to seek permission 
         from the copyright owner.   NOTE:  All third party copyrighted 
         content should be properly cited, regardless of copyright status.</p>
     <p>These materials do not require permission:
     <ul>
         <li>Public domain materials (no longer protected by copyright)
            <ul>
               <li>Published in the US prior to 1923</li>
               <li>Unpublished materials when the author died more than 70 years ago</li>
               <li>Federal government documents created by a US government employee as part</li> 

            </ul>
         </li>
         <li><a href="http://creativecommons.org/" target="_blank">Creative Commons</a> licensed materials used in accordance with their licences</li>
         <li>Materials you authored and for which you currently own the copyright</li>
         <li>Photos you took and for which you currently own the copyright</li>
     </ul>
     </p>
     
     <p>You may typically rely on fair use to include these types of materials:
         <ul>
             <li>Short quotations of books, journal articles, poetry</li>
             <li>Film stills from movies</li>
             <li>Graphs, charts and tables of facts</li>
              <li>Screenshots of web pages (unless they include proprietary information)</li>
              <li>Materials which are integral to the argument being made (not simply illustrative), using no more than is necessary to make the argument</li>
         </ul>
</p>


<p>You may need permission to include these types of materials:
         <ul>
            <li>Images, particularly from ArtStor, other licensed databases, or archives and museums</li>
            <li>Articles or other materials you authored, but for which you no longer own copyright --  most common are journal articles where copyright was transferred to the publisher</li>
            <li>Long quotations of a page or more from a book</li>
            <li>Unpublished materials when the author died less than 70 years ago</li>
            <li>Poetry or music lyrics when used in their entirety or without comment or criticism</li>
            <li>Musical scores or sound recordings</li>
            <li>Computer Code without an open license</li>
</ul>
</p>

<p>See the <a href="https://classes.emory.edu/webapps/lobj-wiki-bb_bb60/wiki/CEI/_1251529_1/Home" target="_blank">Copyright Education Initiative</a> 
    on Blackboard for more information on the public domain, fair use, 
    Creative Commons, the permissions process, and example permission letters. 
    You can also contact the Libraries’ Scholarly Communications Office at 
    scholcomm@listserv.cc.emory.edu if you have questions.</p>

<p><b>Does your thesis or dissertation include text, audiovisual or other material for which you need permission?</b></p>
    
        <?= $this->formRadio('copyright', $this->answers['copyright'], 
        array('class' => 'required-field'), $this->yes_no) ?>
     <? /* copyright details: display if answer to copyright question is YES */ ?>
    <div id="copyright_yes"> 
      <p>You must obtain permissions or remove the copyrighted content from 
          your ETD before proceeding with submission. Please list all 
          materials for which you received permission on the ETD submission 
          form available on the <a href="https://etd.library.emory.edu/">ETD home page</a>.</p>
    </div>
<!--     <div id="copyright_perms_yes"> <? /*  Show if answered YES to permissions */ ?>
            <p>Complete Part 4 of the Submission Form.</p>
      </div>-->
    </li>


    <!-- Question 2 -->
    <li><p>Does your thesis or dissertation disclose or describe any inventions 
         or discoveries that could potentially have commercial application 
         and therefore may be patented?  (If you and/or your faculty 
         advisor(s) have any questions about patents and commercial 
         applications, please contact the Emory Office of Technology 
         Transfer at <a href="mailto:ott-web@emory.edu">ott-web@emory.edu</a>).</p>
    <?= $this->formRadio("patent", $this->answers["patent"],
       array('class' => 'required-field'), $this->yes_no) ?>
  <div id="patent_yes">   <? /* display only if yes to patent */ ?>	 
     <p>Further conversation with ETD administrators is required before you 
         can continue with the ETD submission process. Please contact ETD Help 
         at <a href="mailto:etd-admin@listerv.cc.emory.edu">etd-admin@listerv.cc.emory.edu</a> or call (404)727-5301.</p>
     <? /* TODO: use configured email; remove phone number? */ ?>
  </div>
</li>

<!-- Questions 3 -->
<li><p>The ETD repository allows two levels of access restriction on your work: 
        full or partial. With a partial access restriction, your abstract 
        and/or table of contents are available to the public, but the full 
        text of your thesis/dissertation is not available for viewing or 
        download until your access restriction expires. A full access 
        restriction allows you to restrict access to the abstract, table of 
        contents, and full text for the duration of the restriction period. 
        NOTE: All access restrictions must be approved by your advisor prior 
        to submission.</p>
    
    <p>Are you requesting an access restriction (see Part 3 below) for your 
        thesis or dissertation?</p>
    
        <?= $this->formRadio("embargo", ($this->answers["embargo"] == null ? null : $this->answers["embargo"]),
			     array('class' => 'required-field'), $this->yes_no) ?>
    <div id="embargo_yes">    <? /* display if answer to embargo is yes */ ?>
     <p>Should your abstract and/or table of contents be included in the access restriction?</p>
     
     <p>NOTE: You will specify your requested access restriction (full, table 
         of contents and/or abstract) later in the ETD record creation process.</p>

     <?= $this->formRadio("embargo_abs_toc", ($this->answers["embargo_abs_toc"] == null ? null : $this->answers["embargo_abs_toc"]), array('class' => 'required-field'), $this->yes_no) ?>
   </div>
</li>
</ol>

<p>Enter your thesis or dissertation title to begin the submission process.</p>

<!-- TODO: label needs to be bold, input field needs to be much longer -->
<div>
  <label for="etd_title" class="etd_title">Thesis or Dissertation Title</label>
  <?= $this->formTextarea("etd_title", $this->answers['title'], array("class" => "required-field")); ?> 
</div>

  <?= $this->formSubmit("Begin", "Begin >", array("class" => "button", "style" => "margin-left:10px")); ?>
  <span id="processing" style="display:none">Processing ... <span class="note">(this may take a moment)</span></span>
</form>

<script>          
var $j = jQuery.noConflict(); 
<? /* avoid conflict with prototype/scriptaculous while ETD has both */ ?>

$j(document).ready(function() {
  // configure divs to be conditionally displayed based on answers
  $j('input[name=copyright]').conditionalDisplay({
    conditions: { yes: '#copyright_yes' }
  });
  $j('input[name=copyright_permission]').conditionalDisplay({
    conditions: { yes: '#copyright_perms_yes', no: '#copyright_perms_no' }
  });  
  $j('input[name=patent]').conditionalDisplay({
    conditions: { yes: '#patent_yes' }
  });  
  $j('input[name=embargo]').conditionalDisplay({
    conditions: { yes: '#embargo_yes' }
  });  
  $j('input[name=embargo_abs_toc]').conditionalDisplay({
    conditions: { yes: '#embargo_abs_toc_yes' }
  });  

   // trigger change for all radio inputs to show/hide subsections as appropriate
   // based on initial form values
   $j("input:radio").change();

   //validate required or conditionally required fields on the form
   $j('#submission').validate({
      rules: {
        "copyright_permission": {
          required: "#copyright-yes:checked"
        },
        "embargo_abs_toc" : {
          required: "#embargo-yes:checked"
        }
      },
      errorPlacement: function(error, element) {
        // custom error placement for yes/no radio inputs
        // zend framework view helper outputs input inside a label;
        // if there is a label following, put the error after it; otherwise, after element.
        var after = element.parent().nextAll('label');
        error.insertAfter(after.length > 0 ? after : element);
      },
      submitHandler: function(form) {
        // on valid submit, disable submit button (prevent double/multi-click creating multiple records)
        $j(form).find('input[type=submit]').attr('disabled', true);
        $j('#processing').show();  // display indicator that something is happening
        $j(form).submit();  // now actually submit the form
      }
    });
    jQuery.validator.addClassRules("required-field", {required: true});

});                                       
</script>