 <? /* month/year list  */ ?>
    <tr>
    <td colspan="4" class="caption">Views by month/year <? /* $date? */?></td>
    </tr>
    <? if (count($this->month) == 0): ?>
     <tr>
      <td colspan="4">No views during this period</td>
     </tr>
    <? else: ?>
	<? foreach ($this->month as $row): ?>
	<tr>
	  <td>
	     
	     <?= $row['month'] ?>
 	  </td>
	  <td class="count abstract"><?= $row['abstract'] ?></td>
	  <td class="count download"><?= $row['file'] ?></td>
	  <td>
  	       <div class="abstractviews" style="width:<?= $this->scaleGraphValue($row['abstract']) ?>px">
		<?= $row['abstract'] ?></div>
  	       <div class="downloads"
	    style="width:<?= $this->scaleGraphValue($row['file']) ?>px">
	     <?= $row['file'] ?></div>
	  </td>
	</tr>								
       <? endforeach ?>
   <? endif ?>
	     <? /* end month/year */ ?>
