<div id="news">
  <h2>News and Announcements</h2>
   
<p><b>Intellectual Property Rights Workshops for Fall graduates</b><br/>

Will the nature of your thesis or dissertation raise copyright issues? Come to a workshop to learn about navigating copyright issues in a digital environment.
<ul>
  <li>Tuesday, February 24, noon to 1pm, Woodruff Library Room 312. Focus on
   Humanities &amp; Social Sciences.</li>
   <li>Thursday, February 26, noon to 1pm, Rollins School of Public Health, Rita Rollins Room, 8th floor.  Focus on Sciences.</li>
  <li>Tuesday, March 3, noon to 1pm Woodruff Library Room 312.
		      Focus on Art History.</li>
   <li>Tuesday, Mar. 17, noon to 1pm Woodruff Library Room 312.
		      General session.</li>
</ul>
If you cannot attend a session with a focus related to your discipline, feel free to attend the general session. Each workshop will allow time for specific questions.<br/>
<a href="http://web.library.emory.edu/IP_rights/ETDCopyrightWorkshops.html">Find out more about the workshops</a>.<br/>

Please RSVP to Heather Williams at <a href="mailto:hrwilli@emory.edu">hrwilli@emory.edu</a> or 404.727.0127 so we know how many students to expect. If you have any questions, please contact Heather.</p>


<p><b>An Introduction to Emory's ETD Program</b></p>
<ul>
<li>Thursday, February 26 from 3:00pm to 4:00pm in Woodruff Library room 215</li>
<li>Wednesday, March 4 from 4:30pm to 5:30pm in Woodruff Library room 214</li>
<li>Monday, March 16 from 4:00pm to 5:00pm in Woodruff Library room 215</li>
</ul>
<p>Contact Erika Farr at <a href="elfarr@emory.edu">elfarr@emory.edu</a> for further information.</p>

<p>Please note, we will offer hands-on ETD submission workshops in the last two
weeks of March.</p>

<p><b>Electronic Submission of Theses and Dissertations Now Required </b><br/>
All students completing their degree programs in the Emory Graduate School must now
submit their theses and dissertations electronically. <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Detailed instructions on submitting your ETD</a> are available on the site. Please contact 
the ETD staff at <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
if you need assistance.  Any questions on graduation 
requirements should be referred to the Graduate School.</p>
 
<p><b>Submission Form for All ETD Program Participants </b><br>
 All students depositing their thesis or dissertation must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>


</div>
