<?=  $this->render('email/_debug.phtml'); ?>

<p>Dear <?= $this->etd->authorInfo->mads->name ?>,</p>

<p>Congratulations!  You have successfully submitted your ETD to
Emory's repository.</p>

<p>In order to complete the submission process, please attend to the following tasks:</p>

<ol>
<? if ($this->etd->schoolId() == "grad"): ?>
<li>Submit a paper copy for the Dean’s review</li>
<? elseif ($this->etd->schoolId() == "candler"): ?>
<li>Submit a paper copy (or copies) for binding, as necessary</li>
<? endif ?>
<li>Review your ETD record</li>
<? if ($this->etd->schoolId() == "rollins"): ?>
<li>Submit all required forms to the ADAP in your department</li>
<? endif ?>
<? if ($this->etd->schoolId() != "rollins"): ?>
    <li>Submit all required forms to the <?if($this->etd->schoolId() == "grad"):?>Laney <?endif?><?=$this->etd->admin_agent?></li>
<? else: ?>
    <li>Take the Graduate Information Survey and the Rollins Exit Survey</li>
<? endif ?>
<? if ($this->etd->schoolId() == "grad"): ?>
<li>Take the Graduate Exit Survey</li>
<? endif ?>
</ol>

<p>Details for each of these steps are included below.</p>

<ol>
<? if ($this->etd->schoolId() == "grad"): ?>
<li>Print a paper copy of the document you deposited for the Dean's review. To ensure that the Dean  will be reviewing the final version of your document, click the link below to visit your record in the ETD repository, open your PDF file, and print a paper copy.</li>
<?elseif($this->etd->schoolId() == "candler"): ?>
<li>Submit the number of paper copies you want bound (with required signatures) to the Candler Registrar’s Office for binding.  Include a completed Thesis/Dissertation Binding Request Form available on-line at:<br> <a href='http://www.candler.emory.edu/ACADEMIC/REGISTRAR/pdfs/Thesis_form_Feb09.pdf'>http://www.candler.emory.edu/ACADEMIC/REGISTRAR/pdfs/Thesis_form_Feb09.pdf</a> </li>
<?endif?>
<li>Please review your record, checking for accuracy and formatting:<br>
  <a href="<?= $this->etd->ark() ?>"><?= $this->etd->ark() ?></a></li>

<? if ($this->etd->schoolId() == "grad" || $this->etd->schoolId() == "candler" || $this->etd->schoolId() == "rollins"):?>
<li><p>All students must submit the ETD Submission Agreement Form with the paper copy of their
dissertation or thesis. In part 3 of that form, you must choose between the "Open" or "Restricted" Access options.
<? if ($this->etd->mods->isEmbargoRequested()): ?>
   You have requested <b>Restricted Access</b> (pending the approval of 
   <?= $this->etd->admin_agent ?>). The full text of your work will be published in
   the repository immediately after the expiration of your access
   restriction period.
<? else: ?>
   You have requested <b>Open Access</b>. The full text of your work
   will be published in the repository immediately after graduation.
<? endif ?></p>

 <p>You will receive written notification confirming whether or not your dissertation or thesis has been approved by the <?= $this->etd->admin_agent ?>. Upon approval you will receive further information regarding the publication of your ETD in our repository, as well as your opportunity to order bound copies.</p>
</li>

<? if($this->etd->schoolId() == "rollins"): ?>
<li>You will soon receive communication from Rollins Career Services about the Graduate Information Survey and the Rollins Exit Survey. Please take the time to complete these surveys, as information gathered from them is important to both Rollins and future students.</li>
<? endif ?>

<? elseif($this->etd->schoolId() == "honors"): ?>
<li><p>All students must submit a hard copy of the ETD Submission Agreement Form to Ms. Elizabeth Fricker in White Hall 300 by April 22, 2010 along with other required forms. You may find these requirements in the guidelines distributed earlier or on the LearnLink conference for College Honors.</p>
<? if ($this->etd->mods->isEmbargoRequested()): ?>
   You have requested <b>Restricted Access</b>. The full text of your work will be published in
   the repository immediately after the expiration of your access
   restriction period.
<? else: ?>
   You have requested <b>Open Access</b>. The full text of your work
   will be published in the repository immediately after graduation.
<? endif ?></p>

 <p>You will receive written notification confirming whether or not your dissertation or thesis has been approved by the <?= $this->etd->admin_agent ?>. Upon approval you will receive further information regarding the publication of your ETD in our repository, as well as your opportunity to order bound copies.</p>
</li>
<? endif ?>
<? if ($this->etd->schoolId() == "grad"): /* not applicable to honors etds */ ?>
<li>Soon after graduation, you will receive an email message notifying you that your dissertation or thesis has been published by the ETD system. You will find a link to the Graduate Exit Survey in that email. Please take the time to provide valuable feedback to the Graduate School by completing this survey.</li>
<? endif ?>
