<?=  $this->render('email/_debug.phtml'); ?>
<p><i>*****PLEASE DO NOT RESPOND TO THIS EMAIL*****</i></p>
<br />

<p>Dear <?= $this->etd->authorInfo->mads->name ?>,</p>

<p>Congratulations!  You have successfully submitted your ETD to
Emory's repository.</p>

<p>In order to complete the submission process, please attend to the following tasks:</p>

<ol>
<li>Review your ETD record</li>
<? if ($this->etd->schoolId() == "rollins"): ?>
<li>Submit all required forms to the ADAP in your department</li>
<? endif ?>
<? if ($this->etd->schoolId() != "rollins"): ?>
    <li>Submit all required forms to the <?if($this->etd->schoolId() == "grad"):?> <?endif?><?=$this->etd->admin_agent?></li>
<? else: ?>
    <li>Take the Graduate Information Survey and the Rollins Exit Survey</li>
<? endif ?>
</ol>

<p>Details for each of these steps are included below.</p>

<ol>
<li>Please review your record, checking for accuracy and formatting:<br>
  <a href="<?= $this->etd->ark() ?>"><?= $this->etd->ark() ?></a></li>

<? if ($this->etd->schoolId() == "grad" || $this->etd->schoolId() == "candler" || $this->etd->schoolId() == "rollins"):?>
<li><p>All students must submit the ETD Submission Agreement Form<? if ($this->etd->schoolId() == "candler"):?> and title page with original signatures<? endif ?>. In part 3 of that form, you must choose between the "Open" or "Restricted" Access options.
<? if ($this->etd->mods->isEmbargoRequested()): ?>
   You have requested <b>Restricted Access</b> (pending the approval of
   <?= $this->etd->admin_agent ?>). The full text of your work will be published in
   the repository immediately after the expiration of your access
   restriction period.
<? else: ?>
   You have requested <b>Open Access</b>. The full text of your work
   will be published in the repository immediately after graduation.
<? endif ?></p>

 <p>You will receive notification confirming whether or not your dissertation or thesis has been approved by the <?= $this->etd->admin_agent ?>.</p>
</li>

<? if($this->etd->schoolId() == "rollins"): ?>
<li>You will soon receive communication from Rollins Career Services about the Graduate Information Survey and the Rollins Exit Survey. Please take the time to complete these surveys, as information gathered from them is important to both Rollins and future students.</li>
<? endif ?>

<? elseif($this->etd->schoolId() == "honors"): ?>
<li>

<p>All students must submit a hard copy of the ETD Submission Agreement Form to Dr. Brandy Simula in White Hall 300 along with other required forms. You may find these requirements in the guidelines distributed earlier or on the Blackboard site for College Honors.</p>

<? if ($this->etd->mods->isEmbargoRequested()): ?>
   You have requested <b>Restricted Access</b>. The full text of your work will be published in
   the repository immediately after the expiration of your access
   restriction period.
<? else: ?>
   You have requested <b>Open Access</b>. The full text of your work
   will be published in the repository immediately after graduation.
<? endif ?></p>

 <p>You will receive written notification confirming whether or not your dissertation or thesis has been approved by the <?= $this->etd->admin_agent ?>.
</p>
</li>
<? endif ?>
<? if ($this->etd->schoolId() == "grad"): /* not applicable to honors etds */ ?>
<p>Soon after graduation, you will receive an email message notifying you that your dissertation or thesis has been published by the ETD system.</p>
<? endif ?>
