<p>embargo trends</p>

<table>
<? foreach ($this->data as $semester => $totals): ?>
  <tr><th rowspan="<?= count($totals) + 1 ?>" style="vertical-align:top">
   <?= $semester ?>
   </th></tr>

  <? foreach ($totals as $duration => $count): ?>
    <tr><td><?= $duration ?></td>
<td><div style="background-color:#cdcdcd;width:<?= $count ?>in;"><?= $count ?></div></td>
    </tr>
  <? endforeach ?>

<? endforeach ?>
</table>
  

