<? /* display non-facet search terms for the current search results */ ?>
<? if (isset($this->url_params['query']) || isset($this->search_fields)): ?>
  <p><b>Search terms</b></p>
  <ul>
    <? if (isset($this->url_params['query'])): ?>
      <li><?= $this->url_params['query'] ?></li>
    <? endif ?>
    <? if ($this->url_params['unembargoed']): /* special advanced search filter */ ?>
      <li>full text available</li>
    <? endif ?>
    <? foreach ($this->search_fields as $field): ?>
      <? if (isset($this->url_params[$field])): ?>
	 <? $label = ($field == "tableOfContents") ? "Table of Contents" : ucfirst($field) ?>
	 <li><b><?= $label ?>: </b> <?= $this->url_params[$field] ?></li>
      <? endif ?>
    <? endforeach ?>
  </ul>		
  <hr/>
 <? endif ?>	 
    
