<? if (isset($this->etdSet->facets) && $this->etdSet->facets->hasValues()): ?>
  <style type="text/css">div.content {padding-right:215px; }</style>
 <? /* FIXME.. better way to do this? (set margin for main div to leave room for faces) */ ?>

<? /* assumes view->facets is set with output from Solr */ ?>
<div class="facets">

    <?=  $this->render('search/_terms.phtml'); ?>

     <? /* display filters currently in effect and allow them to be removed */ ?>
     <? if (isset($this->filters) && count($this->filters)): ?>
        <p><b>Remove filters:</b></p>
	<ul>
	  <? foreach ($this->filters as $facet => $term): ?>
	   <? /* build up url for this page _without_ this facet */ ?>
	   <? $url_opts = array_merge(array('controller' => $this->controller, 'action' => $this->action), $this->url_params); ?>
<?		foreach ($this->filters as $f => $t) if ($f != $facet) $url_opts[$f] = $t; ?>
	   <? if ($facet == "program")	// convert program id to text label
		$term = $this->programHierarchy->findLabelbyId($term) ?>
	    <li><a href="<?= $this->url($url_opts, '', true) ?>"><?= $term ?></a></li>
          <? endforeach ?>
	</ul>
        <hr/> 
    <? endif ?>
   
   <b>Filter your results:</b>
   
     <? foreach (array("status", "year", "subject", "advisor", "committee", "program", "author", "keyword", "subfield", "document_type") as $facet): ?>
    <? if ($this->browse_mode == "committee" && $facet == "advisor") continue; ?>
    <? if ($this->browse_mode == "researchfield" && $facet == "subject") continue; ?>
     <? if (isset($this->etdSet->facets->$facet) && count($this->etdSet->facets->$facet)
	    && !isset($this->filters[$facet]) && $this->browse_mode != $facet): ?>
   <p class="label">
      <? if ($facet == "advisor"): ?>Committee Chair
      <? elseif ($facet == "document_type"): ?>Document type
      <? else: ?><?= ucfirst($facet) ?>
      <? endif ?>		      
   </p>
	  <ul>
  	    <? foreach ($this->etdSet->facets->$facet as $label => $count): ?>
  	      <li>
<? /* include url params when generating links (needed for facets on search query) */ ?>
<? $url_opts = array_merge(array('controller' => $this->controller, 'action' => $this->action), $this->url_params); ?>
     <? $url_opts[$facet] = $label; ?>
     <? if ($facet == "program")	// convert program id to text label
	  $label = $this->programHierarchy->findLabelbyId($label); ?>
  	        <a href="<?= $this->url($url_opts) ?>"><?= $label ?></a>
	       (<?= $count ?>)</li>
 	    <? endforeach ?>
	  </ul>
       <? endif ?>
    <? endforeach ?>
  
</div>
<? endif ?>