<?
/*print "<br>";
print $this->curDate;
print "<br>";
print $this->curStart;
print "<br>";
print $this->curEnd;
print "<br>";
print_r ($this->options);
 */
?>
<h1>Graduation Report Download</h1>

<p>
    Select the desired academic year and click Download to create Graduation Report
</p>

<form name="gradData" action="" method="post">
    <table>
        <tr>
            <td>
                Academic Year: <?=$this->formSelect("academicYear", null, null, $this->options) ?>
            </td>
        </tr>
        <tr>
        <td>
            <?= $this->formSubmit("download", "Download >", Array("class" => "submitlink")); ?>
        </td>

        </tr>
    </table>

</form>
