<H1>Available Reports</H1>
<ul>
  <li><a href="<?= $this->url(array("controller" => "manage", "action" => "report"), '', true); ?>">View Statistics Report</a></li>
  <li><a href="<?= $this->url(array("controller" => "report", "action" => "commencement"), '', true); ?>">Commencement Report</a></li>
  <li><a href="<?= $this->url(array("controller" => "report", "action" => "grad-data"), '', true); ?>">Graduate School Academic Year Report</a></li>
</ul>