<? /* statistics by country */ ?>
    <tr>
    <td colspan="4" class="caption">Views by country <? /* $date? */?></td>
    </tr>
    <? if (count($this->country) == 0): ?>
     <tr>
      <td colspan="4">No views during this period</td>
     </tr>
    <? else: ?>
	<? foreach ($this->country as $country): ?>
	<tr>
	  <td>
	     <img src="<?= $this->linkTo("images/flags/" . $country['country'] . ".gif") ?>" style="border:1px solid black"/>
	     <?/* FIXME: should be image helper, but it thinks these images don't exist */ ?>
	     
	     <?= $this->countries->$country['country'] /* FIXME: country name instead of code */ ?>
 	  </td>
	  <td class="count abstract"><?= $country['abstract'] ?></td>
	  <td class="count download"><?= $country['file'] ?></td>
	  <td>
  	       <div class="abstractviews" style="width:<?= $country['abstract'] ?>px">
		<?= $country['abstract'] ?></div>
  	       <div class="downloads"
	    style="width:<?= $country['file'] ?>px">
	     <?= $country['file'] ?></div>
	  </td>
	</tr>								
       <? endforeach ?>
   <? endif ?>
