<h1>Edit File Information</h1>
<p>You may edit author and file description below.  If information is satisfactory, click on save to proceed.</p>

<?=  $this->render('edit/_xforms_key.phtml'); ?>

<?= $this->xformText("Title", "dc:title"); ?> <br/>
<?= $this->xformText("Author", "dc:creator"); ?> <br/>
<?= $this->xformTextarea("Description", "dc:description"); ?> <br/>

 <xf:select1 ref="dc:type">
   <xf:label>Type of resource</xf:label>
   <xf:itemset nodeset="instance('dcmitypes')/type">
     <xf:label ref="@display"/><xf:value ref="@value"/>
   </xf:itemset>
  </xf:select1>
 <br/>


<? /* these are set on upload and should not be editable by the user */ ?>
<?= $this->xformOutput("file type", "dc:format[contains(., '/')]"); ?>
	<?= $this->FiletypeIcon($this->etdfile->dc->mimetype) ?>
   	<br/>
<?= $this->xformOutput("pages", "dc:format[contains(., 'p.')]"); ?> <br/>
<?= $this->xformOutput("file size (in bytes)", "dc:format[not(contains(., '/')) and not(contains(., 'p.'))]"); ?>
	(<?= $this->readableSize($this->etdfile->dc->filesize) ?>)
	<br/>

	

 <xf:submit submission="submission">
<xf:label>Save</xf:label>
</xf:submit>

<? if ($this->env == 'development'): ?>
  <p id="status"></p>
<? endif ?>   
