<div id="news">
  <h2>News and Announcements</h2>

<p><b>ETD Program now accepting Emory College Honors Theses</b><br/>
Starting in spring 2009, Emory College seniors participating in the College
Honors Program may submit their honors theses to the ETD repository. Honors
Program students are submitting their theses on a voluntary basis this
semester but all Honors Program participants will use the ETD submission
process beginning in spring 2010.</p>
<p>For more information about the ETD Program and Honors theses, please contact
Erika Farr (<a href="mailto:elfarr@emory.edu">elfarr@emory.edu</a>).</p>


<p><b>Electronic Submission of Theses and Dissertations Now Required </b><br/>
All students completing their degree programs in the Emory Graduate School must now
submit their theses and dissertations electronically. <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Detailed instructions on submitting your ETD</a> are available on the site. Please contact 
the ETD staff using the <a href="<?= $this->url(array("controller" => "help", "action" => "index"), '', true); ?>">online help form</a>
if you need assistance.  Any questions on graduation 
requirements should be referred to the Graduate School.</p>
 
<p style="margin:0px"><b>Submission Form for All ETD Program Participants </b><br>
All students depositing their thesis or dissertation must complete the ETD Submission form:
<ul style="margin:0px">
 <li><a href="<?= $this->linkTo("documents/Graduate_Submission_Form.doc") ?>">Graduate
   	School submission form</a></li>
 <li><a href="<?= $this->linkTo("documents/Honors_Submission_Form.doc") ?>">College
   	Honors Program submission form</a></li>
</ul>
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>


</div>
