<div id="news">
  <h2>News and Announcements</h2>
   
<p><b>Electronic Submission of Theses and Dissertations Now Required </b><br/>
All students completing their degree programs in the Emory Graduate School must now
submit their theses and dissertations electronically. <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Detailed instructions on submitting your ETD</a> are available on the site. Please contact 
the ETD staff using the <a href="<?= $this->url(array("controller" => "help", "action" => "index"), '', true); ?>">online help form</a>
if you need assistance.  Any questions on graduation 
requirements should be referred to the Graduate School.</p>
 
<p><b>Submission Form for All ETD Program Participants </b><br>
 All students depositing their thesis or dissertation must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>


</div>
