<?=  $this->render('email/_debug.phtml'); ?>
<p>Dear <?= $this->etd->authorInfo->mads->name ?>,</p>

<p>You were notified on <?= $this->etd->mods->embargo_notice ?> that
your ETD access restriction was expiring.  We have not been informed
that you wish to extend your access restriction period and therefore
your dissertation or thesis is now available in full text
form in our repository.</p>

<p>Your dissertation or thesis
can be accessed in the Emory University ETD Repository at:
<a href="<?= $this->etd->ark() ?>"><?= $this->etd->ark() ?></a></p>


<p>
If you need your record to remain restricted/embargoed, please contact
 <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
 or reply to this email with your request.
</p>


<p>
<b>FOR AUTHORS WHO ALSO SUBMITTED TO PROQUEST:</b><br>
To extend your access restriction/embargo in the ProQuest database, you will need to contact ProQuest's Author Relations department to request they extend your embargo. You can reach them at 1-800-521-0600 ext. 77020 or via email at
<a href="mailto:disspub@proquest.com">disspub@proquest.com</a>.
</p>
