<h1>Access Statistics</h1>

<p>Cumulative statistics for all records.</p>

<ul>
  <li><a href="<?= $this->url(array("action" => "country")) ?>">by Country</a></li>
  <li><a href="<?= $this->url(array("action" => "monthly")) ?>">by Month/Year</a></li>
</ul>

<? if ($this->acl->isAllowed($this->current_user, "statistics", "manage")): ?>
   <p style="padding-top:25px">Statistics script was last run on <?= $this->lastrun->date ?>, inserted <?= $this->lastrun->inserted ?> new entries.
   Processing took <?= strtotime($this->lastrun->end_time,0) - strtotime($this->lastrun->start_time,0) ?> seconds.</p>
<? endif ?>