<ul>
<? if (!empty($this->faculty)) : ?>
  <? foreach ($this->faculty as $member) : ?>
    <li id="<?= $member->netid ?>">
      <span class="dept">(<?= htmlentities($member->department) ?>)</span>
       <span class="value"><?= $member->lastname ?>, <?= $member->name ?> <?//= $member->firstname ?> <?//= $member->middlename ?></span>
    </li>
  <? endforeach ?>
<? else : ?>
  <li>No matches</li>
<? endif ?>
</ul>