   <xf:group ref="mads:address">
     <xf:label>address</xf:label>
     <xf:repeat id="repeat-street" nodeset="mads:street"> 
        <?= $this->xformText("street", "."); ?> <br/>
     </xf:repeat>

     <xf:trigger id="street-add">
       <xf:label>Add</xf:label>
        <xf:action ev:event="DOMActivate">
          <xf:insert ref="mads:street" at="last()" position="after"/> 
          <xf:setvalue ref="mads:street[last()]" value="''"/>
        </xf:action>
      </xf:trigger>
      
      <xf:trigger>
        <xf:label>Remove</xf:label>
        <xf:delete ev:event="DOMActivate" nodeset="mads:street" at="last()"/>
      </xf:trigger>
      <br/>

     <?= $this->xformText("city", "mads:city"); ?> <br/>
     <?= $this->xformText("state", "mads:state"); ?>
       <xf:select1 ref="mads:country">
       <xf:label>country</xf:label>
       <xf:itemset nodeset="instance('countries')/country">
         <xf:label ref="."/><xf:value ref="."/>
       </xf:itemset>
    </xf:select1>

     <?= $this->xformText("postcode", "mads:postcode"); ?>
  </xf:group>
 <br/>
