   <xf:group ref="mads:address">
     <xf:label>address</xf:label>
     <?= $this->xformText("street", "mads:street"); ?> <br/>
     <?= $this->xformText("city", "mads:city"); ?> <br/>
     <?= $this->xformText("state", "mads:state"); ?>
     <?= $this->xformText("country", "mads:country"); ?>
     <?= $this->xformText("postcode", "mads:postcode"); ?>
  </xf:group>
 <br/>
  <?= $this->xformText("phone", "mads:phone"); ?> <br/>
