<h1>user information</h1>
<? $user = $this->user->mads; ?>

<?= $user->name->first ?> <?= $user->name->last ?>

   <? if (isset($user->current)): ?>
 <p><u>current contact information:</u></p>
    <p><b>address</b>
    <? if ($user->current->date): ?> (valid as of <?= $user->current->date ?>)<? endif ?>
    </p>
    <? $this->address = $user->current->address; ?>
    <?= $this->render("user/address.phtml"); ?>

    <p><b>phone:</b> <?= $user->current->phone ?></p>
<p><b>email:</b> <?= $user->current->email ?>
<? endif ?>

<? if (isset($user->permanent)): ?>
  <p><u>permanent contact information</u></p>
  <p><b>address</b> (valid as of <?= $user->permanent->date ?>)</p>
  <? $this->address = $user->permanent->address; ?>
  <?= $this->render("user/address.phtml"); ?>

<p><b>email:</b> <?= $user->permanent->email ?>
</p>
<p><b>phone:</b> <?= $user->permanent->phone ?></p>
<? endif ?>

<p><b>netid:</b> <?= $user->netid ?></p>


<p><a href="<?= $this->url(array("controller" => "user",
		 "action" => "edit", "pid" => $this->user->pid), null, true) ?>">edit</a></p>