<h1>Processing PDF</h1>

<? if (count($this->errors)): ?>
 <p>There was an error processing the PDF.</p>
<? endif ?>   
<?= $this->render("submission/_processpdf_errs.phtml"); ?>

<? if($this->etd_info): ?>
<p>information extracted from pdf</p>
<div>
  <? if (isset($this->etd_info['title'])): ?>
    <b>Title:</b> <?= $this->etd_info['title'] ?><br/>
  <? endif ?>      
  <? if (isset($this->etd_info['keywords'])): ?>     
    <b>Keywords:</b> <?= implode("; ", $this->etd_info['keywords']) ?><br/>
  <? endif ?>     
  <? if (isset($this->etd_info['abstract'])): ?>        
    <b>Abstract:</b> <div><?= $this->etd_info['abstract'] ?></div>
  <? endif ?>     
  <? if (isset($this->etd_info['toc'])): ?>     
    <b>Table of Contents:</b> <div><?= $this->etd_info['toc'] ?></div>
  <? endif ?>   
<? endif ?>
     
<? if (isset($this->department)): ?>
  <p><b>Department match from program list:</b> <?= $this->department ?>
<? endif ?>   

<? if ($this->env == 'development'): ?>
 <hr/>     
 <p>More details:</p>
  <ul id="log">
     <? foreach ($this->log as $logline): ?>
       <li><?= $logline ?></li>
     <? endforeach ?>
  </ul>
<? endif ?>

     
<hr>

<? if($this->etd_info): ?>
  <p>raw content pulled from pdf</p>
  <pre>
     <?= htmlentities(print_r($this->etd_info, true)); ?>
  </pre>
<? endif ?>  




