<?= $this->javascript("jquery.local.js"); ?>
<noscript style="color:red">The submission process requires that you enable Javascript.</noscript>

<p>Please answer the following questions before you begin creating your record.</p>

<? if ($this->form_errors): ?>
<div id="messages">
  <? /* display appropriate detailed error message for any missing required fields */ ?>
  <? foreach ($this->form_errors as $err): ?>
    <p class="error">
      <? switch ($err): 
        case 'copyright': ?>You must answer about copyrighted materials.<? break ?>
        <? case 'copyright_permission': ?>Because you have indicated that you have
            included copyrighted materials, you must answer whether or not you have obtained permissions.<? break ?>
        <? case 'patent': ?>You must answer whether or not your work may warrant patenting.<? break ?>
        <? case 'embargo': ?>You must answer whether or not you are requesting an access restriction.<? break ?>
        <? case 'embargo_abs_toc': ?>Because you have indicated you are requesting an access restriction, you must answer about your abstract or table of contents.<? break ?>
        <? case 'title': ?>A title is required to create your initial record.<? break ?>
      <? endswitch ?>
    </p>
  <? endforeach ?>
</div>
<? endif ?>

<form name="submission" id="submission" method="post" 
   action="<?= $this->url(array("action" => "start"))?>"> 

<ol id="screening-questions">
 <li><p>Have you included any copyrighted material in your thesis or dissertation?</p>
    <?= $this->formRadio('copyright', $this->answers['copyright'], 
        array('class' => 'required-field'), $this->yes_no) ?>
     <? /* copyright details: display if answer to copyright question is YES */ ?>
    <div id="copyright_yes"> 
      <p>1b. Have you obtained permission to include that copyrighted material in your thesis or dissertation?</p>
      <?= $this->formRadio("copyright_permission", $this->answers["copyright_permission"], array(),
			      $this->yes_no) ?>
    <? /* copyright permission details */ ?>
    <div id="copyright_perms_no">  <? /*  Show if answered NO to permissions */ ?> 
        <p>You must obtain these permissions before you can continue with the submission process.
    Contact Lisa Macklin (<a href="mailto:lisa.macklin@emory.edu">lisa.macklin@emory.edu</a>) or
    Heather Williams (<a href="mailto:hrwilli@emory.edu">hrwilli@emory.edu</a>) if you have any questions.</p>
      </div>
     <div id="copyright_perms_yes"> <? /*  Show if answered YES to permissions */ ?> 
    <p>Complete Part 4 of the Submission Form.</p>
    </div>
 </li>

 <li><p>Does your thesis or dissertation disclose or describe any inventions or discoveries that could potentially have commercial application and therefore warrant patenting?  (If you and/or your faculty advisor(s) have any questions about making this determination, please contact the Emory Office of Technology Transfer at <a href="mailto:ott-web@emory.edu">ott-web@emory.edu</a>).</p>
    <?= $this->formRadio("patent", $this->answers["patent"],
       array('class' => 'required-field'), $this->yes_no) ?>
  <div id="patent_yes">   <? /* display only if yes to patent */ ?>	 
     <p>The technology transfer and patenting process necessitates further conversation with ETD administrators before you can continue with the ETD submission process.  Please contact ETD Help at <a href="mailto:etd-admin@listerv.cc.emory.edu">etd-admin@listerv.cc.emory.edu</a> or call (404)727-5301.</p>
     <? /* TODO: use configured email; remove phone number? */ ?>
  </div>
</li>

<li><p>Are you requesting an access restriction (see Part 3 below) for your thesis or dissertation?</p>
        <?= $this->formRadio("embargo", ($this->answers["embargo"] == null ? null : $this->answers["embargo"]),
			     array('class' => 'required-field'), $this->yes_no) ?>
    <div id="embargo_yes">    <? /* display if answer to embargo is yes */ ?>
     <p>Please indicate how long you intend to restrict access to your dissertation or thesis on the Submission Form. You will also need to indicate your request for an access restriction during the submission process itself.
     </p>

    <p>3b. Should your abstract and/or table of contents be included in the access restriction?</p>
        <?= $this->formRadio("embargo_abs_toc", ($this->answers["embargo_abs_toc"] == null ? null : $this->answers["embargo_abs_toc"]), array('class' => 'required-field'), $this->yes_no) ?>
    <div id="embargo_abs_toc_yes">  <? /* display only if restricting abstract/toc */ ?>
      <p>You will need to restrict access to your abstract and/or your table of contents once you have uploaded you document to the ETD repository. If you have already submitted your document to the ETD repository, you can log in and make appropriate changes to your record while it is in draft form.</p>
    </div>
   </div>
</li>

<li><p>Enter your thesis or dissertation title to begin the submission process.</p></li>
      
</ol>

<!-- TODO: label needs to be bold, input field needs to be much longer -->
<div>
  <label for="etd_title" class="etd_title">Thesis or Dissertation Title</label>
  <?= $this->formTextarea("etd_title", $this->answers['title'], array("class" => "required-field")); ?> 
</div>

  <?= $this->formSubmit("Begin", "Begin >", array("class" => "button", "style" => "margin-left:10px")); ?>
  <span id="processing" style="display:none">Processing ... <span class="note">(this may take a moment)</span></span>
</form>

 <hr/>

 <p>After submitting your PDF, the submission page (pictured below) will appear, 
 where you will be able to edit the information harvested from your PDF, and enter the remainder of the required data
by using the "edit" links.  Green check marks <?= $ok ?> will appear in the Submission Status box 
 next to each completed section (with red <?= $incomplete?>'s next to incomplete 
 sections).  Once you have completed all the sections, a "Review and Submit" link 
 will appear below the submission status box.</p> 

<img src="<?= $this->linkTo("images/submit_preview.jpg") ?>"/>


<script>          
var $j = jQuery.noConflict(); 
<? /* avoid conflict with prototype/scriptaculous while ETD has both */ ?>

$j(document).ready(function() {
  // configure divs to be conditionally displayed based on answers
  $j('input[name=copyright]').conditionalDisplay({
    conditions: { yes: '#copyright_yes' }
  });
  $j('input[name=copyright_permission]').conditionalDisplay({
    conditions: { yes: '#copyright_perms_yes', no: '#copyright_perms_no' }
  });  
  $j('input[name=patent]').conditionalDisplay({
    conditions: { yes: '#patent_yes' }
  });  
  $j('input[name=embargo]').conditionalDisplay({
    conditions: { yes: '#embargo_yes' }
  });  
  $j('input[name=embargo_abs_toc]').conditionalDisplay({
    conditions: { yes: '#embargo_abs_toc_yes' }
  });  

   // trigger change for all radio inputs to show/hide subsections as appropriate
   // based on initial form values
   $j("input:radio").change();

   //validate required or conditionally required fields on the form
   $j('#submission').validate({
      rules: {
        "copyright_permission": {
          required: "#copyright-yes:checked"
        },
        "embargo_abs_toc" : {
          required: "#embargo-yes:checked"
        }
      },
      errorPlacement: function(error, element) {
        // custom error placement for yes/no radio inputs
        // zend framework view helper outputs input inside a label;
        // if there is a label following, put the error after it; otherwise, after element.
        var after = element.parent().nextAll('label');
        error.insertAfter(after.length > 0 ? after : element);
      },
      submitHandler: function(form) {
        // on valid submit, disable submit button (prevent double/multi-click creating multiple records)
        $j(form).find('input[type=submit]').attr('disabled', true);
        $j('#processing').show();  // display indicator that something is happening
        $j(form).submit();  // now actually submit the form
      }
    });
    jQuery.validator.addClassRules("required-field", {required: true});

});                                       
</script>