<p>Congratulations!  You have successfully submitted your ETD to Emory's
repository.</p>

<p>Remember to print the PDF version of your dissertation and submit a paper
copy to the Graduate School for the Dean's review.</p>

<p>You will receive an e-mail notification confirming whether or not
your dissertation has been approved by the Graduate School.  You may
check the status of your submission by viewing your record in <a
href="<?= $this->url(array('controller' => 'browse', 'action' => 'my'), '', true) ?>">My ETDs</a>.
Your submission's status is
listed at the top of the page and the details on approval by the
Graduate School will appear in the History section of the record.</p>
