<? /* auto-completer for author names; uses author facet for
      completion; submitting the form searches for unpublished records
      where the selected name is listed as author
   */ ?>

<?= $this->javascript("projax/js/prototype.js"); ?>
<?= $this->javascript("projax/js/scriptaculous.js"); ?>
<?
include("projax/projax.php");
$projax = new Projax();
$ajaxopts = array("url" => $this->url(array("controller" => "search", "action" => "suggestor",
					    "field" => "author_facet", "mode" => "unpublished",
					    "show_count" => "no"), "", true),
		  "indicator" => "loading", "select" => "value", "with" => "'&query='+element.value");
$inputopts = array("size" => "55", "autocomplete" => "off");
?>

<div id="quicksearch">
  <p>Search by author (Last name, First):</p>
  <form name="quicksearch"
     action="<?= $this->url(array("controller" => "search", "action" => "results"), '', true)?>">
    <?=  $projax->text_field_with_auto_complete('author', $inputopts, $ajaxopts); ?>
    <span id="loading" style="display:none;"> Searching...</span>
    
    <?= $this->formHidden("status", "unpublished"); ?>
    <?= $this->formSubmit("Go", "Go >", array("class" => "submitlink")); ?>
  </form>
</div>