<?/* left side navigation */?>
<div id="sidenav">

   <? /* fixme: needs a check if user is authorized to submit */ ?>
   <p><b><a
href="<?= $this->url(array("controller" => "submission", "action" => "start"), "", true); ?>">Submit &gt;</a></b>
<font color="red">(beta)</font>
</p>


<div class="section">
  <p><a href="doc.php?id=about">About Us</a></p>
  <p><a href="doc.php?id=faq">Frequently Asked Questions</a></p>
  <p><a href="doc.php?id=faq#help" class="help">ETD Help</a></p>
  <p><a href="doc.php?id=policies">Policies and Procedures</a></p>
  <p><a href="doc.php?id=ip">Intellectual Property</a></p>
</div>

Browse by:
<? $this->browse_class = 'browse'; ?>
<?=  $this->render('browse/_categories.phtml'); ?>

<?=  $this->render('_proquest.phtml'); ?>


<div class="section">
<p><a href="http://www.emory.edu/GSOAS/">Emory Graduate School</a></p>

<p><a href="http://www.college.emory.edu/">Emory College</a></p>

<p><a href="http://www.emory.edu/libraries.cfm">Emory Libraries</a></p>
</div>

</div>

