<?
// where should this happen? (should get user name instead of login...)
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) { $identity = $auth->getIdentity(); }

// TEMPORARY - until we get 
$baseurl = "/~rsutton/etd/";

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:xf="http://www.w3.org/2002/xforms"
  xmlns:ev="http://www.w3.org/2001/xml-events"
  xmlns:v="http://www.w3.org/2001/vcard-rdf/3.0#"
  xmlns:mods="http://www.loc.gov/mods/v3"
  xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <title>ETD08 : <?= $this->escape($this->title) ?></title>
  <link rel="stylesheet" href="http://wilson.library.emory.edu/~rsutton/etds/css/etd.css" type="text/css"/>
  <?= $this->render('dc_header.phtml'); ?>

  <? if ($this->xforms): ?>
       <?= $this->render('xforms_head.phtml'); ?>
  <? endif ?>       
</head>
<body>

<div id="header">
  <div id="emory">
	<a href="http://www.emory.edu"><img
	    src="http://wilson.library.emory.edu/~rsutton/etds/images/emory.gif" alt="EMORY" title="EMORY"/></a>
      </div>
<div id="title"><a href="<?//= $this->url(array(), '', true) ?>">Electronic Theses and Dissertations</a> (ETD08)</div>

  <div id="photo">
	<img src="http://wilson.library.emory.edu/~rsutton/etds/images/woodruff-path.jpg"/> 
<p>Welcome to Emory University's Electronic Thesis and Dissertation
	  repository.</p>
      </div>
</div>


<div id="login">
 <div class="text">	<!-- FIXME: get rid of extra div (holdover from fez) -->

 <? if (isset($identity)): ?>
   <b>Welcome, <?= $identity ?></b>

   <ul class="horizontal">
      <li class="first">
         <a title="logout"
		href="<?= $this->url(array("controller" => "auth", "action" => "logout"), "", true)?>"><b>Logout &gt;</b></a>

	    </li>

            <? /* if $isAdministrator */ ?>
            <li><a href="<?= $this->url(array("controller" => "admin"), "", true)?>">Admin</a></li>

      	    <li><a title="preferences" href="">Preferences</a></li>

            <li><a href="">My ETDs</a></li>

            <li><a href="docs/id/faq#help">Help</a></li>

 <? else: ?>
  Emory Login: 
  <form name="login" method="post"
    action="<?= $this->url(array("controller" => "auth", "action" => "login"), "", true)?>">
  <?= $this->formText("login[username]", ""); ?>
  <?= $this->formPassword("login[password]", "", array("size" => 32)); ?>
  <input type="submit button" class="submitlink" name="Submit" value="Login &gt;"/>
</form>	

 <ul class="horizontal">
   <li><a href="" class="help">Why Login?</a></li>
 </ul>

 <? endif ?>
 </div>
</div>

<div id="navbar">
  <div id="etdhome"><a href="<?= $baseurl?>">ETD HOME</a></div>
  <?=  $this->render('navbar-curve.phtml'); ?>
</div>

<?=  $this->render('sidenav.phtml'); ?>

<div class="content">

  <?= $this->content ?>


</div> <!-- end content div -->

<div id="footer">
 <a
    href="http://www.emory.edu/copyright.cfm">&copy; 2007 Emory
    University.</a> 
   Version Zend-0.1 updated 8/07. 
 <a href="doc.php?id=ip">Rights and Privileges</a>
</div>

</body>
</html>
