<? if (! in_array($this->browserInfo->parent, $this->supported_browsers)
       && ! preg_match("|Firefox/3\.|", $_SERVER["HTTP_USER_AGENT"])): ?>
<p class="warning">
   <span id="exclamation">!</span>
   Your browser
   <? if ($this->browserInfo->browser != "Default Browser" &&
	  $this->browserInfo->majorver != 0):  /* if browser not detected, don't display */ ?>
     (<?= $this->browserInfo->browser ?> <?= $this->browserInfo->majorver ?>) <? endif ?>
   is currently not supported for the submission process.  <br/>
   Please use one of the following:
   <?= implode(', ', $this->supported_browsers) ?>
   <? /* special check for MSIE 8, which will only work in compatibility view */
      if (preg_match("|MSIE 8.0|", $_SERVER["HTTP_USER_AGENT"])): ?> 
    <br/>You appear to be using <b>Internet Explorer 8</b>.  Please switch to compatibility view.
    <? endif ?>					
</p>
<? endif ?>

<noscript style="color:red">The submission process requires that you enable Javascript.</noscript>
<script type="text/javascript">
/* get radio button value by name */ 
function radioValue(name) {
   return Form.getInputs("submission","radio", name).find(function(radio) { return radio.checked; }).value;
}
/* check if one radio option is selected */
function radioSet(name) {
  var checked = false;
  Form.getInputs("submission","radio", name).each(function(radio) { if (radio.checked) checked = true; });
  return checked;
}   

/* show/hide element by id based on a parameter */
function showbyid(id, show) {
  if (show) $(id).show();
  else $(id).hide();
}
/** if value is true, show the first element and hide the second; otherwise, do the reverse
    -- second element is optional
 */ 
function showif(value, iftrue, ifnot) {
  if (value) {
    $(iftrue).show();
    if (ifnot) $(ifnot).hide();
  } else {
    $(iftrue).hide();
    if(ifnot) $(ifnot).show();
  }
}

/*Useed to validate all questions are answerd  before submitting PDF */
function validate() {
  var err = false;
  $('form_errors').update("");
  // answer to copyright is required
  if (! radioSet("copyright")) {
    $('form_errors').appendChild(document.createTextNode("Answer 1 \"copyright\" is required"));
    $('form_errors').appendChild(document.createElement("br"));
    err = true;
  } else if (radioValue("copyright") == 1 && ! radioSet("copyright_permission")) {
    // if answer to copyright is yes, answer about permissions is required
    $('form_errors').appendChild(document.createTextNode("Answer 1b \"copyright permissions\" is required"));
    $('form_errors').appendChild(document.createElement("br"));
      err = true;
  }
  // answer to patent is required
  if (! radioSet("patent")) {
    $('form_errors').appendChild(document.createTextNode("Answer 2 \"patent\" is required"));
    $('form_errors').appendChild(document.createElement("br"));
    err = true;
  }

  // answer to embargo question is required
  if (! radioSet("embargo")) {
    $('form_errors').appendChild(document.createTextNode("Answer 3 \"embargo\" is required"));
    $('form_errors').appendChild(document.createElement("br"));
    err = true;
  } else if (radioValue("embargo") == 1 && !radioSet("embargo_abs_toc")) {
    $('form_errors').appendChild(document.createTextNode("Answer 3b \"embargo level\" is required"));
    $('form_errors').appendChild(document.createElement("br"));
    err = true;
  }

  if (err) $("submit").hide();
  else  $("submit").show();

}

</script>
    
<? //DEBUG SECTION
print "ANSERS:";
print_r($this->answers);
?>

<p>Welcome!</p>
    <p>Please answer the follow questions before you submit your document.</p>

<form name="submission" id="submission" method="post" enctype="multipart/form-data"
    action="<?= $this->url(array("action" => "processpdf"))?>">

<ol>
 <li><p>Have you included any copyrighted material in your thesis or dissertation?</p>
    <?= $this->formRadio("copyright", null,
			 array("onClick" => "showif((radioValue('copyright')==1),'copyright_yes')"),
			 array(1 => "Yes", 0 => "No")) ?>

     <? /* copyright details: display if answered YES to copyright */ ?>
    <div id="copyright_yes" style="display:none">
      <p>1b. Have you obtained permission to include that copyrighted material in your thesis or dissertation?</p>
      <?= $this->formRadio("copyright_permission", null,
			   array("onClick" => "showif((radioValue('copyright_permission')==1), 'copyright_perms_yes', 'copyright_perms_no')"),
			 array(1 => "Yes", 0 => "No")) ?>
      <? /* copyright permission details */ ?>
    <div id="copyright_perms_no" style="display:none">  <? /* if answered NO to permissions */ ?> 
        <p>You must obtain these permissions before you can continue with the submission process.
    Contact Lisa Macklin (<a href="mailto:lisa.macklin@emory.edu">lisa.macklin@emory.edu</a>) or
    Heather Williams (<a href="mailto:hrwilli@emory.edu">hrwilli@emory.edu</a>) if you have any questions.</p>
      </div>
     <div id="copyright_perms_yes" style="display:none"> <? /* if answered YES to permissions */ ?> 
    <p>Complete Part 4 of the Submission Form and submit to the Graduate School (OR College/Candler?).</p>
    </div>
 </li>

 <li><p>Does your thesis or dissertation disclose or describe any inventions or discoveries that could potentially have commercial application and therefore warrant patenting?  (If you and/or your faculty advisor(s) have any questions about making this determination, please contact the Emory Office of Technology Transfer at <a href="mailto:ott-web@emory.edu">ott-web@emory.edu</a>).</p>
    <?= $this->formRadio("patent", null,
			 array("onClick" => "showif((radioValue('patent')==1),'patent_yes')"),
			 array(1 => "Yes", 0 => "No")) ?>
  <div id="patent_yes" style="display:none">   <? /* if yes to patent */ ?>	 
     <p>The technology transfer and patenting process necessitates further conversation with ETD administrators before you can continue with the ETD submission process.  Please contact Erika Farr (<a href="mailto:elfarr@emory.edu">elfarr@emory.edu</a>).</p>
  </div>
</li>

<li><p>Are you requesting an access restriction (see Part 3 below) for your thesis or dissertation?</p>
        <?= $this->formRadio("embargo", null,
			     array('onClick' => "showif(radioValue('embargo')==1, 'embargo_yes')"),
			     array(1 => "Yes", 0 => "No")) ?>
    <div id="embargo_yes" style="display:none">    <? /* if yes to embargo */ ?>
     <p>Please indicate how long you intend to restrict access to your dissertation or thesis on the Submission Form and submit it to the Graduate School. You will also need to indicate your request for an access restriction during the submission process itself.
     </p>

    <p>3b. Should your abstract and/or table of contents be included in the access restriction?</p>
        <?= $this->formRadio("embargo_abs_toc", null,
			     array("onClick" => "showif(radioValue('embargo_abs_toc')==1, 'embargo_abs_toc_yes')"),
			     array(1 => "Yes", 0 => "No")) ?>

    <div id="embargo_abs_toc_yes" style="display:none">  <? /* if restricting abs/toc */ ?>
      <p>You will need to restrict access to your abstract and/or your table of contents once you have uploaded you document to the ETD repository. If you have already submitted your document to the ETD repository, you can log in and make appropriate changes to your record while it is in draft form.</p>
    </div>
   </div>
</li>
      
</ol>

    <p><a onClick="validate()" class="button">Continue &gt;</a></p>
  <div id="form_errors" style="color:red">
  </div>

  <div id="submit" style="display:none">

  <p style="color:green">You are now ready to submit your thesis or dissertation to the ETD system.</p>
    
    <hr/>
    
    

<p>To begin the submission process, please upload the PDF of your
dissertation.  Click on "Browse" to locate your document and then
"Begin" to start the process.</p>


<p>Please note that the system will be scanning your PDF document and
extracting certain information from it.  As a result, it is important
that your PDF document follow the format for
<? if ($this->current_user->getRoleId() == "honors student"): ?>
theses given by the College Honors Program 
<? else: /* Grad School  */ ?>
theses and dissertations given by the Graduate School     
<? endif ?>					     
 so that the pages are in the proper order
(i.e., Circulation Agreement, Approval Sheet, Dissertation/Thesis
Abstract Cover Sheet, Abstract, etc.). </p>

<p>Any information automatically extracted from the PDF can be edited
later in the process, if necessary.</p>


<?//= $this->formHidden("MAX_FILE_SIZE", "3000000"); ?> 
  <p><b>Your PDF</b> <?= $this->formFile("pdf"); ?>
<?= $this->formSubmit("Begin", "Begin >", array("class" => "button", "style" => "margin-left:10px",
						"onClick" => "Element.show('processing')")); ?>

<span id="processing" style="display:none">Processing ... <span class="note">(this may take a moment)</span></span>
</p>
</form>

<? $ok = "<span style='color:green'>&#x2714;</span>"; // green check mark 
 $incomplete = "<span style='color:red'>&#x2717;</span>"; // red x
?>

 <hr/>

 <p>After submitting your PDF, the submission page (pictured below) will appear, 
 where you will be able to edit the information harvested from your PDF, and enter the remainder of the required data
by using the "edit" links.  Green check marks <?= $ok ?> will appear in the Submission Status box 
 next to each completed section (with red <?= $incomplete?>'s next to incomplete 
 sections).  Once you have completed all the sections, a "Review and Submit" link 
 will appear below the submission status box.</p> 

<img src="<?= $this->linkTo("images/submit_preview.jpg") ?>"/>


<? if ($this->env == "development"): ?>

<form name="submission" method="post" enctype="multipart/form-data"
    action="<?= $this->url(array("action" => "debugpdf"))?>">

   <p>Test information extracted from a PDF (development only)</p>

<?//= $this->formHidden("MAX_FILE_SIZE", "3000000"); ?> 
  <p><?= $this->formFile("pdf"); ?> <?= $this->formSubmit("Debug", "Debug >", array("class" => "submitlink", "style" => "padding-left:10px")); ?></p>

</form>
<? endif ?>