<?
// FIXME: move this somewhere else - make a function of etd object? getStatTotals / get Stats ?
$stats = new StatObject();
$pids = array();
$pids[] = $this->etd->pid;
foreach ($this->etd->pdfs as $pdf) $pids[] = $pdf->pid;
$mystats = $stats->count($pids);
?>
<div id="stats">
    <h2>Access Statistics</h2>
<p><?= $mystats['abstract'] ?> Abstract Views, <?= $mystats['file'] ?> File Downloads
  <a href="<?= $this->url(array('controller' => 'statistics', 'action' => 'record',
	'pid' => $this->etd->pid),'', true, false) ?>">Detailed Statistics</a>
  </p>
</div>
