<h1>About the web service: Indexdata (eulindexer)</h1>

<p>This php web service provides solr index configuration and data to 
<a target=_blank href="https://github.com/emory-libraries/eulindexer/blob/master/README.rst">eulindexer</a> 
that will deposit this data into a SOLR index.</p>
<p></p>
<p>Required parameters are:</p>
<ul>
  <li><i>default</i> - full index of all ETD objects that have a content model: "emory-control:ETD-1.0".<br/>
  <li><b><i>{PID}</i></b> - single solr index for individual pid.</li>
</ul>
<p>Response are in JSON format examples:</p>
<ul>
  <li><i>default</i> <pre>{"SOLR_URL":"http://dev11.library.emory.edu:9083/solr/etd","CONTENT_MODELS":["emory-control:ETD-1.0"]}</pre><br/>
  <li><b><i>{PID}</i></b> <pre>
  {"PID":"emory:9kqb1",
  "advisor":["Thomas, Alexander"],
  "advisor_id":["athom09"],
  "author":"Connard, Sari",
  "collection":"emory-control:ETD-Rollins-collection",
  "committee":["Anderson, Steven"],
  "committee_id":["scande3"],
  "contentModel":"emory-control:ETD-1.0",
  "date_embargoedUntil":"2012-02-09",
  "dateIssued":"20110831",
  "degree_level":"masters (MSPH) ",
  "degree_name":"MSPH",
  "document_type":"Master's Thesis",
  "embargo_duration":"6 months",
  "embargo_requested":"yes",
  "keywords":["test","indexdata"],
  "label":"Indexdata test restricted toc and abstract",
  "language":"English",
  "lastModified":"2011-08-09T19:07:19.841Z",
  "num_pages":"278",
  "ownerId":"sconna2",
  "partneringagencies":["CDC","International Non-governmental organization (e.g., CARE, Inc.)"],
  "program":"Biostatistics and Bioinformatics",
  "program_id":"rsph-bb",
  "registering_copyright":"no",
  "status":"published",
  "state":"Active",
  "subfield":"Biostatistics",
  "subfield_id":"rsph-bios",
  "subject":["Music","Biology, Bioinformatics","Biology, Biostatistics"],
  "title":"Indexdata test restricted toc and abstract",
  "year":"2011"}</pre></li>
</ul>

<hr/>
<p><small>2011-08-10</small></p>
