<form id="set_role" method="post"
   action="<?= $this->url(array('controller' => 'auth', 'action' => 'setrole'), '', true) ?>">
   Set role:
   <? $role_opts = array('' => '--',
          'admins' => array(
              "grad admin" => "Graduate School admin",
              "honors admin" => "College Honors admin",
              "candler admin" => "Candler admin",
              "rollins admin" => "Rollins admin",
              "nhwson admin" => "School of Nursing admin",
              "report viewer" => "report viewer",
              "admin" => "admin",
              "superuser" => "superuser",
          ),
          'students' => array(
              "grad student" => "Graduate student",
              "honors student" => "Honors student",
             "candler student" => "Candler student",
             "rollins student" => "Rollins student",
             "nhwson student" => "School of Nursing student",
          ),
          "faculty" => "faculty",
          'graduate department coordinator' => array(
            "coordinator:Chemistry" => "Chemistry",
            "coordinator:English" => "English",
            "coordinator:Religion" => "Religion",
            "coordinator:Graduate Institute of the Liberal Arts" => "ILA",
          )
   ); ?>
 <?= $this->formSelect("role", $this->current_user->role, array("id" => "user_role"), $role_opts); ?>
</form>
<span id="setrole_status" style="display:none"></span>
