<? if ($this->env == "production"):   	/* Google Analytics */ ?>
<? $role = isset($this->current_user) ? $this->current_user->role : 'guest'; ?>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    // Primary tracking ID (preferably the newer one above
    ga('create', 'UA-61756900-16', 'auto');
    ga('send', 'pageview');

    // Secondary tracking ID (older one that’s currently in place)
    ga('create', 'UA-3821577-1', {'name':'etd'});
    ga('etd.send', 'pageview', {
        'dimension1': '<?= $role ?>'
    });

    // Emory Main tracking ID

    ga('create', 'UA-43397511-1', {'name':'emory'});
    ga('emory.send', 'pageview');

</script>
<? endif ?>
