<h1>Summary by status</h1>

<ul>
<? foreach ($this->status_totals as $status => $total) : ?>
  <li><a href="<?= $this->url(array("action" => "list", "status" => $status))?>"><?= $status ?></a>
   (<?= $total ?>)</li>
<? endforeach ?>
</ul>

<?= $this->render("manage/_search.phtml") ?>

<hr/>

<ul>
  <li><a href="<?= $this->url(array('action' => 'embargoes')) ?>">Upcoming embargo expirations</a></li>
  <li><a href="<?= $this->url(array('action' => 'report')) ?>">View Reports</a></li>
<li><a href="<?= $this->url(array('action' => 'exportemails')) ?>">Export email addresses for approved records</a> (CSV file) </li>   

  <? if ($this->acl->isAllowed($this->current_user, "log", "view")): ?>
    <li><a href="<?= $this->url(array('action' => 'view-log')) ?>">View Log</a></li>
  <? endif ?>

  <? if ($this->acl->isAllowed($this->current_user, "programs", "edit") ||
	 $this->acl->isAllowed($this->current_user, "undergrad programs", "edit")): ?>
       <li><a href="<?= $this->url(array('controller' => 'program', 'action' => 'index')) ?>">View/edit Programs</a></li>
  <? endif ?>
</ul>
