<form name="reviseembargo" method="post"
   action="<?= $this->url(array("action" => "updateembargo"))?>">
<h1><?= $this->formLabel("message", "Updating the embargo"); ?>   </h1>

<p><b>Title:</b> <?= $this->etd->title() ?><br/>
<b>Author:</b> <?= $this->etd->author() ?><br/>
<br>
<b>The current embargo ending date is: <?= $this->etd->mods->embargo_end ?> </b>
</p>

<?= $this->formHidden("pid", $this->etd->pid()) ?>
<p>
<b>
<?= $this->formLabel("newdate", "New embargo ending date (YYYY-MM-DD): "); ?>   
<?= $this->formText("newdate", "", array("size" => 20)); ?>
</b>
</p>
  <?= $this->formSubmit("reviseembargo", "Revise"); ?>
</form>
