<div id="news">
  <h2>News and Announcements</h2>
   
<p><b>Intellectual Property Rights Workshops for Fall graduates</b><br/>

Will the nature of your thesis or dissertation raise copyright issues? Come to a workshop to learn about navigating copyright issues in a digital environment.
<ul>
<li>Thursday, October 23, noon to 1 pm, Woodruff Library Room 312. Focus on Humanities & Social Sciences.</li>
<li>Tuesday, October 28, 4 pm to 5 pm, Woodruff Library Room 312. General session.</li>
<li>Wednesday, October 29, noon to 1 pm, Rollins School of Public Health, Rita Rollins Room, 8th floor. Focus on Sciences.</li>
<li>Thursday, October 30, noon to 1 pm, Woodruff Library Room 312. Focus on permissions for images in Art History.</li>
</ul>
If you cannot attend a session with a focus related to your discipline, feel free to attend the general session. Each workshop will allow time for specific questions.<br/>
<a href="http://web.library.emory.edu/IP_rights/ETDCopyrightWorkshops.html">Find out more about the workshops</a>.<br/>

Please RSVP to Heather Williams at <a href="mailto:hrwilli@emory.edu">hrwilli@emory.edu</a> or 404.727.0127 so we know how many students to expect. If you have any questions, please contact Heather.</p>

<p><b>ETD Submission Workshops for Fall graduates</b><br/>

We will be holding workshops for students submitting their theses and dissertations on Monday, November 3 from 12:00-1:00 pm in Woodruff Library Room 314 and on Thursday, November 13 from 4:00 to 5:00 pm in Woodruff Library Room 312.<br/>
Feel free to drop by any time during these hours and we will assist you with your submission.</p>

<p><b>Electronic Submission of Theses and Dissertations Now Required </b><br/>
All students completing their degree programs in the Emory Graduate School must now
submit their theses and dissertations electronically. <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">
Detailed instructions on submitting your ETD</a> are available on the site. Please contact 
the ETD staff at <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
if you need assistance.  Any questions on graduation 
requirements should be referred to the Graduate School.</p>
 
<p><b>Submission Form for All ETD Program Participants </b><br>
 All students depositing their thesis or dissertation must complete the
<a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD Submission form</a>.
This form -- WHICH REQUIRES THE SIGNATURE OF YOUR ADVISOR --<br>
(1) gives the library permission to publish your dissertation on the web;<br>
(2) confirms access restrictions -- if any; and <br>
(3) certifies that you have secured rights to all content that you will be publishing.</p>


</div>
