<h1>edit user information</h1>

<xf:group nodeset="mads:authority/mads:name"> 
   <xf:label>name</xf:label> 

   <?= $this->xformText("last name", "mads:namePart[@type='family']"); ?>
   <?= $this->xformText("first name", "mads:namePart[@type='given']"); ?>
   <?= $this->xformText("birth year", "mads:namePart[@type='date']"); ?>
</xf:group> 
<br/>

<xf:group nodeset="mads:affiliation[mads:position != 'permanent resident']">

   <?= $this->xformText("degree", "mads:position"); ?><br/>
   <?= $this->xformText("department", "mads:organization"); ?><br/>

   <?=  $this->render('user/_mads_address.phtml'); ?>
   <?= $this->xformText("email", "mads:email"); ?> <br/>
   <?= $this->xformText("date valid", "mads:dateValid"); ?> <br/>
  
</xf:group>
<br/>

<xf:group nodeset="mads:affiliation[mads:position = 'permanent resident']">
   <xf:label>permanent address</xf:label>

   <?=  $this->render('user/_mads_address.phtml'); ?>
   <?= $this->xformText("non-emory email", "mads:email"); ?> <br/>

  <?= $this->xformText("date valid", "mads:dateValid"); ?> <br/>
  
</xf:group>
<br/>

<?= $this->xformOutput("netid", "mads:identifier[@type='netid']"); ?> <br/>

<xf:submit submission="submission">
  <xf:label>Save</xf:label>
</xf:submit>


<? if ($this->site_mode == 'development'): ?>
  <p id="status"></p>
<? endif ?>   

