<h1>edit user information</h1>

<p><i>probably should have some information here... this info collected for proquest,etc.</i></p>

<xf:group nodeset="mads:authority/mads:name"> 
  <xf:label>name</xf:label> 

   <?= $this->xformText("last", "mads:namePart[@type='family']"); ?>
   <?= $this->xformText("first and middle", "mads:namePart[@type='given']"); ?>
   <?//= $this->xformText("birth year", "mads:namePart[@type='date']"); ?>
</xf:group> 
<br/>

<xf:group nodeset="mads:affiliation[mads:position != 'permanent resident' or not(mads:position)]">

   <?//= $this->xformText("degree", "mads:position"); ?>
<?= $this->xformOutput("department", "mads:organization"); ?><br/>

   <xf:label>current address</xf:label>
   <?=  $this->render('user/_mads_address.phtml'); ?>
   <?= $this->xformText("email", "mads:email"); ?> <br/>
   <?= $this->xformText("date valid", "mads:dateValid"); ?> <br/>
  
</xf:group>

<hr/>

<xf:group nodeset="mads:affiliation[mads:position = 'permanent resident']">
   <xf:label>permanent address</xf:label>

   <?=  $this->render('user/_mads_address.phtml'); ?>
   <?= $this->xformOutput("phone", "mads:phone"); ?> <br/>

   <?= $this->xformText("non-emory email", "mads:email"); ?> <br/>

  <?= $this->xformText("date valid", "mads:dateValid"); ?> <br/>
  
</xf:group>
<br/>

<?= $this->xformOutput("netid", "mads:identifier[@type='netid']"); ?> <br/>

<xf:submit submission="submission">
  <xf:label>Save</xf:label>
</xf:submit>


<? if ($this->site_mode == 'development'): ?>
  <p id="status"></p>
<? endif ?>   

