<?=  $this->render('email/_debug.phtml'); ?>
<p>Dear <?= $this->etd->authorInfo->mads->name ?>,</p>

<p>You were notified on <?= $this->etd->mods->embargo_notice ?> that
your ETD access restriction was expiring.  We have not been informed
that you wish to extend your access restriction period and therefore
your dissertation or thesis is now available in full text
form in our repository.</p>

<p>Your dissertation or thesis
can be accessed in the Emory University ETD Repository at:
<a href="<?= $this->etd->ark() ?>"><?= $this->etd->ark() ?></a></p>


<p>If you have any questions regarding this matter, please contact us at
 <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>.</p>