<h1>Contact Information for <?= $this->authorInfo->mads->name->first ?> <?= $this->authorInfo->mads->name->last ?></h1>
<?=  $this->render('author-info/_view.phtml'); ?>

<? if ($this->acl->isAllowed($this->authorInfo->getUserRole($this->current_user), "authorInfo", "edit")): ?>
<p><a class="button" href="<?= $this->url(array("controller" => "authorInfo",
		 "action" => "edit", "pid" => $this->authorInfo->pid), null, true) ?>">edit</a></p>
<? endif ?>

<? $this->authorInfo->etd ?>
		 
<a class="button" href="<?= $this->url(array('controller' => 'view', 'action' => 'record',
	'pid' => $this->authorInfo->etd->pid), '', true, false)?>">return to record &gt;</a><br/>
