<?= $this->javascript("projax/js/prototype.js"); ?>
<?
 $etd = $this->etd; 
 $ok = "<span style='color:green'>&#x2714;</span>"; // green check mark 
 $incomplete = "<span style='color:red'>&#x2717;</span>"; // red x
?>
<h2>submission status</h2>
<? if (isset($etd->authorInfo)): ?>
   <? $authorInfo_url = $this->url(array("controller" => "user", "action" => "view",
					 "pid" => $etd->authorInfo->pid), '', true, false); ?>
   <? if ($etd->authorInfo->readyToSubmit()): ?>
	<?= $ok ?> <a href="<?= $authorInfo_url ?>">contact information</a><br/>
   <? else: ?>
	      <?= $incomplete ?> <a href="<?= $authorInfo_url ?>">contact information</a><br/>
        <ul id="user_missing" class="missing">
          <? foreach ($etd->authorInfo->checkRequired() as $missing): ?>
             <li><?= $missing ?></li>
          <? endforeach ?>
        </ul>
   <? endif ?>
 <? else: ?>
    <?= $incomplete ?> <a href="<?= $this->url(array('controller' => 'user', 'action' => 'new',
			'etd' => $etd->pid), '', true, false) ?> ">contact information</a><br/>
 <? endif ?>

  <? if ($readyToSubmit = $etd->mods->readyToSubmit()): ?>
    <?= $ok ?> thesis information<br/>
 <? else: ?> 
   <?= $incomplete; ?> thesis information
     <? /* display which required fields are missing, if any */   ?>
     <ul id="mods_missing" class="missing">
       <? if (count($etd->mods->checkRequired())): ?>
         <? foreach ($etd->mods->checkRequired() as $missing => $action): ?>
           <li><a href="<?= $this->url(array('controller' => 'edit', 'action' => $action)) ?>"><?= $missing ?></a>
           </li>
         <? endforeach ?>
      <? else : /* not ready to submit but no missing fields = xml is invalid */ ?>
        <li>XML invalid; please contact ETD Administrator</li>
      <? endif ?>       
     </ul>
  <? endif ?>       

  <?= $etd->hasPDF() ? $ok : $incomplete ?> PDF file<br/>
  <?if ($etd->hasOriginal()) : ?>
   <?= $ok ?> original file
  <? else : ?>
    <?= $incomplete ?> <a href="<?= $this->url(array('controller' => 'file', 'action' => 'add',
			'etd' => $etd->pid), '', true, false)?>">original file</a>
  <? endif ?> <br/>

<?/* FIXME: should this be grouped as rights/restrictions since they are edited on the same page? */ ?>
  <? $rights_url = $this->url(array('controller' => 'edit', 'action' => 'rights')); ?>

  <? if ($etd->mods->degree->name != "PhD" && $etd->mods->degree->name != ""): ?>
    <? /* since PQ submission is not optional for PhDs, hide this from them */ ?>
    <? $pq_submit = $etd->mods->hasSubmitToProquest() ?>
    <?= $pq_submit ? $ok : $incomplete; ?> <a href="<?= $rights_url ?>">send to ProQuest</a>
    <?= $pq_submit ? ": <b>" . $etd->mods->pq_submit . "</b>" : "";	/* display choice if set */ ?>
    <br/>
  <? endif ?>

  <? /* if not submitting to PQ and copyright is set, suppress (redundant) */ ?>
  <? $copyright = $etd->mods->hasCopyright(); ?>
  <? if ($etd->mods->submitToProquest() && $copyright): ?>
    <?= $copyright ? $ok : $incomplete; ?> <a href="<?= $rights_url ?>">copyright</a>
    <?= $copyright ? ": <b>" . $etd->mods->copyright . "</b>" : "";	/* display choice if set */ ?>
    <br/>
  <?endif ?>
  
  <? $embargo = $etd->mods->hasEmbargoRequest(); ?>
  <?= $embargo ? $ok : $incomplete; ?> <a href="<?= $rights_url ?>">embargo request</a>
  <?= $embargo ? ": <b>" . $etd->mods->embargo_request . "</b>" : "" ?>
  <br/>
  <?= $etd->mods->hasSubmissionAgreement() ? $ok : $incomplete; ?>
  	<a href="<?= $rights_url ?>">submission agreement</a><br/>

   <? if ($this->acl->isAllowed($this->role, $this->etd, "submit")
	  && $readyToSubmit): ?>
      <p><a class="button" href="<?= $this->url(array('controller' => 'submission',
				'action' => 'review')) ?>">review &amp; submit &gt;</a></p>
  <? endif ?>								     

</p>
