<?= $this->javascript("projax/js/prototype.js"); ?>
<?
 $etd = $this->etd; 
 $ok = "<span style='color:green'>&#x2714;</span>"; // green check mark 
 $incomplete = "<span style='color:red'>&#x2717;</span>"; // red x
$unknown = '<font color="blue">?</font>';
?>
<h2>submission status</h2>
<? /* FIXME: should not use current_user object anymore - need author info related to etd  */ ?>
 <? if ($etd->authorInfo): ?>
   <? $authorInfo_url = $this->url(array("controller" => "user", "action" => "view",
					 "pid" => $etd->authorInfo->pid), '', true); ?>
   <? if ($etd->authorInfo->readyToSubmit()): ?>
	<?= $ok ?> <a href="<?= $authorInfo_url ?>">contact information</a><br/>
   <? else: ?>
	      <?= $incomplete ?> <a href="<?= $authorInfo_url ?>">contact information</a><br/>
        <ul id="user_missing" class="missing">
          <? foreach ($etd->authorInfo->checkRequired() as $missing): ?>
             <li><?= $missing ?></li>
          <? endforeach ?>
        </ul>
   <? endif ?>
 <? else: ?>
    <? /* FIXME: this should link to creating a new user object ... */ ?>
    <?= $unknown ?> <a href="<?= $this->url(array('controller' => 'user', 'action' => 'new',
			'etd' => $etd->pid), '', true) ?> ">contact information</a><br/>
 <? endif ?>


  <? if ($etd->mods->readyToSubmit()): ?>
    <?= $ok ?> thesis information<br/>
 <? else: ?> 
  <?= $incomplete; ?> thesis information
    <? /* display which required fields are missing, if any */   ?>
   <ul id="mods_missing" class="missing">
     <? foreach ($etd->mods->checkRequired() as $missing => $action): ?>
      <li><a href="<?= $this->url(array('controller' => 'edit', 'action' => $action)) ?>"><?= $missing ?></a>
      </li>
     <? endforeach ?>
    </ul>
  <? endif ?>       

  <?= $etd->hasPDF() ? $ok : $incomplete ?> PDF file<br/>
  <?if ($etd->hasOriginal()) : ?>
   <?= $ok ?> original file
  <? else : ?>
    <?= $incomplete ?> <a href="<?= $this->url(array('controller' => 'file', 'action' => 'add',
			'etd' => $etd->pid), '', true)?>">original file</a>
  <? endif ?> <br/>

<?/* FIXME: should this be grouped as rights/restrictions since they are edited on the same page? */ ?>
  <? $rights_url = $this->url(array('controller' => 'edit', 'action' => 'rights')); ?>
  <? $copyright = $etd->mods->hasCopyright(); ?>
  <?= $copyright ? $ok : $incomplete; ?> <a href="<?= $rights_url ?>">copyright</a>
  <?= $copyright ? "(" . $etd->mods->copyright . ")" : "";	/* display choice if set */ ?>
  <br/>
  <? $embargo = $etd->mods->hasEmbargoRequest(); ?>
  <?= $embargo ? $ok : $incomplete; ?> <a href="<?= $rights_url ?>">embargo request</a>
  <?= $embargo ? "(" . $etd->mods->embargo_request . ")" : "" ?>
  <br/>
  <?= $etd->mods->hasSubmissionAgreement() ? $ok : $incomplete; ?>
  	<a href="<?= $rights_url ?>">submission agreement</a><br/>

<p><?= $unknown ?> = status unknown / not yet implemented</p>

   <? if ($this->acl->isAllowed($this->role, $this->etd, "submit")
	  && $etd->readyToSubmit()): ?>
      <p style="font-weight:bold;font-size:125%"><a href="<?= $this->url(array('controller' => 'submission',
				'action' => 'review')) ?>">review &amp; submit&gt;</a></p>
  <? endif ?>								     

</p>
