<? /* Process PDF page - if processing succeeded, user should be
    redirected to main record view to start editing.
    Landing on this page means some kind of error occurred.   */ ?>
<h1>Processing PDF</h1>
    
<p>There was an error processing your PDF.</p>

<?= $this->render("submission/_processpdf_errs.phtml"); ?>

<p>Suggestions for resolving this problem:</p>
<ul>
 <li>not image-only</li>
 <li>do not include image of your signature</li>
 <li>not encrypted</li>
 <li>create with recommended tools (see instructions?)</li>
 <li>all required pages are included in the correct order</li>
</ul>

<? if (count($this->log)): /* FIXME: show these to the user ? */?>
   <hr/>
  <p>More details:</p>
  <ul>
  <? foreach ($this->log as $msg): ?>
    <li><?= $msg ?></li>
  <? endforeach ?>
  </ul>
<? endif ?>

   
<? if ($this->debug): ?>
  <pre>
   <?= htmlentities($this->xml) ?>
  </pre>
<? endif ?>




