<p id="submit_warning">
   <span id="exclamation">!</span>
   You are about to deposit the final version of your
Thesis/Dissertation to the ETD Repository.  Please review the document
thoroughly.  After the document is deposited, you will NOT be able to
access the file to make changes of any kind without authorization from
the Graduate School.</p>

<? $this->role = $this->etd->getUserRole($this->current_user);  ?>
<style type="text/css">  <? /* hide a few divs that are not relevant for this page */ ?>
   p.note, #submission_status, #history {display:none; }
</style>
<?=  $this->render('view/fullrecord.phtml'); ?>

<?=  $this->render('submission/_reviewinfo.phtml'); ?>

</hr>
<p><b><a href="<?= $this->url(array('action' => 'submit')) ?>">Submit &gt;</a></b></p>
<? /* fixme; make this a form, add a hidden parameter to confirm that
    it was reviewed? */ ?>