<?= $this->javascript("jquery.local.js"); ?>
<noscript style="color:red">The submission process requires that you enable Javascript.</noscript>

<p>Please answer the following questions before you begin creating your record.</p>

<? if ($this->form_errors): ?>
<div id="messages">
  <? /* display appropriate detailed error message for any missing required fields */ ?>
  <? foreach ($this->form_errors as $err): ?>
    <p class="error">
      <? switch ($err): 
        case 'copyright': ?>You must answer about copyrighted materials.<? break ?>
        <? case 'copyright_permission': ?>Because you have indicated that you have
            included copyrighted materials, you must answer whether or not you have obtained permissions.<? break ?>
        <? case 'patent': ?>You must answer whether or not your work may warrant patenting.<? break ?>
        <? case 'embargo': ?>You must answer whether or not you are requesting an access restriction.<? break ?>
        <? case 'embargo_abs_toc': ?>Because you have indicated you are requesting an access restriction, you must answer about your abstract or table of contents.<? break ?>
        <? case 'title': ?>A title is required to create your initial record.<? break ?>
      <? endswitch ?>
    </p>
  <? endforeach ?>
</div>
<? endif ?>

<form name="submission" id="submission" method="post" 
   action="<?= $this->url(array("action" => "start"))?>"> 

<ol id="screening-questions">
 <li><p>
         Does your thesis or dissertation include any text, audiovisual, or
         other material not created by you or for which you no longer own
         copyright?  (See the Copyright
         <a target="_blank" href="https://classes.emory.edu/webapps/lobj-wiki-bb_bb60/wiki_home/Handler?course_id=_11416_1&content_id=_1251529_1">Education Initiative on Blackboard</a>
         for more information if you are uncertain how to answer this question)
     </p>
    <?= $this->formRadio('copyright', $this->answers['copyright'], 
        array('class' => 'required-field'), $this->yes_no) ?>
     <? /* copyright details: display if answer to copyright question is YES */ ?>
    <div id="copyright_yes"> 
      <ol class="alpha">
      <li>
          <p>Have you obtained permission to use these materials?</p>

          <p>Examples of materials for which you may need permission include
              long quotations, images, and articles you authored for which you
              no longer own copyright.  You will need to list the materials
              for which you obtained permission on the Submission Form.</p>
          <p><b>Please Note:</b></p>
          <p>Materials in the public domain, materials with Creative Commons 
              licenses or materials that fit the Fair Use parameters of
              <a href="http://www.copyright.gov/fls/fl102.html" target="_blank">U.S.
          Copyright Law</a> DO NOT REQUIRE permission.
          <p>See the
              <a href="https://classes.emory.edu/webapps/lobj-wiki-bb_bb60/wiki_home/Handler?course_id=_11416_1&content_id=_1251529_1"
             target="_blank">Copyright Education Initiative</a>
          on Blackboard for more information on the public domain, fair use,
          Creative Commons, the permissions process, and example permission letters.</p>

      <?= $this->formRadio("copyright_permission", $this->answers["copyright_permission"], array(),
			      $this->yes_no) ?>

      </li> 

      <? /* copyright permission details */ ?>
      <div id="copyright_perms_no">  <? /*  Show if answered NO to permissions */ ?> 
        <p>
            If you have not obtained necessary permissions, you must obtain 
            permissions or remove the copyrighted content from your ETD before 
            proceeding with submission.  Please contact Lisa Macklin or 
            Melanie Kowalski of the Libraries’ Scholarly Communications Office 
            at scholcomm@listserv.cc.emory.edu if you have questions.
            <a href="mailto:scholcomm@listserv.cc.emory.edu">scholcomm@listserv.cc.emory.edu</a>
            if you have questions.
        </p>
      </div>
<!--     <div id="copyright_perms_yes"> <? /*  Show if answered YES to permissions */ ?>
            <p>Complete Part 4 of the Submission Form.</p>
      </div>-->
    </li>

    </ol>

    </div>

 <li><p>
         Does your thesis or dissertation disclose or describe any inventions
         or discoveries that could potentially have commercial application 
         and therefore may be patented? (If you and/or your faculty advisor(s) 
         have any questions about patents and commercial applications, please 
         contact the Emory Office of Technology Transfer at
         <a href="mailto:ott-web@emory.edu">ott-web@emory.edu</a>).
     </p>
    <?= $this->formRadio("patent", $this->answers["patent"],
       array('class' => 'required-field'), $this->yes_no) ?>
  <div id="patent_yes">   <? /* display only if yes to patent */ ?>	 
     <p>
         If your ETD describes an invention or discovery that may be patented, 
         further conversation with ETD administrators is required before you 
         can continue with the ETD submission process. Please contact ETD Help 
         at etd-admin@listerv.cc.emory.edu or call (404)727-5301.
         <a href="mailto:etd-admin@listerv.cc.emory.edu">etd-admin@listerv.cc.emory.edu</a>
         or call (404)727-5301.
     </p>
     <? /* TODO: use configured email; remove phone number? */ ?>
  </div>
</li>

<li><p>Are you requesting an access restriction for your thesis or dissertation?</p>
        <?= $this->formRadio("embargo", ($this->answers["embargo"] == null ? null : $this->answers["embargo"]),
			     array('class' => 'required-field'), $this->yes_no) ?>
    <div id="embargo_yes">    <? /* display if answer to embargo is yes */ ?>
     <p>
         Please indicate how long you intend to restrict access to your
         dissertation or thesis on the Submission Form. You will also need to
         indicate your request for an access restriction during the submission
         process itself.
     </p>

     <ol class="alpha">
      <li>
        <p>The ETD system allows for both full and partial embargo of your
            work. A partial embargo will allow visitors to read your abstract
            and/or table of contents while the full text of your thesis or
            dissertation is embargoed. A full embargo allows to you hide this
            information for the duration of the embargo period. Should your
            abstract and/or table of contents be included in the access
            restriction?</p>
        <?= $this->formRadio("embargo_abs_toc", ($this->answers["embargo_abs_toc"] == null ? null : $this->answers["embargo_abs_toc"]), array('class' => 'required-field'), $this->yes_no) ?>

        <div id="embargo_abs_toc_yes">  <? /* display only if restricting abstract/toc */ ?>
          <p>
          You will need to restrict access to your abstract and/or your
          table of contents once you have uploaded you document to the ETD
          repository. If you have already submitted your document to the ETD
          repository, you can log in and make appropriate changes to your
          record while it is in draft form.
        </p>
      </div>
    </li>
  </ol>
   </div>
</li>
</ol>

<p>Enter your thesis or dissertation title to begin the submission process.</p>

<!-- TODO: label needs to be bold, input field needs to be much longer -->
<div>
  <label for="etd_title" class="etd_title">Thesis or Dissertation Title</label>
  <?= $this->formTextarea("etd_title", $this->answers['title'], array("class" => "required-field")); ?> 
</div>

  <?= $this->formSubmit("Begin", "Begin >", array("class" => "button", "style" => "margin-left:10px")); ?>
  <span id="processing" style="display:none">Processing ... <span class="note">(this may take a moment)</span></span>
</form>

<script>          
var $j = jQuery.noConflict(); 
<? /* avoid conflict with prototype/scriptaculous while ETD has both */ ?>

$j(document).ready(function() {
  // configure divs to be conditionally displayed based on answers
  $j('input[name=copyright]').conditionalDisplay({
    conditions: { yes: '#copyright_yes' }
  });
  $j('input[name=copyright_permission]').conditionalDisplay({
    conditions: { yes: '#copyright_perms_yes', no: '#copyright_perms_no' }
  });  
  $j('input[name=patent]').conditionalDisplay({
    conditions: { yes: '#patent_yes' }
  });  
  $j('input[name=embargo]').conditionalDisplay({
    conditions: { yes: '#embargo_yes' }
  });  
  $j('input[name=embargo_abs_toc]').conditionalDisplay({
    conditions: { yes: '#embargo_abs_toc_yes' }
  });  

   // trigger change for all radio inputs to show/hide subsections as appropriate
   // based on initial form values
   $j("input:radio").change();

   //validate required or conditionally required fields on the form
   $j('#submission').validate({
      rules: {
        "copyright_permission": {
          required: "#copyright-yes:checked"
        },
        "embargo_abs_toc" : {
          required: "#embargo-yes:checked"
        }
      },
      errorPlacement: function(error, element) {
        // custom error placement for yes/no radio inputs
        // zend framework view helper outputs input inside a label;
        // if there is a label following, put the error after it; otherwise, after element.
        var after = element.parent().nextAll('label');
        error.insertAfter(after.length > 0 ? after : element);
      },
      submitHandler: function(form) {
        // on valid submit, disable submit button (prevent double/multi-click creating multiple records)
        $j(form).find('input[type=submit]').attr('disabled', true);
        $j('#processing').show();  // display indicator that something is happening
        $j(form).submit();  // now actually submit the form
      }
    });
    jQuery.validator.addClassRules("required-field", {required: true});

});                                       
</script>