<div id="calendar">
<h2>Calendar</h2>

<p><b>April 3, 2009:</b> Theses/Dissertations Due at Graduate School for May Graduation</p>

<p><b>April 22, 2009:</b> Emory College Honors Program deadline for Honors Theses</p>


<p><b>May 11, 2009:</b> Commencement</p>

<p><b>July 2, 2009:</b> Degree Applications Due for August Graduation</p>

<p><b>July 31, 2009:</b> Theses/Dissertations Due for August Graduation</p>
</div>
