<div id="calendar">
<h2>Calendar</h2>

<p><b>Fall ETD  Sumbission workshops:</b><br/>
November 9, 1pm, room 314 in Woodruff Library<br/>
November 16, 1pm, room 314 in Woodruff Library<br/>
November 19, 1pm, room 314 in Woodruff Library<br/>
</p>

<p><b>November 20, 2009:</b> Graduate School submission deadline for fall</p>

<p><b>April 16, 2010:</b> Graduate School submission deadline for spring</p>
</div>
