<h1>Notes on Intellectual Property</h1>

<ul>
 <li><a href="#basics">Copyright Basics</a></li>
 <li><a href="#prev_copyright">Including Previously Copyrighted Materials in Your ETD</a></li>
 <li><a href="#fair_use">What is Fair Use?</a></li>
 <li><a href="#permission">Permission Process</a></li>
 <li><a href="#prev_pub">Including a Previously Published Journal
 Article as a Chapter in Your ETD</a></li>
 <li><a href="#rights">Retaining Rights to your Publications</a></li>
 <li><a href="#author_concerns">Publication Concerns for
	  Authors</a></li>
 <li><a href="#protecting_copyright">Protecting your copyright</a></li>
</ul>


<h2><a name="basics">Copyright Basics</a></h2>

<p>Copyright is a federal law found in <a
href="http://www.copyright.gov/title17">Title 17 of the United States
Code</a>, which gives authors the right to control the use of their
work for a limited period of time. The law also grants exemptions to
users of copyrighted works; one such exemption is Fair Use (link to
fair use further down the page). In order to be copyrighted, a work
must be "an original work of authorship" and "fixed in a tangible
medium of expression." To be "original" a work must have a minimal
amount of creativity. A list of facts or names in a phone book is not
sufficiently creative to be copyrightable. A work is "fixed" if it is
sufficiently permanent or stable to allow it to be perceived,
reproduced or otherwise communicated.</p>

<p>Examples of what cannot be copyrighted include:
<ul>
  <li>Ideas, procedures, methods, systems, processes</li>
  <li>Titles, names, short phrases, slogans</li>
  <li>Facts, news, and research</li>
  <li>Works created by the U.S. Government</li>
</ul>
</p>

<p>Copyright occurs automatically, and one does not need to register a
work nor affix a copyright notice to the work in order for the work to
be protected by copyright. Currently, the term of copyright is the
life of the author plus 70 years. When the term of copyright expires,
the work enters the public domain and can be used without
restrictions. </p>

<h2><a name="prev_copyright">Including Previously Copyrighted Materials in Your ETD</a></h2>

<p>Authors submitting to the ETD repository are subject to the same
concerns regarding copyright as those using the traditional submission
procedures. In order to include any previously copyrighted material,
including text, images, figures, tables, or audio-visual materials, in
an ETD, the material must either be unambiguously in the <a
href="http://www.copyright.cornell.edu/training/Hirtle_Public_Domain.htm">public
domain</a> or fall within the parameters of <a href="#fair_use">fair
use</a>.  If the material does not fall within either of those
categories, authors must receive permission from the copyright owner
to include the material in their ETD.</p>

<h2><a name="fair_use">What is Fair Use?</a></h2>

<p>Fair use is an exemption within copyright law that allows for the
use of copyrighted materials without obtaining permission, provided
the use is fair. A determination of fair use rests upon a four factor
analysis, and the goal of the analysis is to balance the rights of the
copyright owner with the rights of the public to use portions of
copyrighted materials for education, commentary or criticism. The fair
use exemption is technologically neutral, so the same four factor
analysis should be applied regardless of the medium. For help in
performing a fair use analysis, please use the <a
href="<?= $this->linkTo("documents/ETD_fair_use_checklist.doc") ?>">fair use
checklist</a>  <?= $this->filetypeIcon("application/msword") ?>,
and retain a copy of the completed checklist for your
records.</p>

<p>While the only way to definitively determine whether a use is fair
is to have it resolved in federal court, it is important to understand
fair use and the four factor analysis used to determine whether a use
is fair. If a copyright owner claims infringement, the court can
reduce the amount of money damages if the alleged infringer can show
an understanding of the fair use analysis and that they made a good
faith determination that the use was fair.</p>


<p>Section 107 of Title 17 of the United States Code states:

<blockquote>Notwithstanding the provisions of sections 106 and 106A,
      the fair use of a copyrighted work, including such use by
      reproduction in copies or phonorecords or by any other means
      specified by that section, for purposes such as criticism,
      comment, news reporting, teaching (including multiple copies for
      classroom use), scholarship, or research, is not an infringement
      of copyright. In determining whether the use made of a work in
      any particular case is a fair use the factors to be considered
      shall include--
  <ol>
   <li> the purpose and character of the use, including whether such use is of a commercial nature or is for nonprofit educational purposes;</li>
   <li> the nature of the copyrighted work;</li>
   <li> the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and</li>
   <li> the effect of the use upon the potential market for or value
	  of the copyrighted work.</li>
  </ol>
The fact that a work is unpublished shall not itself bar a finding of
fair use if such finding is made upon consideration of all the above
factors.</blockquote>
</p>


<h3>Factor 1: Purpose</h3>

<p>The purpose of the use refers to whether the use is for an
educational purpose, such as teaching or research, or whether the
purpose is for a commercial activity. Another consideration is whether
the use is transformative, whether the use changes the original work
to serve a new purpose. Educational uses and transformative uses weigh
more favorably toward fair use.</p>

<h3>Factor 2: Nature</h3>

<p>The nature of the copyrighted work refers to whether a work is
artistic and creative or whether it is factual in nature. A factual
work weighs more favorably toward fair use than an artistic and
creative work.</p>

<p>Additionally, this factor takes into consideration whether the work
in question has been published or is unpublished. An unpublished work
weighs less favorably toward fair use, as one of the exclusive rights
granted to copyright holders is the right to determine when their work
is first published.</p>

<h3>Factor 3: Amount</h3>

<p>When determining the amount of the use one should perform both a
quantitative and a qualitative analysis. The smaller the portion used,
the more likely the use would be considered a fair use. However, even
a very small portion of a work may not be considered a fair use if it
were the "heart of the work," or the most memorable aspect of the
work. </p>

<h3>Factor 4: Effect</h3>

<p>The fourth factor considers whether, if the use of a work were
widespread, it would deprive the copyright owner of income or
negatively impact the market or potential market for the original
work. Consequently, the more restricted the use, the less of an impact
there will likely be on the market or potential market for the
original work. </p>

<p>The fourth factor is also linked to the purpose of the use because
a negative impact on the market is often presumed if a use is for a
commercial purpose. However, if the use is for an educational purpose
or is transformative, then a negative impact on the market will be
more difficult to prove.</p>


<h2><a name="permission">Permission Process</a></h2>

<p>If your use of a previously copyrighted work exceeds fair use, you
need permission from the copyright owner. When writing a permission
letter, you should include a thorough description of the material to
be used and how you plan to use it.(See a
<a href="<?= $this->linkTo("documents/permissions_letter_text.doc") ?>">sample
permission letter for text</a> <?= $this->filetypeIcon("application/msword") ?> and a
<a href="<?= $this->linkTo("documents/permissions_letter_images.doc") ?>">sample
permission letter for images</a>  <?= $this->filetypeIcon("application/msword") ?>.)  
Permission should be sought in writing, which can be via e-mail, and
all documentation should be kept. Should any question arise, you will
be able to prove you received permission to use the material if you
have kept a record of your correspondence. You must receive an
affirmative response from the copyright owner before using the
material. If you do not receive a response from the copyright owner,
consider revising your use of the material to fall within fair use or
using an alternative work.</p>

<p>There are organizations that manage permissions for authors. By
contacting one of these collective rights organizations you may be
able to receive the permission you need without having to contact an
individual copyright owner. One such organization is the <a
href="http://www.copyright.com">Copyright Clearance Center
(CCC)</a>.</p>


<h2><a name="prev_pub">Including a Previously Published Journal
	Article as a Chapter in Your ETD</a></h2>

<p>If you have previously published an article, either as an author or
co-author, and would like to include it in your ETD, you need to
consider whether the particular chapter is not substantially different
from the published article and if the publication agreement allows
subsequent publication.</p>

<p>If the chapter is not substantially different and the publication
      agreement does not allow subsequent publication, you can either:
  <ul>
	<li>request permission from the publisher, or</li>
	<li>link to the article if it is available online</li>
  </ul>
</p>

<p>Permission is only needed if the particular chapter in your ETD is
not substantially different from the previously published article. The
particular chapter in your thesis or dissertation may be substantially
different because articles are often shorter and more concise, while
your thesis or dissertation may include all your data and a more
thorough explanation of your research.</p>

<p>Permission is also not needed if the publication agreement includes
provisions for the author to retain the right reproduce the article
for non-commercial purposes or post the article to institutional
websites or open-access repositories.</p>


<h2><a name="rights">Retaining Rights to your Publications</a></h2>

<p>Many publishers use traditional publication agreements which
require that all rights, including copyright, transfer to the journal
publisher. Consequently, if you have transferred your copyright to the
journal, you may have to ask for permission from the journal publisher
to include your article in your ETD.</p>

<p>One way to avoid this issue is to carefully read all your
publication agreements and negotiate with the publisher. If your
research has been accepted for publication in a journal, book, or
conference proceeding, you can negotiate with the publisher to retain
some of your rights. If you would like to include the material in an
ETD or to reuse the material is some other way, negotiate with the
publisher to create such an agreement.</p>

<p>One way to retain some of your rights, including the right to
include your article in your ETD, is to add the <a
href="http://www.arl.org/sparc/author/addendum.html">SPARC Author
Addendum</a> to your publication agreement. The addendum modifies the
publication agreement to allow the author to retain some rights,
including the ability to reproduce the article for non-commercial
purposes, prepare derivative works from the article, and post the
article to personal or institutional websites or open-access digital
repositories.</p>


<h2><a name="author_concerns">Publication Concerns for Authors</a></h2>

<p>Emory authors retain the copyright to their theses and
dissertations. In submitting one's thesis or dissertation to the
repository, you grant to the University a limited publication
license. Emory may retain a copy for preservation purposes and publish
the document via the World Wide Web by including it in our
repository.</p>

<p>Many authors, especially in the humanities, produce books from
their dissertations. Some publishers may have concerns about a thesis
or dissertation, on which a book is to be based, having been
previously available on the web. We recommend, therefore, that you
check with your publisher about whether depositing your document in
the repository would jeopardize your publication plans in the
future. Because most books produced from dissertations require
considerable revision, there is a strong argument that depositing a
thesis or dissertation in the repository would not amount to a prior
publication.  Also, availability of a thesis or dissertation on the
web can increase interest in a topic be an indicator of potential book
sales.</p>

<h2><a name="protecting_copyright">Protecting your copyright</a></h2>

<p>Copyright is automatically granted to the author of a work at the
time the work is created in a fixed form. Neither a notice of
copyright, nor registration is required by law.  However, it is
beneficial to include a copyright notice on your thesis or
dissertation because it shows your reader that you are the copyright
owner and states the first date of publication. An example of such a
notice is: &copy; <i>2007 Jane Doe</i>. The notice should be
placed in a prominent location, typically after the title page.</p>

<p>Additionally, while registration is not required for copyright
protection, you will receive certain benefits by registering your
copyright with the Copyright Office. Registration establishes a public
record of your copyright and is necessary before you can file a
lawsuit for copyright infringement. By registering your copyright
before an infringement occurs, you will be eligible to receive
statutory damages and attorney's fees. An added benefit of registering
your copyright is the inclusion of your dissertation or thesis in the
Library of Congress.</p>

<p>If you publish your dissertation through UMI, UMI can prepare the
registration forms and deposit copies of your thesis or dissertation
on your behalf. You may also download the forms from the <a
href="http://www.copyright.gov">U.S. Copyright Office website</a> and
submit the forms and copies of your thesis or dissertation
yourself.</p>

