<p><b>Error: <?= $this->error ?></b></p>

<? if ($this->error_message): ?>
  <p style="color:red"><?= $this->error_message ?></p>
<? endif ?>     

<? if ($this->env == "development" && isset($this->exception)): ?>
<?= $this->exception->getMessage() ?><br/>
Line <b><?= $this->exception->getLine() ?></b> in <b><?= $this->exception->getFile() ?></b><br/>
<?= $this->exception->getTraceAsString() ?>
<? endif ?>
