<script type="text/javascript">
function open_flash_chart_data()
{
    return JSON.stringify(data);
}
function GetXmlHttpObject()
{
	if (window.XMLHttpRequest)
  	{
    	// code for IE7+, Firefox, Chrome, Opera, Safari
      		return new XMLHttpRequest();
        }
	if (window.ActiveXObject)
	{
	    // code for IE6, IE5
	      return new ActiveXObject("Microsoft.XMLHTTP");
	}
	return null;
}
function findSWF(movieName) {
  if (navigator.appName.indexOf("Microsoft")!= -1) {
    return window[movieName];
  } else {
    return document[movieName];
  }
}
function stateChanged()
{
	if (xmlhttp.readyState == 4) //4 - complete
	{
	    var adata = xmlhttp.responseText;
	    tmp = findSWF("my_chart");
	    tmp.load(adata);
	    return JSON.stringify(adata);
	}
}
function change_chart_type_by_program(type)
{
        xmlhttp = GetXmlHttpObject();
        var index = document.progform.proglist.selectedIndex;
        var text = document.progform.proglist.options[index].text;
        if (xmlhttp == null)
        {
                alert ("Your browser does not support AJAX!");
                return;
        }
        //prepare url here
        var url = document.URL + 'specific/programname/' + type + '/nametext/' + text;
        xmlhttp.onreadystatechange = stateChanged;
        xmlhttp.open("GET",url,true);
        xmlhttp.send(null);
}
function change_chart_type_by_year(type)
{
        xmlhttp = GetXmlHttpObject();
        if (xmlhttp == null)
        {
                alert ("Your browser does not support AJAX!");
                return;
        }
        //prepare url here
        var url = document.URL + 'specific/year/' + type;
        xmlhttp.onreadystatechange = stateChanged;
        xmlhttp.open("GET",url,true);
        xmlhttp.send(null);
}
</script>
