<script type = "text/javascript" src="<?= $this->linkTo('js/swfobject.js') ?>"></script>
<script type = "text/javascript">
swfobject.embedSWF("<?= $this->linkTo('js/ofc/open-flash-chart.swf') ?>", "my_chart", "750", "500", "9.0.0");
</script>
<script type="text/javascript">    
function open_flash_chart_data(){
   return JSON.stringify(<?= $this->chart->toPrettyString(); ?>);
}
</script>

<p>Filter by year:
  <select id="year" name="year" onChange="window.location=$('year').getValue()">
      <option value="<?= $this->url(array('year' => null)) ?>"
        <? if (! $this->current_year): ?> selected="true" <? endif ?> >All</option>
<? foreach ($this->years as $year): ?>
   <option value="<?= $this->url(array('year' => $year)) ?>"
     <? if ($year == $this->current_year): ?> selected="true" <? endif ?> ><?= $year ?></a></option>
<? endforeach ?>
  <? if ($this->current_year): ?> <a href="<?= $this->url(array('year' => null)) ?>">All</a>
  <? else: ?> All
  <? endif ?>
  </select>
				     
</p>

<p>Filter by Program:
  <?=  $this->render('report/_program_hierarchy.phtml'); ?>				      
<? if (count($this->program->members)): ?>    &gt;		
  <select id="program" name="program" onChange="window.location=$('program').getValue()">
   <option value="#">--</option>  <? /* blank entry so any selection is a change */ ?>
    <? foreach ($this->program->members as $member): ?>
      <? $link_id = str_replace("#", '', $member->id);?>
      <option value="<?= $this->url(array('program' => $link_id)) ?>"><?= $member->label ?></option>
    <? endforeach ?>
  </select>  
<? endif ?>
				     
<div id="my_chart"></div>
