<H1>Available Reports</H1>
<ul>
  <li><a href="<?= $this->url(array("controller" => "report",
			"action" => "summary-stat"), '', true); ?>">Summary Statistics</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
			"action" => "commencement-review"), '', true); ?>">Graduate School Commencement Report</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
		"action" => "grad-data"), '', true); ?>">Graduate School Academic Year Report</a>
	<?= $this->FiletypeIcon("text/csv") ?></li>
  <li><a href="<?= $this->url(array("controller" => "report",
		"action" => "embargo-csv"), '', true); ?>">Upcoming Embargos</a>
	<?= $this->FiletypeIcon("text/csv") ?></li>
  <li>Page Length -
      <a href="<?= $this->url(array("controller" => "report",
			"action" => "pagelengthbydegree"), '', true); ?>">by degree</a>
      <a href="<?= $this->url(array("controller" => "report",
			"action" => "pagelengthbyprogram"), '', true); ?>">by program</a>
  </li>
  <li>Requested Embargo Duration - 
	<a href="<?= $this->url(array("controller" => "report",
			"action" => "embargobyyear"), '', true); ?>">by year</a>
        <a href="<?= $this->url(array("controller" => "report",
			"action" => "embargobyprogram"), '', true); ?>">by program</a>
 </li>
  <li><a href="<?= $this->url(array("controller" => "report",
	    'action' => 'exportemails')) ?>">Export email addresses for approved records</a>
    <?= $this->FiletypeIcon("text/csv") ?></li>
</ul>
