<H1>Available Reports</H1>
<ul>
  <li><a href="<?= $this->url(array("controller" => "report",
			"action" => "summary-stat"), '', true); ?>">Summary Statistics</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
			"action" => "commencement-review"), '', true); ?>">Graduate School Commencement Report</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
		"action" => "grad-data"), '', true); ?>">Graduate School Academic Year Report</a>
	<?= $this->FiletypeIcon("text/csv") ?></li>
  <li><a href="<?= $this->url(array("controller" => "report",
		"action" => "embargo-csv"), '', true); ?>">Upcoming Embargos</a>
	<?= $this->FiletypeIcon("text/csv") ?></li>
  <li><a href="<?= $this->url(array('action' => 'embargo')) ?>">Requested Embargo Duration</a></li>
  <li><a href="<?= $this->url(array('action' => 'embargo')) ?>">Document Length</a></li>
  <li><a href="<?= $this->url(array("controller" => "report",
	    'action' => 'exportemails')) ?>">Export email addresses for approved records</a>
    <?= $this->FiletypeIcon("text/csv") ?></li>
</ul>
