<script type = "text/javascript" src="<?= $this->linkTo('js/swfobject.js') ?>"></script>
<script type = "text/javascript" src="<?= $this->linkTo('js/json/json2.js') ?>"></script>
<script type = "text/javascript">
swfobject.embedSWF("<?= $this->linkTo('js/ofc/open-flash-chart.swf') ?>", "my_chart", "750", "500", "9.0.0");
</script>
<?=  $this->render('report/chart.phtml'); ?>
<script type="text/javascript">
var data = <?php echo $this->flashchart->toPrettyString(); ?>;
</script>
<form name = "progform">
Please Select A Program: <select name = "proglist" onchange = "change_chart_type_by_program(this.value)">
<? foreach ($this->collection->members as $member): ?>
   <? $prog_id = str_replace("#", '', $member->id);?>
   <? $prog_name = str_replace('/', ' and ', $member->label);?>
<option value = <?= $prog_id?>><?= $prog_name ?></option>
<? endforeach ?>
</select>
</form>
<br>
<div id="my_chart"></div>
