<? /* recursive partial template to generate hierarchy list; expects these variables:
      collection - skosCollection for this level of the tree
      acl 	 - ACL object
      current_user - logged in user, for checking acl
      can_edit	 - boolean: can the current user edit this portion of the subtree   */ ?>
<? if ($this->can_edit ||
       ($this->collection->id == "#undergrad" && 
	$this->acl->isAllowed($this->current_user, "undergrad programs", "edit"))) {
     $this->can_edit = true;
} ?>
<? $id = $this->collection->getId(); /* clean id used multiple times below */ ?>
   <li id="item_<?= $id ?>">
    <? if ($this->can_edit): ?>
      <a><?= $this->img("images/draggable.png", array("class" => "hdl", "alt" => "click to drag",
						      "id" => $id . "_img",
						    "onMouseOver" => "hdlOn('" . $id . "_img')",
						    "onMouseOut" => "hdlOff('" . $id . "_img')")) ?></a>
    <? endif ?>

   <? if (count($this->collection->members)): ?>
      <a class="toggle" id="<?= $id ?>_txt" onClick="Element.toggle('<?= $id ?>_list')">&gt;</a>
   <? endif ?>

   <? if ($this->can_edit): ?>
     <input type="text" value="<?= $this->collection->label ?>" name="<?= $id ?>"/>
   <? else: ?>
       <?= $this->collection->label ?>
   <? endif ?>
	
    <input type="hidden" id="<?= $id ?>_members" name="<?= $id ?>_members" value=""/>
     <ul id="<?= $id ?>_list"
     <? foreach ($this->collection->members as $subcollection): ?>
      <?=  $this->partial('program/_tree.phtml', array("collection" => $subcollection,
						       "acl" => $this->acl,
						       "current_user" => $this->current_user,
						       "can_edit" => $this->can_edit)); ?>
     <? endforeach ?>
     </ul>
 </li>




