<? /* dublin core xform for etd file */ ?>
<xf:instance id="dcmitypes" xmlns="">
   <dcmitypes>
     <type display="Text" value="Text"/>
     <type display="Dataset" value="Dataset"/>
     <type display="Video" value="MovingImage"/>
     <type display="Image" value="StillImage"/>
     <type display="Software" value="Software"/>
     <type display="Sound" value="Sound"/>
   </dcmitypes>
</xf:instance>   

<? // any bindings needed here? ?>
<xf:bind nodeset="dc:title" type="xsd:string"
   constraint=". != ''" required="true()" />
	  
<xf:submission id="submission" action="<?= $this->url(array('action' => 'save', 'pid' => $this->etdfile->pid))?>"
		method="post" />

<xf:message level="modal"
   ev:event="xforms-submit-error">Error: check that all required fields are filled in correctly</xf:message>
