<?=  $this->render('email/_debug.phtml'); ?>
<p>Dear <?= $this->etd->mods->author->first ?>,</p>

<p>This is to inform you that your <?= $this->etd->document_type() ?> entitled:
<blockquote><?= $this->etd->title() ?></blockquote>
can now be accessed in the Emory University ETD Repository at:
<a href="<?= $this->etd->ark() ?>"><?= $this->etd->ark() ?></a></p>

<? if ($this->etd->mods->embargo_request == "no"): ?>
<p>Upon submission, you agreed to grant open access to your work via the
web.  We appreciate your contribution to the intellectual output of
the University, and we hope that making your work as widely accessible
as possible will be mutually beneficial.</p>
<? else: ?>
<p>Upon submission, you chose to restrict access to your work via the
web.  Access to your <?= $this->etd->document_type() ?> will be restricted for
<?= $this->etd->mods->embargo ?>.  Details describing your document will appear in
the repository's index, but the full text of your work will not appear
until the expiration of the access restriction period.</p>

<p>The access restriction associated with your <?= $this->etd->document_type() ?> 
will expire automatically on <?= $this->etd->mods->embargo_end ?>.  You will receive notice
(via e-mail to the permanent e-mail address which you provided) of the
impending expiration of the access restriction sixty (60) days prior
to the access restriction's expiration.  You are responsible for
contacting the Emory library if you need to extend that access
restriction for any reason.</p>

<? endif ?>

<p>The library no longer requires that you create bound paper copies
of your thesis.  Please contact your department or
program regarding their requirements for the production of paper
copies for department/program libraries or committee members.  To have
personal copies of your thesis produced, there are a <a
href="http://etd.library.emory.edu/docs/boundcopies">number of
vendors</a> who you may wish to contact, and their contact information
is listed on the ETD website.
<? if (! $this->etd->isHonors()): /* PQ-specific, not relevant for undergrad */ ?>
(Paper copies of your thesis will also be available through UMI/Proquest
once your thesis has been processed by them.)
<? endif ?>
</p>

<p>Congratulations!</p>

