<?=  $this->render('email/_debug.phtml'); ?>

<p>An automated email message regarding your Emory Electronic Thesis
or Dissertation (ETD) was sent out in error earlier today. Please
disregard this message. Feel free to contact <a
href="mailto:ETD-ADMIN@listserv.emory.edu">ETD-ADMIN@listserv.cc.emory.edu</a>
if you have any questions or concerns.</p>

<p>Please be assured that no documents will be released prior to the
expiration of the access restriction period you requested.</p>
