<div id="calendar">
<h2>Calendar</h2>

<p>
    <b>Information Workshops:</b><br/>
    <ul>
        <li>Thursday, Feb 17, Rollins School of Public Health (Room TBA), Noon</li>
        <li>Thursday, Feb 24, Woodruff Library Room 310, 3pm</li>
        <li>Wednesday, March 2, Rollins School of Public Health (Room TBA), Noon</li>
        <li>Monday, March 14, Woodruff Library Room 310, 3pm</li>
    </ul>

</p>

<p>
    <b>Submission Workshops:</b>
    <ul>
        <li>Wednesday, April 6, Woodruff Library Room 310, 3pm</li>
        <li>Thursday, April 7, Rollins School of Public Health (Room TBA), Noon</li>
        <li>Tuesday, April 12, Rollins School of Public Health (Room TBA), Noon</li>
        <li>Thursday, April 14, Woodruff Library Room 310, 3pm</li>
    </ul>
</p>

</div> 

