<h1>About Emory's Electronic Thesis and Dissertation (ETD)
      Repository</h1>

<h2>Program Summary</h2>

<p>As a first step towards creating an institutional repository, Emory
began plans for its ETD repository in the Spring of 2006 when the
library's Digital Programs and Systems division formed the ETD
Advisory Group, comprised of faculty, graduate students, university
administrators and librarians.  A fulltime project manager was hired
in 2006.</p>

<p>The primary purpose of the ETD repository is to provide convenient
access to one of the most important intellectual products of the
university - masters theses and doctoral dissertations.  (It will also
recognize the contributions of undergraduate scholars by collecting
undergraduate honors theses.)  In the past, access to an Emory thesis
or dissertation was quite limited.  Beyond reading the one copy held
in Emory's library, interested (non-Emory) researchers could only
acquire copies of theses and dissertations through interlibrary loan
or by purchasing a paper or electronic copy of the document from
UMI/Proquest.  Moreover, it often took a number of months after the
author's graduation before the academic community could access the
document.  The ETD repository offers prompt web-based access to these
documents, greatly increasing the visibility of our scholars and
fulfilling our core mission: to contribute to academic scholarship.
It is our hope that this program will also streamline the submission
process and eliminate the production of unnecessary paper copies of
documents.</p>


<h2>Contributors</h2>

<p>The program was overseen by the university's ETD advisory group:
University Library Representatives: Martin Halbert, Erika Farr,
Katherine Skinner, Lars Meyer, Ginger Cain and Paul O'Grady; Faculty
Representatives: Simon Blakey, Department of Chemistry, Kathy Miner,
Rollins School of Public Health, Paul Courtright, Department of
Religion, Harry Rusche, Department of English, Elizabeth Fox-Genovese,
Department of History, Walt Reed, Institute for Liberal Arts; Rick
Rubinson, Graduate School of Arts and Sciences (GSAS); Staff
Representatives: Maureen Sweatman, Office for Undergraduate Education,
Monica Taylor, Graduate Division of Biological/Biomedical Sciences,
Queen Watson (GSAS); Student Representatives: Wesley Robertson,
Department of Physics, Scott Gavorsky, Department of History.  The
contributions of the Emory Graduate School administration, including
Dean Lisa Tedesco, Rosemary Hines, and Virginia Shadron were
invaluable to the design of this program.  </p>

<h2>Software Development</h2>

<p>The submission system used is the <a
href="http://www.fedora.info/">Fedora Digital Repository System</a>
combined with the <a
href="http://espace.library.uq.edu.au/documentation/">Fez</a> web
front-end for Fedora, developed at the University of Queensland,
Australia.  The software development team at Emory is led by Kyle
Fenton and includes Rebecca Sutton Koeser, Jason White and Chris
Roddy.  </p>
