<p>Most general questions about submission will be answered on our <a href="http://localhost/src/public/docs/instructions">instructions page.</a></p>
<p>For general questions about submitting your thesis or dissertation, you should contact Queen Watson in the Graduate School.</p>
<p>For problems creating a PDF, please consult the support staff in ECIT, the Cox Hall Computer Lab, or the Tech staff for your individual programs.</p>
<p>&nbsp</p>
<p>For problems with the ETD submission software, please submit your questions using the form below or send an email to <a href="mailto:etd-help@listserv.cc.emory.edu">etd-help@listserv.cc.emory.edu</a>.</p>

	<script type="text/javascript"
		djConfig="isDebug: true, parseOnLoad: true"
		src="http://o.aolcdn.com/dojo/1.2.3/dojo/dojo.xd.js"></script>
	<script type="text/javascript">
		dojo.require("dijit.form.Form");
		dojo.require("dijit.form.DateTextBox");
		dojo.require("dijit.form.ValidationTextBox");
		dojo.require("dijit.form.Textarea");
		dojo.require("dijit.form.Button");
		dojo.require("dojox.validate.regexp");
		dojo.require("dojo.parser");
			
		//Put "onload" logic in here.
		dojo.addOnLoad(function(){
			var theme = 'tundra';
			if(!dojo.hasClass(dojo.body(),theme))
			{
			        dojo.addClass(dojo.body(),theme);
			}
		});
	</script>
	<head>
	<style type="text/css">
        @import "http://o.aolcdn.com/dojo/1.2.3/dijit/themes/tundra/tundra.css";
        @import "http://o.aolcdn.com/dojo/1.2.3/dojo/resources/dojo.css";
	</style>
	</head>

<form dojoType="dijit.form.Form" id="helpSubmissionForm" action="<?= $this->url(array("action" => "submit"))?>">
<fieldset id="helpFormFields"><legend ="helpLegend">ETD Help Submission Form</legend>
<div class="formRow"><input type="hidden" id="etd_link" name="etd_link" value="<?= $this->$current_user->fullname ?>"></input></div>
<div class="formRow"><label class="formLabel" for="username">Full Name:</label><input dojoType="dijit.form.TextBox" class="formInput" type="text" id="username" name="username" value="<?= $this->$current_user->fullname ?>"></input></div>
<div class="formRow"><label class="formLabel" for="email">Net ID Email:</label><input dojoType="dijit.form.ValidationTextBox" class="formInput" type="text" id="email" name="email" value="<?= $this->$current_user->netid ?>"regExpGen="dojox.regexp.emailAddress" trim="true" required="true" invalidMessage="Invalid Email Address."></input></div>
<div class="formRow"><label class="formLabel" for="grad_date">Graduation Date:</label><input class="formInput" type="text" id="grad_date" name="grad_date" value="" dojoType="dijit.form.DateTextBox" constraints="{datePattern:'MM/yyyy'}" required="true" trim="true" promptMessage="mm/yyyy" invalidMessage="Invalid date. Use mm/yyyy format."></input></div>
<div class="formRow"><label class="formLabel" for="message">Message:</label><textarea dojoType="dijit.form.Textarea" class="formInputArea" type="text" id="message" name="message" value=""></textarea></div>
<div id="helpFormButtons">
<button dojoType="dijit.form.Button" class="formInput" type="submit" id="submitButton" title="Submit">Submit</button>
<button dojoType="dijit.form.Button" class="formInput" type="reset" id="resetButton" title="Reset">Reset</button>
</div>
</fieldset>
</form>

