<p>Most general questions about submission will be answered on our <a href="<?= $this->url(array("controller" => "docs", "action" => "instructions"), '', true); ?>">instructions page.</a></p>
<p>For general questions about submitting your thesis or dissertation, you should contact Queen Watson in the Graduate School.</p>
<p>For problems creating a PDF, please consult the support staff in ECIT, the Cox Hall Computer Lab, or the Tech staff for your individual programs.</p>
<p>&nbsp</p>
<p>For problems with the ETD submission software, please submit your questions using the form below:</p>

	<script type="text/javascript"
		djConfig="isDebug: false, parseOnLoad: true"
		src="http://o.aolcdn.com/dojo/1.2.3/dojo/dojo.xd.js"></script>
	<script type="text/javascript">
		dojo.require("dijit.form.Form");
		dojo.require("dijit.form.DateTextBox");
		dojo.require("dijit.form.ValidationTextBox");
		dojo.require("dijit.form.Textarea");
		dojo.require("dijit.form.Button");
		dojo.require("dijit.form.CheckBox");
		dojo.require("dojox.validate.regexp");
		dojo.require("dojo.parser");
			
		//Put "onload" logic in here.
		dojo.addOnLoad(function(){
			var theme = 'tundra';
			if(!dojo.hasClass(dojo.body(),theme))
			{
			        dojo.addClass(dojo.body(),theme);
			}
		});
	</script>
	<head>
	<style type="text/css">
        @import "http://o.aolcdn.com/dojo/1.2.3/dijit/themes/tundra/tundra.css";
        @import "http://o.aolcdn.com/dojo/1.2.3/dojo/resources/dojo.css";
	</style>
	</head>

<form dojoType="dijit.form.Form" id="helpSubmissionForm" action="<?= $this->url(array("action" => "submit"))?>">
<fieldset id="helpFormFields"><legend ="helpLegend">ETD Help Submission Form</legend>
<?php 
	$config = Zend_Registry::get('config');
	$environment = Zend_Registry::get('env-config');
	if ($environment->mode != "production") {
?>
	<div class="formRow">
		<label class="formLabel" for="list_addr"><strong>DEBUG</strong> To:</label>
		<input dojoType="dijit.form.ValidationTextBox" regExpGen="dojox.regexp.emailAddress" class="formInput" type="text" id="list_addr" name="list_addr" value="<?= isset($this->list_addr)?$this->list_addr:"" ?>"  required="true" title="DEBUG: Send this email to this address" promptMessage="DEBUG: Send this email to this address"></input></div>
<?php
	}
?>
	<div class="formRow">
		<input type="hidden" id="etd_link" name="etd_link" value="<?= isset($this->etd_link)?$this->etd_link:"" ?>"></input></div>
	<div class="formRow">
		<label class="formLabel" for="username">Full Name:</label>
		<input dojoType="dijit.form.TextBox" class="formInput" type="text" id="username" name="username" value="<?= isset($this->fullname)?$this->fullname:"" ?>"  required="true" title="User's Full Name" promptMessage="User's Full Name"></input></div>
	<div class="formRow">
		<label class="formLabel" for="email">Net ID Email:</label>
		<input dojoType="dijit.form.ValidationTextBox" class="formInput" type="text" id="email" name="email" value="<?= isset($this->email)?$this->email:"" ?>" regExpGen="dojox.regexp.emailAddress" trim="true" required="true" title="User's netid email address" promptMessage="User's netid email address" invalidMessage="Invalid Email Address."></input>
		<input class="formInput" type="checkbox" id="copy_netid" name="copy_netid" value="true" dojoType="dijit.form.CheckBox" title="Send a copy to yourself?"></input> Send me a copy</div>
	<div class="formRow">
		<label class="formLabel" for="grad_date">Graduation Date:</label>
		<input class="formInput" type="text" id="grad_date" name="grad_date" value="" dojoType="dijit.form.DateTextBox" value="new Date();" constraints="{datePattern:'MM/yyyy'}" required="true" trim="true" promptMessage="Please use this format: mm/yyyy" invalidMessage="Invalid date. Use mm/yyyy format."></input>
		or N/A <input class="formInput" type="checkbox" id="grad_date_appl" name="grad_date_appl" value="true" dojoType="dijit.form.CheckBox" onClick="dijit.byId('grad_date').setDisabled(dijit.byId('grad_date_appl').getValue()); dijit.byId('grad_date').setValue('');" title="No specific graduation date"></input></div>
	<div class="formRow">
		<label class="formLabel" for="subject">Subject:</label>
		<input dojoType="dijit.form.TextBox" class="formInput" type="text" id="subject" name="subject" value=""  required="true" title="Please enter the subject of the assistance needed." promptMessage="Please enter the subject of the assistance needed."></input></div>
	<div class="formRow">
		<label class="formLabel" for="message">Message:</label>
		<textarea dojoType="dijit.form.Textarea" class="formInputArea" minSize="250px" type="text" id="message" name="message" required="true" title="Please be as descriptive as possible" promptMessage="Please be as descriptive as possible"value=""></textarea></div>
	<div id="helpFormButtons">
		<button dojoType="dijit.form.Button" class="formInput" type="submit" id="submitButton" title="Submit">Submit</button>
		<button dojoType="dijit.form.Button" class="formInput" type="reset" id="resetButton" title="Reset">Reset</button>
	</div>
</fieldset>
</form>

