<?= $this->javascript("util.js"); ?>

<h1>Add file to record</h1>

<p><b><?= $this->etd->title() ?></b></p>

<p>Upload both a PDF copy and the original file of your thesis.  Your
    original file is likely a Microsoft Word file.  You may also upload
    supplemental files associated with your document, such as data sets,
    audio or video, computer animation, or other material.</p>

<ul>
    <li>The PDF and supplemental files will be available on your public ETD
        record after any requested embargo expires.</li>
    <li>The library collects your original files for archival purposes.
        It will neither be visible nor downloadable from your public ETD record.</li>
</ul>



<form name="addfile" method="post" enctype="multipart/form-data" onsubmit="disableButton('Upload')"
    action="<?= $this->url(array("action" => "new", "etd" => $this->pid))?>">

   <p><b>Type of file to add:</b></p>
  <p><?= $this->formSelect("filetype", $this->default_filetype, null,
			   array("pdf" => "Thesis/Dissertation in PDF format",	
				 "original" => "Thesis/Dissertation in original format ",
				 "supplement" => "Supplemental file")); ?> </p>
   
  <p><?= $this->formFile("file"); ?></p>

  
  <?= $this->formSubmit("Upload", "Upload"); ?>
</form>
