<h1>Commencement Report </h1>

 <?php //Change this paragraph if the query changes ?>
    <p>
        Selected all records with degree <span style="font-weight:bold">PhD</span>
        published between <span style="font-weight:bold"><?=$this->startDate ?></span> and
        <span style="font-weight:bold"><?=$this->endDate ?></span> or not yet published and with status not
        <span style="font-weight:bold">inactive</span>.
    </p>


<?php //Based on browse/list.phtml ?>

    <p>Displaying <?=  count($this->etdSet->etds); ?> result(s)</p>

<? /* output formatted content in a hidden textarea; use FCKEditor to display
      as formatted and make easily selectable */ ?>
<textarea id="commencement-report" style="display:none"> 
<? foreach ($this->etdSet->etds as $etd): ?>
  <? $this->etd = $etd; ?>
  <?=  $this->render('report/shortrecord.phtml'); ?>
<? endforeach ?>
</textarea>

<? /* configuration options for FCK editor */ 
$editor_opts = array("config" => (string)$this->linkTo("js/FCKconfig.js"),
			    "height" => "400", "toolbar" => "etd-title" );
$editor_opts["css"] = $this->linkTo("css/etd.css");
?>

<?= $this->FckEditor("commencement-report", '', $editor_opts) ?>
