<?=  $this->render('email/_debug.phtml'); ?>
<p>Dear <?= $this->etd->mods->author->first ?>,</p>

<p>When you submitted your dissertation or thesis to the
Emory University ETD repository, you requested that the full text of
your document remain inaccessible for <?= $this->etd->mods->embargo ?>.</p>

<p>Unless the library is informed otherwise, the full text of your thesis 
will be available via our website on <?= $this->etd->mods->embargo_end ?>.  
It is your responsibility to request an extension of your access restriction
if it is necessary.</p>

<p>Please feel free to contact <a href="mailto:<?= $this->contact->email ?>"><?= $this->contact->email ?></a>
if you need to request an extension or if you have other questions regarding your ETD.
Thank you very much for participating in the ETD Program.</p>