<?/* display breadcrumb of collection hierarchy
      - follows tree of parents, displaying top-level parent first
      - starting collection is displayed bold and without a link
      - expects view->collection set to starting point collection
   */ ?>
<? if (!isset($this->original)) $this->original = $this->collection; ?>
<? if (isset($this->collection->parent)): ?>
     <? $current_coll = $this->collection; // store reference to current collection ?>
     <? $this->collection = $this->collection->parent; // set context for template ?>
     <?=  $this->render('browse/_collection_breadcrumb.phtml'); // recurse?>
     <? $this->collection = $current_coll; ?>
     >
<? endif ?>     
<? $link_id = str_replace("#", '', $this->collection->id);?>
<? if ($this->collection == $this->original):?>
  <b><?= $this->collection->label; ?></b>
<? else: ?>
  <a href="<?= $this->url(array('controller' => 'browse', 'action' => $this->action,
	'coll' => $link_id), '', true)?>"><?= $this->collection->label; ?></a>
<? endif ?>
