<? /* assumes view->facets is set with output from Solr */ ?>
<div class="facets" style="float:right;border:1px solid gold;background:white;width:150px;font-size:85%;"> 
   <b>Facets</b><br/>
Advisor:<br/>
   <ul>
   <? foreach ($this->facets->advisor as $value => $count): ?>
     <li><?= $value ?> (<?= $count ?>)</li>
   <? endforeach ?>
   </ul>

<? if (count($this->facets->year) && $this->browse_mode != "year"): ?>
  Year:<br/>
   <ul>
   <? foreach ($this->facets->year as $value => $count): ?>
	<li><?= $value ?> (<?= $count ?>)</li>
   <? endforeach ?>
   </ul>
<? endif ?>
    
Subject:<br/>
   <ul>
   <? foreach ($this->facets->subject as $value => $count): ?>
	<li><?= $value ?> (<?= $count ?>)</li>
   <? endforeach ?>
   </ul>

Committee:<br/>
   <ul>
   <? foreach ($this->facets->committee as $value => $count): ?>
     <li><?= $value ?> (<?= $count ?>)</li>
   <? endforeach ?>
   </ul>

<? if ($this->browse_mode != "program"): ?>
Program:<br/>
   <ul>
   <? foreach ($this->facets->program as $value => $count): ?>
	<li><?= $value ?> (<?= $count ?>)</li>
   <? endforeach ?>
   </ul>
<? endif ?>

<? if ($this->browse_mode != "author"): ?>
Author:<br/>
   <ul>
   <? foreach ($this->facets->author as $value => $count): ?>
     <li><?= $value ?> (<?= $count ?>)</li>
   <? endforeach ?>
   </ul>
<? endif ?>
  
</div>
