<p class="browse_heading"><b>Browse by <?= $this->browse_mode ?></b></p>

<? if ($this->alpha): ?>
  <div class="letters">
     <a
       <? if ($this->letter == "" || !isset($this->letter)): ?> class="current"
       <? else: ?> href="<?= $this->url(array('controller' => $this->controller,
			'action' => $this->action), '', true) ?> "
       <? endif ?>
     >All</a> | 
    <? foreach ($this->letters as $letter): ?>
      <a 
        <? if ($letter == $this->letter): ?> class="current"
        <? else: ?>   href="<?= $this->url(array('letter' => $letter)) ?> "
        <? endif ?> >
          <?= $letter ?></a>
    <? endforeach ?>
  </div>
<? endif ?>					 

<? if ($this->browse_mode != "year"): // doesn't make sense for years ?>
  <p><?= $this->count ?> match<? if ($this->count != 1):?>es<? endif ?> found</p>
<? endif ?>   
<? if ($this->count): ?>
  <ul>
  <? foreach ($this->values as $value =>  $count): ?>
     <li><a href="<?= $this->url(array("value" => urlencode($value))) ?>"><?= $value ?></a>
       <? if (($this->action != "author")  || $count != 1): ?>
        (<?= $count ?>)
       <? endif ?>
     </li>
  <? endforeach ?>
  </ul>
<? endif ?>       


<!--<pre>
     <?//= print_r($this->values); ?>
</pre> -->