<? if ($this->list_title): ?>
     <h1><?= $this->list_title ?></h1>
<? endif ?>

<? if (isset($this->count) && isset($this->start) && isset($this->max)): ?>
  <? $this->end = min($this->start + $this->max, $this->count); ?>
  <? if (!$this->post && $this->max < $this->count): ?>
   <ul style="float:right" class="horizontal">
      <li class="first">More results:
     <? for ($i = 1; $i <= $this->count; $i += $this->max): ?>
     <? $cur_end = min($i + $this->max - 1, $this->count);
        $range = $i;  if ($cur_end != $i) $range .= "-" . $cur_end ; ?>
	<? if ($i != 1): ?><li><? endif ?>
     <? if (($i - 1) != $this->start): ?>
          <a href="<?= $this->url(array('start' => $i - 1, 'max' => $this->max)) ?>"><?= $range ?></a>
       <? else: ?>
	   <?= $range ?>
       <? endif ?>
	</li>	 
     <? endfor ?>
     </ul>		  
  <? endif ?>

 <p><?= $this->count ?> match<? if ($this->count != 1): ?>es<? endif ?> found<? if ($this->count): ?>;
  displaying <?= $this->start + 1 ?> - <?= $this->end ?><? endif ?>
 </p>

<? endif ?>

  <?=  $this->render('browse/_facets.phtml'); ?>	       


<? foreach ($this->etds as $etd): ?>
  <?  $this->etd = $etd; ?>
  <?=  $this->render('view/shortrecord.phtml'); ?>
<? endforeach ?>
