<? if ($this->acl->isAllowed($this->role, $this->etd, "view history")): ?>
   <div id="history">
   <h2>History</h2>
      <? if (isset($this->etd->premis) && $this->etd->premis && 
	  $this->etd->premis->event[0]->identifier->value != ""): ?>
      <table class="history">
	 <? foreach (array_reverse($this->etd->premis->event) as $event): /* display most recent first */ ?>
        <tr>
        <td><?= date(DATE_RFC850, strtotime($event->date, 0))  ?></td>
          <td><?= $event->detail ?></td>
        </tr>    
        <? endforeach ?>
	 </table>
      <? else: ?>	     
        <p><i>No changes could be found.</i></p>
      <? endif ?>

   </div>
<? endif ?>
