<div class="fullrecord" >
    <? if ($this->etd->status() != "published"): ?>
     <p class="note">This record is not published. Current status: <b><?= $this->etd->status() ?></b></p>
    <? endif ?>

	<? if ($this->acl->isAllowed($this->role, $this->etd, "edit metadata")): ?>
<a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "title")) ?>">edit title</a>
   <? endif ?>
  <h1><?= $this->etd->html->title ?></a></h1>
 	<? if ($this->acl->isAllowed($this->role, $this->etd, "edit metadata")): ?>
<a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "record")) ?>">edit record</a>
   <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "faculty")) ?>">edit advisor & committee</a>

   <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "rights")) ?>">edit rights/restrictions</a>

   <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "researchfield")) ?>">edit research fields</a>
   <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "program")) ?>">edit program</a>
   <? endif ?>
  <?=  $this->render('view/summary.phtml'); ?>

  <h2>Abstract</h2>
  <? // FIXME: edit links for convenience; need to check if user has permission ?>
   	<? if ($this->acl->isAllowed($this->role, $this->etd, "edit metadata")): ?>
  <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "abstract")) ?>">edit</a>
     <? endif ?>
  <div id="abstract">
     <?= $this->etd->html->abstract ?>
  </div>

  <h2>Table of Contents</h2>
   	<? if ($this->acl->isAllowed($this->role, $this->etd, "edit metadata")): ?>
  <a class="action" href="<?= $this->url(array("controller" => "edit", "action" => "contents")) ?>">edit</a>
     <? endif ?>
  <div id="toc">
    <?= $this->etd->html->contents ?>
  </div>

     <? /* FIXME: make this a helper? */ 
function readable_size($size) {
$bytes = array('B','KB','MB','GB','TB');
  foreach($bytes as $val) {
   if($size > 1024){
    $size = $size / 1024;
   }else{
    break;
   }
  }
  return round($size, 1)." ".$val;
} ?>

     
  <?=  $this->render('view/_files.phtml'); ?>

</div>
