<?/* short record view  for an ETD (list/browse)
     expects $view->etd to be set with record to display.  */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user); ?>

<div class="listrecord">
    <b><a href="<?= $this->url(array("controller" => "view",
    "action" => "record", "pid" => $this->etd->pid()), "", true)?>"><?= $this->etd->title() ?></a></b> <br/>
  <?=  $this->render('manage/_actions.phtml'); ?>
  <?=  $this->render('view/summary.phtml'); ?>
  <? if ($this->show_status || $this->show_lastaction) : ?>
   <div class="record_status">
      <? if ($this->show_status): ?> 
       Current status: <b><?= $this->etd->status() ?></b><br/>
     <? endif ?>
     <? if ($this->show_lastaction): ?> 
       <? $last_event = $this->etd->premis->event[count($this->etd->premis->event) - 1]; ?>
       Last action: <?= $last_event->detail ?>
      (<?= date("Y-m-d", strtotime($last_event->date, 0))?>)<br/>
     <? endif ?>
   </div>
  <? endif ?>      
</div>
