<? /* summary ETD information - displayed in both full and short record views */ ?>

<?= $this->etd->author() ?> 
     <? if ($doctype = $this->etd->document_type()): ?>(<?= $doctype ?>)<? endif ?>
  <br/>

<b>Advisor:</b> <?= $this->etd->advisor() ?><br/>

<b>Committee members:</b> 
    <? foreach ($this->etd->committee() as $cm): ?>
	 <?= $cm ?>;
    <? endforeach ?>
    
    <? // nonemory committee not yet handled in etd interface... ?>
    <? if (isset($this->etd->mods->nonemory_committee) &&
	   isset($this->etd->mods->nonemory_committee[0]) && 
	   isset($this->etd->mods->nonemory_committee[0]->full)): ?>
      <? foreach ($this->etd->mods->nonemory_committee as $cm): ?>
         <?= $cm->full ?> (<?= $cm->affiliation ?>);
      <? endforeach ?> 
    <? endif ?>
    <? // linebreak only after both sets of committee members ?> <br/>
      
  <b>Research Fields:</b>
      <? $researchfields = $this->etd->researchfields(); ?>
    <? foreach ($researchfields as $field): ?>
    <?= $field ?> <? if ($field != $researchfields[count($researchfields)-1]): ?>; <? endif ?>
    <? endforeach ?><br/>
  <b>Keywords:</b>
    <? $keywords = $this->etd->keywords(); ?>
    <? foreach ($keywords as $keyword): ?>
         <?= $keyword ?> <? if ($keyword != $keywords[count($keywords)-1]): ?>; <? endif ?>
    <? endforeach ?><br/>
  <b>Program:</b> <?= $this->etd->program() ?>
     <? if ($this->etd->subfield()): ?>(<?= $this->etd->subfield() ?>)<? endif ?>
     <br/>
