<? /* summary ETD information - displayed in both full and short record views */ ?>

<?= $this->etd->author() ?> 
     (<?= $this->etd->document_type() ?>)<br/>

<b>Advisor:</b> <?= $this->etd->advisor() ?><br/>

<b>Committee members:</b> 
    <? foreach ($this->etd->committee() as $cm): ?>
	 <?= $cm ?>;
    <? endforeach ?>
    
    <? // nonemory committee not yet handled in etd interface... ?>
    <? if (isset($this->etd->mods->nonemory_committee)): ?>
      <? foreach ($this->etd->mods->nonemory_committee as $cm): ?>
         <?= $cm->full ?> (<?= $cm->affiliation ?>);
      <? endforeach ?> 
    <? endif ?>
    <? // linebreak only after both sets of committee members ?> <br/>
      
  <b>Research Fields:</b>
    <? foreach ($this->etd->researchfields() as $field): ?>
         <?= $field ?>;
    <? endforeach ?><br/>
  <b>Keywords:</b> 
    <? foreach ($this->etd->keywords() as $keyword): ?>
         <?= $keyword ?>;
    <? endforeach ?><br/>
  <b>Program:</b> <?= $this->etd->program() ?><br/>
