<?php

require_once("Fedora_API_Service_types.php");

/**
 * Fedora_API_M_Service class
 *
 * @author    auto-generated by wsdl2php
 */
class Fedora_API_M_Service extends SoapClient {

  private static $classmap = array(
                                    'describeRepository' => 'describeRepository',
                                    'describeRepositoryResponse' => 'describeRepositoryResponse',
                                    'getObjectProfile' => 'getObjectProfile',
                                    'getObjectProfileResponse' => 'getObjectProfileResponse',
                                    'listMethods' => 'listMethods',
                                    'listMethodsResponse' => 'listMethodsResponse',
                                    'listDatastreams' => 'listDatastreams',
                                    'listDatastreamsResponse' => 'listDatastreamsResponse',
                                    'getDatastreamDissemination' => 'getDatastreamDissemination',
                                    'getDatastreamDisseminationResponse' => 'getDatastreamDisseminationResponse',
                                    'getDissemination' => 'getDissemination',
                                    'parameters' => 'parameters',
                                    'getDisseminationResponse' => 'getDisseminationResponse',
                                    'findObjects' => 'findObjects',
                                    'findObjectsResponse' => 'findObjectsResponse',
                                    'resumeFindObjects' => 'resumeFindObjects',
                                    'resumeFindObjectsResponse' => 'resumeFindObjectsResponse',
                                    'getObjectHistory' => 'getObjectHistory',
                                    'getObjectHistoryResponse' => 'getObjectHistoryResponse',
                                    'ingest' => 'ingest',
                                    'ingestResponse' => 'ingestResponse',
                                    'modifyObject' => 'modifyObject',
                                    'modifyObjectResponse' => 'modifyObjectResponse',
                                    'getObjectXML' => 'getObjectXML',
                                    'getObjectXMLResponse' => 'getObjectXMLResponse',
                                    'export' => 'export',
                                    'exportResponse' => 'exportResponse',
                                    'purgeObject' => 'purgeObject',
                                    'purgeObjectResponse' => 'purgeObjectResponse',
                                    'addDatastream' => 'addDatastream',
                                    'addDatastreamResponse' => 'addDatastreamResponse',
                                    'describeUser' => 'describeUser',
                                    'describeUserResponse' => 'describeUserResponse',
                                    'modifyDatastreamByReference' => 'modifyDatastreamByReference',
                                    'modifyDatastreamByReferenceResponse' => 'modifyDatastreamByReferenceResponse',
                                    'modifyDatastreamByValue' => 'modifyDatastreamByValue',
                                    'modifyDatastreamByValueResponse' => 'modifyDatastreamByValueResponse',
                                    'setDatastreamState' => 'setDatastreamState',
                                    'setDatastreamStateResponse' => 'setDatastreamStateResponse',
                                    'setDatastreamVersionable' => 'setDatastreamVersionable',
                                    'setDatastreamVersionableResponse' => 'setDatastreamVersionableResponse',
                                    'compareDatastreamChecksum' => 'compareDatastreamChecksum',
                                    'compareDatastreamChecksumResponse' => 'compareDatastreamChecksumResponse',
                                    'getDatastream' => 'getDatastream',
                                    'getDatastreamResponse' => 'getDatastreamResponse',
                                    'getDatastreams' => 'getDatastreams',
                                    'getDatastreamsResponse' => 'getDatastreamsResponse',
                                    'getDatastreamHistory' => 'getDatastreamHistory',
                                    'getDatastreamHistoryResponse' => 'getDatastreamHistoryResponse',
                                    'purgeDatastream' => 'purgeDatastream',
                                    'purgeDatastreamResponse' => 'purgeDatastreamResponse',
                                    'getNextPID' => 'getNextPID',
                                    'getNextPIDResponse' => 'getNextPIDResponse',
                                    'getRelationships' => 'getRelationships',
                                    'getRelationshipsResponse' => 'getRelationshipsResponse',
                                    'addRelationship' => 'addRelationship',
                                    'addRelationshipResponse' => 'addRelationshipResponse',
                                    'purgeRelationship' => 'purgeRelationship',
                                    'purgeRelationshipResponse' => 'purgeRelationshipResponse',
                                    'ComparisonOperator' => 'ComparisonOperator',
                                    'Condition' => 'Condition',
                                    'Datastream' => 'Datastream',
                                    'DatastreamBindingMap' => 'DatastreamBindingMap',
                                    'dsBindings' => 'dsBindings',
                                    'DatastreamBinding' => 'DatastreamBinding',
                                    'DatastreamControlGroup' => 'DatastreamControlGroup',
                                    'DatastreamDef' => 'DatastreamDef',
                                    'FieldSearchQuery' => 'FieldSearchQuery',
                                    'conditions' => 'conditions',
                                    'FieldSearchResult' => 'FieldSearchResult',
                                    'resultList' => 'resultList',
                                    'ListSession' => 'ListSession',
                                    'MethodParmDef' => 'MethodParmDef',
                                    'MIMETypedStream' => 'MIMETypedStream',
                                    'header' => 'header',
                                    'ObjectFields' => 'ObjectFields',
                                    'ObjectMethodsDef' => 'ObjectMethodsDef',
                                    'methodParmDefs' => 'methodParmDefs',
                                    'ObjectProfile' => 'ObjectProfile',
                                    'objModels' => 'objModels',
                                    'Property' => 'Property',
                                    'RelationshipTuple' => 'RelationshipTuple',
                                    'RepositoryInfo' => 'RepositoryInfo',
                                    'passByRef' => 'passByRef',
                                    'passByValue' => 'passByValue',
                                    'datastreamInputType' => 'datastreamInputType',
                                    'userInputType' => 'userInputType',
                                    'defaultInputType' => 'defaultInputType',
                                   );

  public function Fedora_API_M_Service($wsdl = "http://localhost:8080/fedora/wsdl?api=API-M", $options = array()) {
    foreach(self::$classmap as $key => $value) {
      if(!isset($options['classmap'][$key])) {
        $options['classmap'][$key] = $value;
      }
    }
    parent::__construct($wsdl, $options);
  }

  /**
   *
   *
   * @param ingest $parameters
   * @return ingestResponse
   */
  public function ingest(ingest $parameters) {
    return $this->__soapCall('ingest', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param modifyObject $parameters
   * @return modifyObjectResponse
   */
  public function modifyObject(modifyObject $parameters) {
    return $this->__soapCall('modifyObject', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param getObjectXML $parameters
   * @return getObjectXMLResponse
   */
  public function getObjectXML(getObjectXML $parameters) {
    return $this->__soapCall('getObjectXML', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param export $parameters
   * @return exportResponse
   */
  public function export(export $parameters) {
    return $this->__soapCall('export', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param purgeObject $parameters
   * @return purgeObjectResponse
   */
  public function purgeObject(purgeObject $parameters) {
    return $this->__soapCall('purgeObject', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param addDatastream $parameters
   * @return addDatastreamResponse
   */
  public function addDatastream(addDatastream $parameters) {
    return $this->__soapCall('addDatastream', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param modifyDatastreamByReference $parameters
   * @return modifyDatastreamByReferenceResponse
   */
  public function modifyDatastreamByReference(modifyDatastreamByReference $parameters) {
    return $this->__soapCall('modifyDatastreamByReference', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param modifyDatastreamByValue $parameters
   * @return modifyDatastreamByValueResponse
   */
  public function modifyDatastreamByValue(modifyDatastreamByValue $parameters) {
    return $this->__soapCall('modifyDatastreamByValue', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param setDatastreamState $parameters
   * @return setDatastreamStateResponse
   */
  public function setDatastreamState(setDatastreamState $parameters) {
    return $this->__soapCall('setDatastreamState', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param setDatastreamVersionable $parameters
   * @return setDatastreamVersionableResponse
   */
  public function setDatastreamVersionable(setDatastreamVersionable $parameters) {
    return $this->__soapCall('setDatastreamVersionable', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param compareDatastreamChecksum $parameters
   * @return compareDatastreamChecksumResponse
   */
  public function compareDatastreamChecksum(compareDatastreamChecksum $parameters) {
    return $this->__soapCall('compareDatastreamChecksum', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param getDatastream $parameters
   * @return getDatastreamResponse
   */
  public function getDatastream(getDatastream $parameters) {
    return $this->__soapCall('getDatastream', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param getDatastreams $parameters
   * @return getDatastreamsResponse
   */
  public function getDatastreams(getDatastreams $parameters) {
    return $this->__soapCall('getDatastreams', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param getDatastreamHistory $parameters
   * @return getDatastreamHistoryResponse
   */
  public function getDatastreamHistory(getDatastreamHistory $parameters) {
    return $this->__soapCall('getDatastreamHistory', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param purgeDatastream $parameters
   * @return purgeDatastreamResponse
   */
  public function purgeDatastream(purgeDatastream $parameters) {
    return $this->__soapCall('purgeDatastream', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param getNextPID $parameters
   * @return getNextPIDResponse
   */
  public function getNextPID(getNextPID $parameters) {
    return $this->__soapCall('getNextPID', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param getRelationships $parameters
   * @return getRelationshipsResponse
   */
  public function getRelationships(getRelationships $parameters) {
    return $this->__soapCall('getRelationships', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param addRelationship $parameters
   * @return addRelationshipResponse
   */
  public function addRelationship(addRelationship $parameters) {
    return $this->__soapCall('addRelationship', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }

  /**
   *
   *
   * @param purgeRelationship $parameters
   * @return purgeRelationshipResponse
   */
  public function purgeRelationship(purgeRelationship $parameters) {
    return $this->__soapCall('purgeRelationship', array($parameters),       array(
            'uri' => 'http://www.fedora.info/definitions/1/0/api/',
            'soapaction' => ''
           )
      );
  }


  /**
   * Extending SoapClient::__doRequest to work around a php soap bug for null values;
   * Searching for fields that may be set to null (checksum, checksumType, dsLocation), and
   * fixing the xml to correctly set the soap value as null.
   */
  public function __doRequest($request, $location, $action, $version, $one_way = null)  {
    $rqst_dom = new DOMDocument();
    $rqst_dom->loadXML($request);
    $xpath = new DOMXPath($rqst_dom);

    // checksum and checksumType may be set to null; search for those fields with value NULL
    // dsLocation for modifyBinaryDatastream can also be null
    $nodelist = $xpath->query("//checksum[. = 'NULL']|//checksumType[. = 'NULL']|//dsLocation[.='NULL']");
    for ($i = 0; $i < $nodelist->length; $i++) {
      $node =  $nodelist->item($i);
      $node->nodeValue = "";	// remove the text content of the node
      // add xsi:nil=true
      $node->setAttributeNS("http://www.w3.org/2001/XMLSchema-instance",
          "xsi:nil", "true");
    }

    // update request from modified dom
    $request = $rqst_dom->saveXML();
    return parent::__doRequest($request, $location, $action, $version, $one_way);
  }


}
