<p><b>Congratulations!</b>  You have successfully submitted your ETD to Emory's
repository.</p>


<? if ($this->etd->schoolId() == "grad"): //Grad school ?>
<p>Remember to print the PDF version of your dissertation and submit a paper
copy to the Graduate School for the Dean's review.</p>

<p>You will receive an e-mail notification confirming whether or not
your thesis or dissertation has been approved by the Graduate School.  You may
check the status of your submission by viewing your record in <a
href="<?= $this->url(array('controller' => 'browse', 'action' => 'my'), '', true) ?>">My ETDs</a>.
Details regarding approval by the
Graduate School will appear in the History section of the record.</p>

<? else: //All other schools ?>
<p>Remember to submit all forms to the administration of your school or program.
You will receive an e-mail notification confirming whether or not your
thesis has been approved. You may check the status of your submission by
viewing your record in My <a href="<?= $this->url(array('controller' => 'browse', 'action' => 'my'), '', true) ?>">My ETDs</a>.
Details regarding approval will appear in the History section of the record.</p>
<? endif ?>
