<div id="files">
    <h2>Files</h2>
<? if ($this->etd->isEmbargoed()): ?>
    <p>Access restricted until <b><?= $this->etd->mods->embargo_end ?></b></p>
<? endif ?>       

     <? if ($this->acl->isAllowed($this->role, $this->etd, "add file")): ?>
       <p><a class="action" href="<?= $this->url(array("controller" => "file",
		"action" => "add", "etd" => $this->etd->pid), null, true)?>">add another file</a></p>
	  <? /* FIXME: only show this link if at least one category has more than one file */ ?>
	  <? if ($this->acl->isAllowed($this->role, $this->etd, "order files")
		 && (count($this->etd->pdfs) > 1 || count($this->etd->originals) > 1
		     || count($this->etd->supplements) > 1)): ?>
         <p><a class="action" href="<?= $this->url(array("controller" => "edit",
		"action" => "fileorder", "pid" => $this->etd->pid), null, true)?>">re-order files</a></p>
       <? endif ?>
     <? endif ?>					   


  <? foreach (array("pdfs", "originals", "supplements") as $filetype): ?>
     <?	 /* display a label for supplemental files, if appropriate */
       if ($filetype == "supplements" && count($this->etd->$filetype)
	   && $this->acl->isAllowed($this->role, $this->etd->{$filetype}[0], "view")): ?>
	    <b>Supplemental Files</b><br/><? endif ?>
    <? foreach ($this->etd->$filetype as $file) : ?>
      <? if ($this->acl->isAllowed($this->role, $file, "view")): ?>
	    <? if (isset($file->dc->mimetype)): ?>
		 <?= $this->FiletypeIcon($file->dc->mimetype) ?>
	     <? endif ?>
	     <? if ($this->acl->isAllowed($this->role, $file, "download")): ?>
		    <a href="<?= $this->url(array("controller" => "file", "action" => "view",
 				     "pid" => $file->pid))?>/<?= $file->prettyFilename() ?>"><?= $file->dc->title ?></a>
      	     <? else: /* view but not download */?>
		  <?= $file->dc->title ?>
	     <? endif ?>
	  <? if (isset($file->dc->pages)): ?><?= $file->dc->pages ?> pages<? endif ?>
	  <? if (isset($file->dc->filesize)): ?>(<?= $this->readableSize($file->dc->filesize) ?>) <?endif ?>						      
	   <? if ($file->dc->description): ?>
	    <span class="description">[<?= $file->dc->description ?>]</span>
          <?endif ?>
	      
	  <? if ($this->acl->isAllowed($this->role, $file, "edit")): ?>
	    <a href="<?= $this->url(array("controller" => "file", "action" => "edit", "pid" => $file->pid))?>">edit</a>
	  <? endif ?>
	  <? if ($this->acl->isAllowed($this->role, $file, "remove")): ?>
	    <a href="<?= $this->url(array("controller" => "file", "action" => "remove", "pid" => $file->pid))?>">remove</a>
	  <? endif ?>
	  <br/>
       <? endif /* can view file */ ?>
    <? endforeach ?>
  <? endforeach ?>
</div>
