<? /* full record view for an etd */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user); ?>
<? if (isset($this->etd->authorInfo) &&
       $this->acl->isAllowed($this->etd->authorInfo->getUserRole($this->current_user), "user", "view")): ?>
  <a href="<?= $this->url(array('controller' => 'user', 'action' => 'view',
	'pid' => $this->etd->authorInfo->pid), '', true) ?>">view user info</a>
<? endif ?>     

<? if ($this->etd->status() == "draft"): ?>
  <? /* if record is still a draft, show submission progress */ ?>
<div id="submission_status">
  <?=  $this->render('submission/_status.phtml'); ?>
</div>

 <div id="submission">
<? endif ?>

  <?=  $this->render('view/fullrecord.phtml'); ?>
<div class="fullrecord">
  <?=  $this->render('view/_history.phtml'); ?>
</div>

<? if ($this->etd->status() == "draft"): ?></div><? endif /* end submission div */?>
