<? /* full record view for an etd */ ?>
    <?// $acl = Zend_Registry::get('acl'); ?>
<? $this->acl = new Xml_Acl(); ?>
<?// $role =  (isset($this->view->current_user)) ? $this->view->current_user->netid : "guest"; ?>
<? $this->role = "author"; ?>
current role: <?= $this->role ?><br/>
resource: <?= $this->etd->getResourceId() ?><br/>
<!-- FIXME: how to get role with regard to etd ? -->

<? if ($this->etd->status() == "draft"): ?>
  <? /* if record is still a draft, show submission progress */ ?>
<div id="submission_status">
  <?=  $this->render('submission/_status.phtml'); ?>
</div>

 <div id="submission">
<? endif ?>

  <?=  $this->render('view/fullrecord.phtml'); ?>
<div class="fullrecord">
  <?=  $this->render('view/_history.phtml'); ?>
</div>

<? if ($this->etd->status() == "draft"): ?></div><? endif /* end submission div */?>
