<?/* short record view  for an ETD (list/browse)
     expects $view->etd to be set with record to display.  */ ?>
<? $this->role = $this->etd->getUserRole($this->current_user); ?>

<div class="listrecord">
    <b><a href="<?= $this->url(array("controller" => "view",
    "action" => "record", "pid" => $this->etd->pid()), "", true)?>"><?= $this->etd->title() ?></a></b> <br/>
  <?=  $this->render('manage/_actions.phtml'); ?>
  <?=  $this->render('view/summary.phtml'); ?>
</div>
