<?= $this->javascript("util.js"); ?>

<div style="padding:15px;border:1px solid grey;background-color:#efefef;">
<p><b>To:</b> <?= $this->etd->author() ?>
   (<i><?= $this->etd->authorInfo->mads->current->email ?>,
    <?= $this->etd->authorInfo->mads->permanent->email ?></i> )
   </p>


<form method="POST" action="<?= $this->url(array('action' => 'revert-to-draft')) ?>" onsubmit="disableButton('send')">
   <?= $this->formHidden("pid", $this->etd->pid()) ?>
   <?= $this->formHidden("type", $this->changetype) ?>
   <p><b><?= $this->formLabel("subject", "Subject:") ?></b>
   <?= $this->formText("subject", "ETD submission reverted to draft",
		       array("style" => "width:500px")) ?></p>

   <p>At your request your ETD submission has been changed to draft status.</p>
   <?= $this->render("email/_rqstchange_foot.phtml") ?>
   <p><?= $this->formSubmit("send", "Send >", array("class" => "button")) ?></p>
</form>

</div>