<h2>Submission marked for update</h2>

<p>A review of this record indicates that the <?= $this->changetype ?> should be reviewed
   and updated by the author. Please contact the author to inform him/her that changes
   need to be made before the submission process can be successfully completed.</p>

<p><b>Author name:</b> <i><?= $this->etd->author() ?></i></p>
<p><b>Email addresses:</b> <i><?= $this->etd->authorInfo->mads->current->email ?>,
   	<?= $this->etd->authorInfo->mads->permanent->email ?></i></p>

