<h1>Add file to record</h1>

<p><b><?= $this->etd->title() ?></b></p>

<p>Use the upload tool below to upload your original file or any
supplemental files you may wish to include with your document.  (The
tool also gives you the opportunity to continue uploading your thesis
or dissertation in PDF format if you are uploading your PDF in
multiple parts.)</p>

<p>The library is collecting original files for all theses and
dissertations.  For most users this will be a Microsoft Word file.
Note that this "original" file will be held for archival purposes
only; it will not be visible to repository users, nor will it be
downloadable.</p>

<p>You may also choose to upload supplemental files such as datasets,
audio or video, computer animation or other materials as an appendage
to your document.</p>

<form name="addfile" method="post" enctype="multipart/form-data"
    action="<?= $this->url(array("action" => "new", "etd" => $this->pid))?>">

   <p><b>Type of file to add:</b></p>
  <p><?= $this->formSelect("filetype", "", null,
			   array("original" => "Thesis/Dissertation in original format ",
				 "pdf" => "Thesis/Dissertation in PDF format",	
				 "supplement" => "Supplemental file")); ?> </p>
   
  <p><?= $this->formFile("file"); ?></p>

  
  <?= $this->formSubmit("Upload", "Upload"); ?>
</form>
