<p>record updated on <?= $this->save_result ?></p>

<p>committee ids - received in this order: </p>
<? foreach ($this->committee_ids as $cmid) : ?>
  <p><?= $cmid?></p>
<? endforeach ?>

<p><a href="<?= $this->url(array("controller" => "view", "action" => "record",
	"pid" => $this->etd->pid), null, true, false) ?>">return to record</a></p>

<pre>
  <?= htmlentities($this->etd->mods->saveXML()) ?>
</pre>