<h1>Policies and Procedures</h1>


<p>The Electronic Theses and Dissertations program is a joint project of the
  Emory Libraries, the Emory Graduate School, and Emory College. For all questions
  relating to graduation requirements and the preparation of your thesis or dissertation,
  please refer your questions to the Graduate School (or Emory College for undergraduate
  honors theses), or your individual graduate program (or undergraduate department).
  For questions regarding the electronic submission of your thesis or dissertation,
  please contact the Emory Library through our ETD listserv email:
  <a href="mailto:etd-admin@listserv.cc.emory.edu">etd-admin@listserv.cc.emory.edu</a>. </p>

  
<h3>I. Policies and Procedures for Graduate Students</h3>

<p>Please refer to the <a href="https://gs.emory.edu/resources/progress.php?id=7">Graduate
   School website</a> to see the prerequisites for graduation,
    instructions on preparing your theses and dissertations, links to necessary
    forms, and other useful resources. </p>
    
<h4>1. Access</h4>
<p>All students submitting an ETD will be able to choose either (1) "open
  access" meaning the full-text of their work will be available in Emory's
  repository immediately after graduation; or (2) "restricted access;" meaning
  the publication of their work will be delayed for a specific period of time.
  The current restricted access choices for authors are (i) six months, (ii)
  one year, (iii) two years, or (iv) six years. The<em> access restriction period
  expires automatically</em> after the end of access restriction period; it is
  the responsibility of the author to request an extension of the access restriction
  period if necessary. Such requests should be sent to:
  <a href="mailto:etd-admin@listserv.cc.emory.edu">etd-admin@listserv.cc.emory.edu</a>.</p>

  <p>The ETD repository was created by the university to increase access to the
  work of Emory Scholars. The University hopes that authors submitting their
  work here who chose to restrict access to their work will choose the shortest
  possible restriction period, taking into consideration the constraints of their
  individual situations and the demands of their particular academic field. We
  restate the Graduate School's statement on access issues:</p>
  
  <div style="border:3px double #666666;background-color:#CCCCCC;padding:15px">
    <h3>A Note on Access</h3>

  <p>The move to electronic theses and dissertation creates unparalleled opportunities
  for wide and timely dissemination of the work of Emory graduates, creating
  greater opportunities for your scholarly work to be recognized by others in
  your field.</p>
  
  <p>It also creates new parameters for copyright and publishing, and it is important
  that you make an informed decision about the terms of access to your dissertation
  or thesis. In particular, you need to learn about two issues:</p>

  <ol>
    <li>If your dissertation contains articles that were published in scholarly
     journals or elsewhere, you need to make sure that your terms of access are
     compatible with the permissions granted by those journals or other entities.</li>
  
    <li>If you plan to publish some or all of your dissertation/thesis, you need
     find out whether the journals and publishers who would be likely to publish
     your work regard an electronically accessible dissertation as a prior publication.</li>
  </ol>
  
  <p>The policies on both these issues vary widely across fields and publishers,
  and are changing fast. Take the time to investigate the conditions in your
  field, and make your decisions with accurate and up-to-date information, and
  in consultation with your advisor.</p>
  
  <p>The Library offers regular information sessions on copyright and intellectual
  property. You can find dates and times on the ETD website. Take advantage of
  these sessions to learn about issues that will be important throughout your
  scholarly career.</p>
</div>

  
<h4>2. Forms</h4>
<p>All authors must complete the
  <a href="<?= $this->linkTo("documents/ETD_Submission_Form.doc") ?>">ETD
   Submission Agreement Form</a>. All other required
  forms are available via the Graduate School website.</p>

<h4>3. Intellectual Property</h4>
<p>All theses and dissertations produced at Emory are the intellectual property
  of the authors. Authors may disseminate those works as they see fit, but they
  are also solely responsible for the contents of their thesis or dissertation.
  Please refer to our
   <a href="<?= $this->url(array('controller' => 'docs', 'action' => 'ip')) ?>">Intellectual
   Property page</a> for helpful information on author's
  rights and the use of previously copyrighted materials. All questions regarding
  patentable content in a thesis or dissertation should be referred to the
  <a href="http://www.ott.emory.edu/">Office of Technology Transfer</a> and your
  advisor.</p>

<h4>4. Patentable Material</h4>
 <p>If any of your work in your thesis or dissertation has patent implications,
  it is important that you not submit your work electronically. Please confer
  with your faculty advisors and/or <a href="http://www.ott.emory.edu/">Emory's
   Office of Technology Transfer</a>
  for guidance. Once the proper patent filings have been made, you may choose
  to proceed with your electronic submission.</p>
  <h4>5. Paper Copies</h4>
  <p>The library will no longer produce paper copies of theses and dissertations,
    and will not hold a copy on its shelves. The electronic copy will be the
    university's official copy of your work. Please contact your graduate program
    for information on their requirements on paper copies.</p>
  <p>See our information page on
  <a href="<?= $this->url(array('controller' => 'docs', 'action' => 'boundcopies')) ?>">Obtaining
  Bound Copies of Your Theses and Dissertations</a>
  for information on paper copies for your personal use.</p>
  <h4>6. Proquest</h4>
  <p>All doctoral dissertations will continue to be sent to Proquest where they
    will be made available under the terms set in their submission agreement.
    (See <a href="https://gs.emory.edu/resources/progress.php?id=7">Graduate School Website</a> for necessary paper forms.) Master's theses
    may be sent to proquest at the discretion of the author. Please be aware
    that
    most students should choose from one of the two "traditional publishing"
    options for Proquest. Proquest offers two "open access" options
    which give you an opportunity to place your work in their open access repository,
    a
    service offered without cost by Emory. (Students may choose to use the Proquest
    open access repository if they choose to do so, however, if they choose to
    pay the additional fee.)</p>
  <p>Proquest does not offer an access restriction period of greater than 2 years.
    If you choose Emory's six year option, it is your responsibility to see that
    Proquest is informed that you wish an embargo term of greater than two years.</p>
  <h3>II. Policies and Procedures for Undergraduate Students</h3><p>The program for Electronic Submission of Undergraduate Honors theses is still
    in the planning stage. Please refer back to this page for updates.
</p>
