<h1>About the web service</h1>

<p>This php web service retrieves an xml datastream from Fedora and then gives the user
just one part of it, according to the specified id.</p>

<p>The only method is <b>view</b>.</p>
<p>Required parameters are:</p>
<ul>
  <li><b>url</b> - full url to the specified fedora datastream.<br/>
 Note that if the url does not match a fedora datastream url OR if it does not appear to be the fedora that this site is configured to work with, processing will be aborted.</li>
  <li><b>id</b> - id attribute that identifies the portion of xml to be returned</li>
</ul>

<hr/>
<p>2009-10-20, Rebecca Sutton Koeser.</p>