<?= $this->javascript("projax/js/prototype.js"); ?>
<?= $this->javascript("projax/js/scriptaculous.js"); ?>

<? //php ajax/scriptaculous
include("projax/projax.php");
$projax = new Projax();

$ajaxopts = array("url" => $this->url(array("controller" => "search", "action" => "facultysuggestor"), "", true),
		  "indicator" => "chair-loading", "value" => "id", "select" => "value",
		  "after_update_element" => "setChair",
		  );
$inputopts = array("size" => "55", "autocomplete" => "off", "id" => "chair_autocomplete");
?>

<script language="Javascript" type="text/javascript">
  function setChair(text, li) {
  /* create a hidden input with faculty's netid, and display name */
      new Insertion.Bottom('chair_list', '<li id="'+li.id+'"><input type="hidden" name="chair[]" value="' + li.id + '"/>' + text.value + '<a class="remove" href="#" onClick="javascript:removeChair(\''+li.id+'\')">remove</a></li>');
      text.value = '';   // blank out suggestor for more entries
      Sortable.create("chair_list");
  }
  function addFaculty(text, li) {
    /* create a hidden input with faculty's netid, and display name */
    new Insertion.Bottom('faculty_list', '<li id="' + li.id +'"><input type="hidden" name="committee[]" value="' + li.id + '"/>' + text.value + '<a class="remove" href="#" onClick="Element.remove(\''+li.id+'\')">remove</a></li>');

    // make the faculty list sortable (needs to be updated when new fields are added)
    Sortable.create("faculty_list");
    text.value = '';	// blank out suggestor for more entries
  }
 function removeChair(id) { Element.remove(id); Element.show("chair_autocomplete"); }

function addNonemory() {
  nonemory_count++;	// unique id for remove link
  new Insertion.Bottom('nonemory_list', "<tr id='nonemory_" + nonemory_count + "'>\n" +
    "\t<td><input type='text' name='nonemory_firstname[]'></td>\n" +
    "\t<td><input type='text' name='nonemory_lastname[]' ></td>\n" +
    "\t<td><input type='text' name='nonemory_affiliation[]' ></td>\n" +
    "\t<td><a href='#' onClick=\"Element.remove('nonemory_" + nonemory_count + "')\">remove</a>\n" + 
    "</tr>");
}
</script>


<h1>Edit Committee Chair(s) &amp; Members</h1>
<p><b><?= $this->etd->title() ?></b></p>


<p>Your PDF submission indicates that the following faculty members
comprise your committee chair(s) and members.  If any of the selections are
incorrect, click on remove and re-enter the name in the box provided.
The name should appear from the suggestor. If you have any Non-Emory Committee
Members, select yes below and you will be provided with boxes to enter their names and
affiliation.  You may rearrange the order of your committee by
clicking on and dragging the names.</p>
<p> Enter last name of faculty member(s) below and <b>wait a moment</b> while the system retrieves names.</p>

<div id="edit_faculty">
<? $chairs = $this->etd->mods->chair; ?>
<? $committeeMembers = $this->etd->mods->committee; ?>

<form method="post" id="fields_form"  action="<?= $this->url(array("action" => "savefaculty"))?>">
  <h2>Committee Chair(s)</h2>
  <ul id="chair_list">
    <? foreach ($chairs as $chair): ?>
     <? if ($chair->id) : ?>
       <li id="<?= $chair->id ?>"><input type="hidden" name="chair[]" value="<?= $chair->id ?>"/>
	  <?= $chair->full ?>
	  <a class="remove" href="#" onClick="javascript:removeChair('<?= $chair->id ?>')">remove</a>
       </li>
     <? endif ?>
     <? endforeach ?>
   </ul>
  <? if (count($chairs) > 1): ?>
      <?= $projax->sortable_element("chair_list", array("url" => null)); ?>     
  <? endif ?>	      
	  
	  <div id="chair_autocomplete">
      <?=  $projax->text_field_with_auto_complete('advisor', $inputopts, $ajaxopts); ?>
	<span id="chair-loading" style="display:none;">Searching...</span>
    </div>
    <hr/>
   <h2>Committee Members</h2>
   <ul id="faculty_list">
     <? foreach ($committeeMembers as $committee): ?>
	<? if ($committee->id) : ?>
	   <li id="<?= $committee->id ?>">
	      <input type="hidden" name="committee[]" value="<?= $committee->id ?>"/>
	      <?= $committee->full ?>
	      <a class="remove" href="#" onClick="Element.remove('<?= $committee->id ?>')">remove</a>
	<? endif ?>
     <? endforeach ?>	
   </ul>

  <? if (count($committeeMembers) > 1): ?>
      <?= $projax->sortable_element("faculty_list", array("url" => null)); ?>     
  <? endif ?>	      
 
<? $ajaxopts["after_update_element"] = "addFaculty"; $ajaxopts["indicator"] = "cm-loading"; ?>
<?= $projax->text_field_with_auto_complete('faculty', $inputopts, $ajaxopts); ?>
     <span id="cm-loading" style="display:none;">Searching...</span>

 <hr/>
 <? if (count($this->etd->mods->nonemory_committee) > 1 || 
	(isset($this->etd->mods->nonemory_committee[0]) &&
	 $this->etd->mods->nonemory_committee[0]->first != "")) {
	  $has_nonemory = true;
	} else {
	  $has_nonemory = false;
	}
?>

<? if (! $has_nonemory): ?>     
  <p>Do you have any Non-Emory Committee Members?
     <a class="button" onClick="Element.show('nonemory')">yes</a> 
     </p>
<? endif ?>
     
 <div id="nonemory" <? if (! $has_nonemory): ?> style="display:none" <? endif ?> >     
 <h2>Non-Emory Committee Members</h2>
<table>
<tbody id="nonemory_list">						       
     <? $ne_count = 0; ?>
     <tr><th>Last name</th> <th>First name</th> <th>Affiliation</th></tr>
     <? foreach ($this->etd->mods->nonemory_committee as $ne) : ?>
       <tr id="nonemory_<?= ++$ne_count; ?>">
     <td><?= $this->formText("nonemory_lastname[]", $ne->last); ?></td>
     <td><?= $this->formText("nonemory_firstname[]", $ne->first); ?></td>
     <td><?= $this->formText("nonemory_affiliation[]", $ne->affiliation); ?></td>
     <td><a href="#" onClick="Element.remove('nonemory_<?= $ne_count ?>')">remove</a>
       </tr>
     <? endforeach ?>
   <tr id="nonemory_<?= ++$ne_count; ?>">
     <td><?= $this->formText("nonemory_lastname[]"); ?></td>
     <td><?= $this->formText("nonemory_firstname[]"); ?></td>
     <td><?= $this->formText("nonemory_affiliation[]"); ?></td>
     <td><a href="#" onClick="Element.remove('nonemory_<?= $ne_count ?>')">remove</a>
   </tr>
 <tbody>						       
</table>
<? /* pass the count to the javascript so inserted nodes can have unique ids for removal */ ?>
<script type="text/javascript">var nonemory_count = <?= $ne_count ?>; </script>		       
<a href="#" onClick="javascript:addNonemory()">add another</a>
</div>
     
<p><input class="button" type="submit" value="save"/></p>
</form>
						       
</div>


