<p>You should proceed by making the changes to your document,
   creating a new PDF, and then uploading the new version.
   When you are ready to upload the new version, go to your ETD
   record's main edit page, and use the "Replace a File" function
   located in the files section of that page. This function will replace
   your original PDF file so there is no need for you to delete it.</p>

<p>For your convenience, here is a direct link to your record:
  <a href="<?= $this->etd->ark() ?>"><?= $this->etd->ark() ?></a></p>