<h1>Contact Information for <?= $this->authorInfo->mads->name->first ?> <?= $this->authorInfo->mads->name->last ?></h1>
<?=  $this->render('author-info/_view.phtml'); ?>

<? if ($this->acl->isAllowed($this->authorInfo->getUserRole($this->current_user), "authorInfo", "edit")): ?>
<p><a class="button" href="<?= $this->url(array("controller" => "authorInfo",
		 "action" => "edit", "pid" => $this->authorInfo->pid), null, true) ?>">edit</a></p>
<? endif ?>

<? /* fall-back logic for newly created authorInfo with syncUpdates turned off - if etd is not acccessible
   via related object (which queries the RIsearch), use the pid stored in the rels ext */ ?>
<? $etd_pid = $this->authorInfo->etd ? $this->authorInfo->etd->pid : str_replace('info:fedora/', '', $this->authorInfo->rels_ext->etd); ?>
<a class="button" href="<?= $this->url(array('controller' => 'view', 'action' => 'record',
	'pid' => $etd_pid), '', true, false)?>">return to record &gt;</a><br/>
