<h1>Edit File Information</h1>

<p>Review and update the file description below.  PDF and supplemental files will be listed on your public ETD record based on this information, after your embargo (if any) has expired. When you are satisfied, click save to proceed.</p>

 <?=  $this->render('edit/_form_key.phtml'); ?>

<? if (isset($this->errors)): ?> <!-- validation errors -->
<ul class="errors">
   <? foreach ($this->errors as $error):  ?>
      <li><?= $error ?></li>
    <? endforeach  ?>
</ul>
<? endif ?>


<form id="file-metadata" method="post"
   action="<?= $this->url(array('action' => 'edit', 'pid' => $this->etdfile->pid))?>" >
   <div>
     <label for="title" class="required
       <?= array_key_exists('title', $this->errors) ? 'invalid' : ''?>">Title</label>
     <?= $this->formText("title", $this->etdfile->dc->title); ?>
     <p class="help-text">Display label for this document as it should
   	be listed on your ETD record.</p>
   </div>

   <div>
     <label for="author">Author</label>
     <?= $this->formText("creator", $this->etdfile->dc->creator); ?>
     <p class="help-text">Name of the person who created the contents of this file.</p> 
   </div>

   <div>
     <label for="description">Description</label>
     <?= $this->formTextarea("description", $this->etdfile->dc->description); ?>
   <p class="help-text">Brief description of the file, for display on your ETD record.</p> 
   </div>

   <div>
     <label for="type" class="required
       <?= array_key_exists('type', $this->errors) ? 'invalid' : ''?>">Type</label>
     <?= $this->formSelect("type", $this->etdfile->dc->type, array(),
     	  $this->type_options); ?>
  <p class="help-text">Type of content; be sure to update for supplemental files such
                                        as videos or datasets.</p> 
   </div>

  <label>Other file information</label>
  <p>
    <? if (isset($this->etdfile->file->mimetype)):  ?>
      <?= $this->FiletypeIcon($this->etdfile->file->mimetype) ?>
    <? endif ?>
   <?= $this->readableSize($this->etdfile->dc->filesize) ?>
   <? if (isset($this->etdfile->dc->pages)):  ?>
     ; <?= $this->etdfile->dc->pages ?> pages.
    <? endif ?>
  </p>

  <?= $this->formSubmit("Save", "Save", array("class" => "button")); ?>
</form>