<h1>Edit File Information</h1>
<?=  $this->render('edit/_xforms_key.phtml'); ?>

<?= $this->xformText("title", "dc:title"); ?> <br/>
<?= $this->xformText("author", "dc:creator"); ?> <br/>
<?= $this->xformTextarea("description", "dc:description"); ?> <br/>

<? /* these are set on upload and should not be editable by the user */ ?>
<?= $this->xformOutput("file type", "dc:format[contains(., '/')]"); ?> <br/>
<?= $this->xformOutput("pages", "dc:format[contains(., 'p.')]"); ?> <br/>
<?= $this->xformOutput("file size (in bytes)", "dc:format[not(contains(., '/')) and not(contains(., 'p.'))]"); ?> <br/>


 <xf:submit submission="submission">
<xf:label>Save</xf:label>
</xf:submit>





<p>upload a new version of this file (if desired)</p>

<form name="updatefile" method="post" enctype="multipart/form-data"
    action="<?= $this->url(array("action" => "update", "etd" => $this->pid))?>">
  <p><?= $this->formFile("file"); ?>
     <?= $this->formSubmit("Upload", "Upload"); ?>
  </p>
</form>


<? if ($this->env == 'development'): ?>
  <p id="status"></p>
<? endif ?>   
