<? /* secondary xml instances used for data, choices, etc. */ ?>
<xf:instance id="languages" xmlns="" src="<?= $this->url(array("controller" => "config", "action" => "view",
 "id" => "languages"), "", true) ?>"/>
<xf:instance id="degrees" xmlns="" src="<?= $this->url(array("controller" => "config", "action" => "view",
 "id" => "degrees"), "", true) ?>"/>
<xf:bind nodeset="mods:name/mods:displayForm" type="xsd:string"
   calculate="concat(../mods:namePart[@type='family'], ', ', ../mods:namePart[@type='given'])"/>
    
<xf:bind nodeset="mods:extension/etd:degree/etd:level" type="xsd:string" calculate="concat(instance('degrees')/level[degree/@name = instance('main')/mods:extension/etd:degree/etd:name]/@name, ' (', ../etd:name, ') ')"/>
 <xf:bind nodeset="mods:extension/etd:degree/etd:name" type="xsd:string" constraint=". != 'select one' and . != ''"
   	required="true()"/>
   <? /* at least one keyword - so only require the first one */ ?>
 <xf:bind nodeset="mods:subject[@authority='keyword']/mods:topic[position() = '1']" type="xsd:string" required="true()"/> 
 <xf:bind nodeset="mods:language/mods:languageTerm" type="xsd:string" required="true()"/>
 <xf:bind nodeset="mods:name[mods:role/mods:roleTerm='author']/mods:namePart" type="xsd:string" required="true()"/>
   
 <?/* FIXME: seems like a hack; can't get degree genre without including etd:level in the expression */ ?>
<xf:bind nodeset="mods:genre" type="xsd:string" calculate="substring-before(concat(instance('degrees')/level[contains(instance('main')/mods:extension/etd:degree/etd:level, @name)]/@genre, ' ... ', instance('main')/mods:extension/etd:degree/etd:level), ' ...')"/> 

   
<xf:submission id="submission" action="<?= $this->url(array('action' => 'savemods', 'id' => $this->pid))?>"
		method="post" />
   
<xf:message level="modal"
   ev:event="xforms-submit-error">Error: check that all required fields are filled in correctly</xf:message>
		       

      
