<? /* secondary xml instances used for data, choices, etc. */ ?>
<xf:instance id="languages" xmlns=""><? include('../config/languages.xml'); ?></xf:instance>
<xf:instance id="tmp-data" xmlns="">
   <tmp-data>
    <non-emory-faculty><?= ($this->etd->mods->nonemory_committee[0]->last == "") ? "false" : "true" ?></non-emory-faculty>
   </tmp-data>
</xf:instance>
<xf:bind nodeset="mods:name/mods:displayForm" type="xsd:string"
	calculate="concat(../mods:namePart[@type='family'], ', ', ../mods:namePart[@type='given'])"/>

<xf:bind nodeset="mods:name[mods:description = 'Non-Emory Committee Member']"
    relevant="instance('tmp-data')/non-emory-faculty = 'true'"/> 


<xf:submission id="submission" action="<?= $this->url(array('action' => 'savemods', 'id' => $this->pid))?>"
		method="post" />
