<xf:instance id="tmp" xmlns="">
   <tmp>
     <copyright><?= $this->etd->mods->copyright ?></copyright>
     <embargo><?= $this->etd->mods->embargo_request ?></embargo>
   <agreement><?= $this->etd->mods->hasSubmissionAgreement() ? "yes" : "" ?></agreement>
     <rights id="yes">I hereby grant to Emory University and its agents the non-exclusive license to archive, make accessible, and display, (subject to the conditions agreed upon in the separate written agreement I have submitted to the graduate school,) my thesis or dissertation in whole or in part in all forms of media, now or hereafter known, including the display of the thesis or dissertation on the world wide web. I retain all ownership rights to the copyright of the thesis or dissertation. I also retain the right to use in future works (such as articles or books) all or part of this thesis or dissertation. I certify that my electronic submission is the version of my thesis/dissertation that was approved by my committee.</rights>
     <rights id="no"/>
   </tmp>
</xf:instance>

<?/* use yes/no temporary settings for copyright, embargo, and submission agreement;
    once they are set, calculate or set the real fields based on  them
   */ ?>
<xf:bind nodeset="instance('tmp')/*" required="true()"/> 
   
<xf:bind nodeset="mods:note[@ID='embargo']" type="xsd:string" calculate="concat('embargo requested? ', instance('tmp')/embargo)"/>
<xf:bind nodeset="mods:note[@ID='copyright']" type="xsd:string" calculate="concat('applying for copyright? ', instance('tmp')/copyright)"/> 

<xf:submission id="submission" action="<?= $this->url(array('action' => 'savemods',
	'id' => $this->pid, "log" => "modified copyright, embargo, access rights"))?>"
   method="post" />


