<xf:instance id="tmp" xmlns="">
   <tmp>
     <copyright><?= $this->etd->mods->copyright ?></copyright>
     <embargo><?= $this->etd->mods->embargo_request ?></embargo>
    <agreement><?= $this->etd->mods->hasSubmissionAgreement() ? "yes" : "" ?></agreement>
     <rights id="yes">I hereby grant to Emory University and its agents the non-exclusive license to archive, make accessible, and display, (subject to the conditions agreed upon in the separate written agreement I have submitted to the graduate school,) my thesis or dissertation in whole or in part in all forms of media, now or hereafter known, including the display of the thesis or dissertation on the world wide web. I retain all ownership rights to the copyright of the thesis or dissertation. I also retain the right to use in future works (such as articles or books) all or part of this thesis or dissertation. I certify that my electronic submission is the version of my thesis/dissertation that was approved by my committee.</rights>
     <rights id="no"/>
     <ask_pq_submit/>
     <ask_copyright/>
   </tmp>
</xf:instance>

<?/* use yes/no temporary settings for copyright, embargo, and submission agreement;
    once they are set, calculate or set the real fields based on  them
   */ ?>
<xf:bind nodeset="instance('tmp')/*" required="true()"/>
   
<xf:bind nodeset="mods:note[@ID='embargo']" type="xsd:string" calculate="concat('embargo requested? ', instance('tmp')/embargo)"/>
<xf:bind nodeset="mods:note[@ID='copyright']" type="xsd:string" calculate="concat('registering copyright? ', instance('tmp')/copyright)"/> 

<? /* submit to PQ optional for masters */ ?>
<xf:bind id="pq_submit" nodeset="instance('tmp')/ask_pq_submit" relevant="instance('main')/mods:extension/etd:degree/etd:name != 'PhD'"/>
<? /* if degree is PhD, will submit to PQ - no need to prompt */ ?>
<xf:bind nodeset="mods:note[@ID='pq_submit']" type="xsd:string" required="true()"/>
   <? /*   calculate="if(mods:extension/etd:degree/etd:name = 'PhD', 'yes', '')"/>  */ ?>

<!-- FIXME: only ask about copyright if they are actually submitting to proquest  -->
<xf:bind id="ask_copyright" nodeset="instance('tmp')/ask_copyright"
	 relevant="instance('main')/mods:note[@ID='pq_submit'] = 'yes'"/>  
<xf:submission id="submission" 
	       action="<?= $this->url(array('action' => 'savemods',
		       'id' => $this->pid, "component" => "copyright, embargo, and access rights"))?>"
	       method="post" />

<xf:message level="modal"
   ev:event="xforms-submit-error">Error: check that all required fields are filled in correctly</xf:message>
