<? include "js/FCKeditor/fckeditor.php"; ?>

<h1>Edit <?= $this->mode_label ?></h1>
<p><b><?= $this->etd->title() ?></b></p>

<p><b>If you are using special/foreign language characters</b>
please use the special character <?= $this->img("images/fck_specialchar.gif") ?> 
or universal keyboard <?= $this->img("js/FCKeditor/editor/plugins/Jsvk/img/jsvk.gif") ?> tools.
The system may not accept special characters imported using a cut-and-paste
function from your processor, so we recommend that you insert these special
characters using the tools provided.</p>

<p><b>If you are copying and pasting from Microsoft Word</b> please use the
paste from Word tool <?= $this->img("images/fck_pasteword.gif") ?>.  If special
characters are causing problems, please use the paste as plain text tool
<?= $this->img("images/fck_pastetext.gif") ?>.

<form name="edit" method="post"
    action="<?= $this->url(array("action" => "save" . ucfirst($this->mode), "mode" => $this->mode))?>">
<? /* configuration options for FCK editor */ 
$editor_opts = array("config" => (string)$this->linkTo("js/FCKconfig.js"),
			    "height" => "400", "toolbar" => "etd" );
if ( $this->mode == "title") {
  $editor_opts["toolbar"] = "etd-title";
  $editor_opts["height"] = "etd-title";
} elseif ($this->mode == "abstract") {
  $editor_opts["BodyId"] = "abstract";
}

$editor_opts["css"] = $this->linkTo("css/etd.css");
if ($this->current_user->role == "superuser") $editor_opts["toolbar"] = "etd-admin";
?>

<?= $this->FckEditor("edit_content", (string)$this->edit_content, $editor_opts) ?>

<?= $this->formSubmit("Save", "Save", array("class" => "button")); ?>
</form>
