<? include "fckeditor/fckeditor.php"; ?>

<h1><?= $this->etd_title ?></h1>

<p>edit <?= $this->mode ?></p>

<form name="edit" method="post"
    action="<?= $this->url(array("action" => "save" . ucfirst($this->mode), "mode" => $this->mode))?>">

<?php
$oFCKeditor = new FCKeditor("edit_content");
$oFCKeditor->BasePath = "/~rsutton/fckeditor/";
$oFCKeditor->Value = (string)$this->edit_content;
//$oFCKeditor->Config["CustomConfigurationsPath"] = "/myconfig.js"  ;

$oFCKeditor->Config["CustomConfigurationsPath"] = (string)$this->linkTo("js/FCKconfig.js");
$oFCKeditor->ToolbarSet = 'Basic';
if ($this->mode == "title") {
  $oFCKeditor->Height = '200';
  $oFCKeditor->ToolbarSet = "etd-title";
} else {
  $oFCKeditor->Height = '400';
  $oFCKeditor->ToolbarSet = "etd";
}
$oFCKeditor->Create();
?>

  <?= $this->formSubmit("Save", "Save"); ?>
</form>

<? /* preview doesn't really work - to be useful it needs to be updated/dynamic 
<h2>Preview:</h2>
<div class="fullrecord">
  <!-- <h1><?//= $this->edit_content ?></h1> -->
  <div id="<?= $this->mode ?>">
    <?= $this->edit_content ?>
  </div> 
</div>
*/ ?>