<!--
fixme: bindings need to go into header with model... how to get them there? 

<xf:bind id="fullname" nodeset="/mods:name[@type='personal']/mods:displayForm" 
   calculate="concat(../mods:namePart[@type='family'], ', ', ../mods:namePart[@type='given'])"/>
   <xf:bind nodeset="mods:name/mods:displayForm" type="xsd:string"
	calculate="concat(../mods:namePart[@type='family'], ', ', ../mods:namePart[@type='given'])"/>

		       
<xf:submission id="submission" action="<?= $this->url(array('action' => 'savemods', 'id' => $this->etd->pid))?>"
		method="post" /> -->

			       <?/*-		       includenamespaceprefixes="v"  */?>
			       <?/*=  $this->render('xforms-head.phtml'); */?>

      
<h1>edit thesis information</h1>

<!-- fixme: figure out some way to hide this until form is loaded -->

<?//= $this->xformTextarea("Title", "mods:titleInfo/mods:title"); ?>
 <?= $this->xformOutput("Title", "mods:titleInfo/mods:title"); ?>
 <br/>

 <xf:group ref="mods:name[mods:role/mods:roleTerm='author']">
    <xf:label>author</xf:label>
    <?=  $this->render('edit/_mods_name.phtml'); ?>
    <?/* note: department now edited on separate page */ ?>
    <?//= $this->xformOutput("Department", "mods:affiliation"); ?>
 </xf:group>
 <br/>

 <xf:group ref="mods:name[mods:role/mods:roleTerm='Thesis Advisor']">
    <xf:label>advisor</xf:label>
     <?=  $this->render('edit/_mods_name.phtml'); ?>
 </xf:group>

  <br/>

 <p><u>committee members</u></p>
 <xf:repeat id="repeat-committee" nodeset="mods:name[mods:description='Emory Committee Member']">
    <xf:label>committee members</xf:label>
     <?=  $this->render('edit/_mods_name.phtml'); ?>
   <br/>
 </xf:repeat>
 
  <xf:trigger>
        <xf:label>Add</xf:label>
        <xf:action ev:event="DOMActivate">
          <xf:insert nodeset="mods:name[mods:description='Emory Committee Member']" at="last()" position="after"/>
          <xf:setvalue ref="mods:name[mods:description='Emory Committee Member']/mods:namePart[@type='family']" value="''"/>
             <xf:setvalue ref="mods:name[mods:description='Emory Committee Member']/mods:namePart[@type='given']" value="''"/>
        </xf:action>
      </xf:trigger>
      
      <xf:trigger>
        <xf:label>Remove</xf:label>
        <xf:delete ev:event="DOMActivate" nodeset="mods:name[mods:description='Emory Committee Member']" at="last()"/>
      </xf:trigger>

  <p><u>non-emory committee members</u></p>

  <xf:select1 ref="instance('tmp-data')/non-emory-faculty">
   <xf:label>committee includes non-emory faculty?</xf:label>
     <xf:item><xf:label>no</xf:label><xf:value>false</xf:value></xf:item>
     <xf:item><xf:label>yes</xf:label><xf:value>true</xf:value></xf:item>
  </xf:select1>
 <br/>
      
 <xf:repeat id="repeat-nonemory-committee" nodeset="mods:name[mods:description='Non-Emory Committee Member']">
     <?=  $this->render('edit/_mods_name.phtml'); ?>
     <?= $this->xformText("Affiliation", "mods:affiliation"); ?>
     <br/>
 </xf:repeat>


  <xf:trigger id="nonemory-add">
        <xf:label>Add</xf:label>
        <xf:action ev:event="DOMActivate">
          <xf:insert ref="mods:name[mods:description='Non-Emory Committee Member']" at="last()" position="after"/> 
          <xf:setvalue ref="mods:name[mods:description='Non-Emory Committee Member']/mods:namePart[@type='family']" value="''"/>
          <xf:setvalue ref="mods:name[mods:description='Non-Emory Committee Member']/mods:namePart[@type='given']" value="''"/>
          <xf:setvalue ref="mods:name[mods:description='Non-Emory Committee Member']/mods:affiliation[last()]" value="''"/> 
        </xf:action>
      </xf:trigger>
      
      <xf:trigger>
        <xf:label>Remove</xf:label>
        <xf:delete ev:event="DOMActivate" nodeset="mods:name[mods:description='Non-Emory Committee Member']" at="last()"/>
      </xf:trigger>  
    
    <br/>
 
<!-- title/abstract/toc really should not be edited here -->
 <?//= $this->xformTextarea("Abstract", "mods:abstract"); ?>
      <!-- <?//= $this->xformOutput("Abstract", "mods:abstract"); ?>
 <br/> -->

 <?//= $this->xformTextarea("Contents", "mods:tableOfContents"); ?>
      <!-- <?//= $this->xformOutput("Contents", "mods:tableOfContents"); ?>
 <br/> -->

  <xf:select1 ref="mods:language/mods:languageTerm[@type='text']">
   <xf:label>language</xf:label>
   <xf:itemset nodeset="instance('languages')/language">
     <xf:label ref="@display"/><xf:value ref="@text"/>
   </xf:itemset>
  </xf:select1>
 <br/>

 <?/*  umi/proquest research fields edited separately */ ?>

  <p><u>keywords</u></p>
  <xf:repeat id="repeat-keywords" nodeset="mods:subject[@authority='keyword']">
   <?= $this->xformText("", "mods:topic"); ?>
   <br/>
  </xf:repeat>

  <xf:trigger>
      <xf:label>Add</xf:label>
      <xf:action ev:event="DOMActivate">
        <xf:insert nodeset="mods:subject[@authority='keyword']" at="last()" position="after"/>
        <xf:setvalue ref="mods:subject[@authority='keyword']/mods:topic[last()]" value="''"/>
       </xf:action>
     </xf:trigger>
      
    <xf:trigger>
      <xf:label>Remove</xf:label>
      <xf:delete ev:event="DOMActivate" nodeset="mods:subject[@authority='keyword']" at="last()"/>
    </xf:trigger>
<br/>

  <xf:select1 ref="mods:extension/etd:degree/etd:name">
   <xf:label>degree</xf:label>
   <xf:itemset nodeset="instance('degrees')/level/degree">
     <xf:label ref="@name"/><xf:value ref="@name"/>
   </xf:itemset>
  </xf:select1>

  <?= $this->xformText("degree level", "mods:extension/etd:degree/etd:level"); ?>
  <?= $this->xformText("thesis type", "mods:genre"); ?>
  <br/>


  <? $yesno = array(" " => "--", "no" => "no", "yes" => "yes"); ?>
 
  <?= $this->xformSelect("access restriction (embargo)", "instance('tmp-data')/embargo", $yesno); ?>
  Choose 'Yes' to indicate you want an access restriction or 'No' to indicate that your ETD can be published immediately after graduation. <b>NOTE:</b> requests for an access restriction must be made on the paper ETD Submission Agreement Form which you will present to the Graduate School for approval.<br/>

  <?= $this->xformSelect("apply for copyright?", "instance('tmp-data')/copyright", $yesno); ?>
  Indicate 'Yes' if you intend to have Proquest apply for copyright on your behalf. (See Proquest/UMI Publishing Agreement, page 5.)<br/>

 <xf:submit submission="submission">
<xf:label>Save</xf:label>
</xf:submit>

<? if ($this->site_mode == 'development'): ?>
  <p id="status"></p>
<? endif ?>   

