<h1>Edit Program/Department</h1>
<p><b><?= $this->etd->title() ?></b></p>
<p>Your Emory record indicates that your degree is in the following Program or Department.</p>

<p>If this information is incorrect, select your program below from the supplied list.
  <? if ($this->etd->schoolId() == "grad"): /** currently ONLY the graduate school has subfields */ ?>   
  If your program has an applicable subfield, please select that as well.
  <? endif ?>
</p> 

<form action="<?= $this->url(array("action" => "save-program")) ?>" method="post">
			    
<div>
<b>Department/Program <? if ($this->etd->isRequired("program")): ?> * <? endif ?></b><br/>
  <input id="program_id" name="program_id" type="hidden"
    value="<?= isset($this->etd->rels_ext->program) ? $this->etd->rels_ext->program : "" ?>"/>
   <span id="program_label"><?= $this->etd->mods->department ?></span>
</div>
  
 <div id="subfield_form"
    <? if ($this->etd->schoolId() != "grad"): /** currently ONLY the graduate school has subfields */ ?>
       style="display:none"
    <?endif ?>    > 
  <b>Subfield</b><br/>
   <input id="subfield_id" name="subfield_id" type="hidden"
     value="<?= isset($this->etd->rels_ext->subfield) ? $this->etd->rels_ext->subfield : "" ?>"/>
	 <span id="subfield_label"><?= $this->etd->mods->subfield ?></span><br/>
 </div>

<p><input class="button" type="submit" value="save"/></p>
</form>

<script language="JavaScript">
function setProgram(id, label) {
  $('program_id').value = id;
  // get label from display field on the page
  $('program_label').innerHTML = $(id + '_label').innerHTML;
  //  clear highlighting from any previously selected programs
  var selected = $$(".selected");
  for (var i = 0; i < selected.length; i++) {
    selected[i].removeClassName('selected');
  }
  // highlight currently selected program
  $(id).addClassName('selected');

  // clear out any subfield
  $('subfield_id').value = '';
  $('subfield_label').innerHTML = '';
}

function setSubfield(id, parent_id) {
  setProgram(parent_id);
  $('subfield_id').value = id;
  // get label from display field on the page
  $('subfield_label').innerHTML = $(id + '_label').innerHTML;

  // set current subfield as selected
  $(id).addClassName('selected');
}
</script>


<ul id="select_program">
  <? if (isset($this->program_section)): /* display only relevant section of program list */?>
    <?=  $this->partial('edit/_subprogram.phtml' , array("collection" => $this->program_section,
						     "level" => 1)); ?>
  <? else: /* fallback - display entire program tree */ ?>
    <?=  $this->partial('edit/_subprogram.phtml' , array("collection" => $this->programs,
						     "level" => 0)); ?>
  <? endif ?>  
</ul>
