<h1>Edit Thesis Information</h1>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.1/jquery.min.js"></script>
<?= $this->javascript("jquery.local.js"); ?>

<p><b><?= $this->etd->title() ?></b></p>

<?=  $this->render('edit/_form_key.phtml'); ?>

<? if (isset($this->errors)): ?> <!-- validation errors -->
<ul class="errors">
   <? foreach ($this->errors as $error):  ?>
      <li><?= $error ?></li>
    <? endforeach  ?>
</ul>
<? endif ?>

<form id="thesis-info" method="post"> <!-- TODO: action ? -->
   <div class="side-by-side">
     <label for="last-name" class="required
       <?= array_key_exists('last-name', $this->errors) ? 'invalid' : ''?>">Last name</label>
     <?= $this->formText("last-name", $this->etd->mods->author->last); ?>
   </div>
   <div class="side-by-side">
     <label for="first-name" class="required
       <?= array_key_exists('first-name', $this->errors) ? 'invalid' : ''?>">First name</label>
     <?= $this->formText("first-name", $this->etd->mods->author->first); ?>
   </div>
   <p class="help-text">Your name as you would like it to be displayed on your ETD record.</p>
   
   <div>
     <label for="language" class="required
       <?= array_key_exists('language', $this->errors) ? 'invalid' : ''?>">Language</label>
      <p class="help-text">Select the language in which your thesis or
            dissertation is written.</p> 
       <?= $this->formSelect("language", $this->etd->mods->language->code, array(),
      	   $this->language_options); ?>
  </div>

     <label for="keywords" class="required
       <?= array_key_exists('keywords', $this->errors) ? 'invalid' : ''?>">Keywords</label>
   	<p class="help-text">Keywords to describe your work.
      Enter a single word or phrase per input; add as many as you like, but at least one.  </p>
   <div id="edit-keywords">
        <? foreach ($this->etd->mods->keywords as $kw): ?>
          <?= $this->formText("keywords[]", $kw->topic, array("class" => "repeating")); ?>
        <? endforeach ?>
             <!-- start with two blank inputs ? -->
             <?= $this->formText("keywords[]", '', array("class" => "repeating")); ?>
            <?= $this->formText("keywords[]", '', array("class" => "repeating")); ?>
   <a class="add-repeating-input clear">+ Add Keyword</a>
  </div>
  <div>
     <label for="degree" class="required
       <?= array_key_exists('degree', $this->errors) ? 'invalid' : ''?>">Degree</label>
      <p class="help-text">Select the degree which you will be receiving this submission period.</p> 
       <?= $this->formSelect("degree", $this->etd->mods->degree->name, array(),
      	   $this->degree_options); ?>
  </div>
            
  <?= $this->formSubmit("Save", "Save", array("class" => "button")); ?>
