<?= $this->javascript("util.js"); ?>

<h1>Edit School Membership</h1>
<p><b><?= $this->etd->title() ?></b></p>

<p>Select the school to which the ETD should be moved</p>
<p>NOTE: The program field will have to be assigned after changing schools</p>

<form action="<?= $this->url(array("action" => "save-school")) ?>" method="post" onsubmit="disableButton('save')">
<?=  $this->render('edit/_school_elements.phtml'); ?>
<p><?= $this->formSubmit("save", "save", array("class" => "button")); ?></p>
</form>