<p>Please review the data you have entered below.  If you need to make
changes, use the edit buttons on the right side of each section, and
then proceed to review/submit again.</p>

<p id="submit_warning" class="warning">
   <span id="exclamation">!</span>
   You are about to deposit the final version of your thesis or
   dissertation to the ETD Repository. Please review the document
   thoroughly. After the document is deposited, you will NOT be able
   to access the file to make changes of any kind without authorization
   from the administration of your school or program.
</p>

<? $this->role = $this->etd->getUserRole($this->current_user);  ?>
<style type="text/css">  <? /* hide a few divs that are not relevant for this page */ ?>
   p.note, #submission_status, #history {display:none; }
</style>
<?=  $this->render('view/fullrecord.phtml'); ?>

<?=  $this->render('submission/_reviewinfo.phtml'); ?>

</hr>
<p style="text-align:center">
  <a class="button" href="<?= $this->url(array('action' => 'submit'))
?>">Submit &gt;</a>
</p>
<? /* fixme; make this a form, add a hidden parameter to confirm that
    it was reviewed? */ ?>

