<h1>ETD Documents</h1>
<ul>
 <li><a href="<?= $this->url(array("action" => "about")) ?>">About the Repository</a></li>
 <li><a href="<?= $this->url(array("action" => "faq")) ?>">Frequently Asked Questions</a></li>
 <li><a href="<?= $this->url(array("action" => "instructions")) ?>">Submission Instructions</a></li>
 <li><a href="<?= $this->url(array("action" => "ip")) ?>">Intellectual Property</a></li>
 <li><a href="<?= $this->url(array("action" => "policies")) ?>">Policies & Procedures</a></li>
 <li><a href="<?= $this->url(array("action" => "boundcopies")) ?>">Bound Copies</a></li>
</ul>
