<?=  $this->render('email/_debug.phtml'); ?>
<? $etdlink = $this->url(array('controller' => 'view',
			       'action' => 'record', 'pid' => $this->etd->pid()), '', true);
/* FIXME: how to make this url absolute? */ ?>
<p>Dear <?= $this->etd->mods->author->first ?>,</p>

<p>This is to inform you that your <?= $this->etd->document_type() ?> entitled:
<blockquote><?= $this->etd->title() ?></blockquote>
can now be accessed in the Emory University ETD Repository at
<a href="<?= $etdlink ?>"><?= $etdlink ?></a>.</p>

<? if ($this->etd->etd_mods->embargo_request == "no"): ?>
<p>Upon submission, you agreed to grant open access to your work via the
web.  We appreciate your contribution to the intellectual output of
the University, and we hope that making your work as widely accessible
as possible will be mutually beneficial.</p>
<? else: ?>
<p>Upon submission, you chose to restrict access to your work via the
web.  Access to your thesis or dissertation will be restricted for
<?= $this->etd->etd_mods->embargo ?>.  Details describing your document will appear in
the repository's index, but the full text of your work will not appear
until the expiration of the access restriction period.</p>

<p>The access restriction associated with your <?= $this->etd->document_type() ?>
will expire automatically on <?= $this->etd->etd_mods->embargo_end ?>.  You will receive notice
(via e-mail to the permanent e-mail address which you provided) of the
impending expiration of the access restriction sixty (60) days prior
to the access restriction's expiration.  You are responsible for
contacting the Emory library if you need to extend that access
restriction for any reason.</p>

<p>Upon expiration of your access restriction, a non-circulating paper
copy of your dissertation will be produced and held in the University
Archives.</p>
<? endif ?>

<p>The library no longer requires that you create bound paper copies
of your thesis or dissertation.  Please contact your department or
program regarding their requirements for the production of paper
copies for department/program libraries or committee members.  To have
personal copies of your thesis or dissertaion produced, there are a <a
href="http://etd.library.emory.edu/docs/boundcopies">number of
vendors</a> who you may wish to contact, and their contact information
is listed on the ETD website.  (Paper copies of your dissertation will
also be available through UMI/Proquest once your thesis or
dissertation has been processed by them.)</p>

<p>You can expect your dissertation to appear in Emory's EUCLID library catalog in
the near future.</p>

<p>Congratulations!</p>

